### ISSUE TITLE
docs: User suggestions

### ISSUE THREAD

**Issue by PianSom** [unpoller/unpoller#317]
- ~Move Docker FAQ to the Getting help section~ done.
- ~Bare Metal Text suggestions:~
    - ~Use Bullets~ these sections were revamped.
- Application Configuration
    - Section was a bit unclear.  ~Would be nice to include a very simple config (for Influx, for example).~  done 
    - You could instead move the existing description of the config file to the Getting Help section. _not sure?_
- ~Creating the DB should be either covered in the installation sections or in the InfluxDB section, not in final steps~ done.
- ~Grafana configuration should be it’s own section, not in final steps~. final steps renamed.
- ~Grafana section should cover installing required plugins~ done.

**Comment by davidnewhall** [comment]
I'll be working on docs over the next few weeks.

**Comment by davidnewhall** [comment]
I tackled most of this. I spruced up the configuration page a bit too. Many things were moved around. it took me a while to figure out where to put everything, but I think it's pretty dang good now. Please let me know and send more feedback!
