### ISSUE TITLE
Feature request: threat management map

### ISSUE THREAD

**Issue by modem7** [unpoller/unpoller#320]
Hey guys,

Is there a way to get the threat management entries from the udmp to display on a map? Sort of like a live-ish cyberthreat map?

Thanks!

**Comment by davidnewhall** [comment]
No and I don't plan to add that data. I don't personally find any value in seeing random IPs on a table.

**Comment by jackm9367** [comment]
I think that just being able to pull the total threat per severity (i.e. low risk, medium, high) would be useful as it allows the SOC to identify increases in attempted attacks, following which they could use the UniFi Controller to view the detailed threat data.
