### ISSUE TITLE
Which metric provides me with current network activity?

### ISSUE THREAD

**Issue by aidenmitchell** [unpoller/unpoller#330]
![Screen Shot 2021-03-26 at 12 22 08 PM](https://user-images.githubusercontent.com/30846409/112682857-ef09c700-8e2d-11eb-9628-ce0bce82b589.png)
I'd like this on my Grafana dashboard, which Prometheus query would this data appear under?

**Comment by davidnewhall** [comment]
There are three numbers in your screenshot. Which one do you want?

**Comment by aidenmitchell** [comment]
Sorry for not being clear. I'd like the current download and upload speed/activity (the ones by the arrows).

**Comment by davidnewhall** [comment]
Honestly, I have no idea what those numbers represent. My 3 APs are currently averaging less than 1MB/s in and out. That'd make 6MB/s total (and it's more like 3 really). My dashboard is currently saying 70-90Mbps up and 1-7Mbps down. (it changes as I refresh)  This doesn't line up with the port statistics either, which look an awful lot like the virtual AP stats. Not sure what to say. 
![Screen Shot 2021-03-26 at 1 11 42 PM](https://user-images.githubusercontent.com/2402929/112687505-d2bd5880-8e34-11eb-9193-40b4aee76c82.png)

**Comment by davidnewhall** [comment]
I mean, these are all identical. Three different metrics for what is basically the same data. All in alignment. None of these match what I
![Screen Shot 2021-03-26 at 1 24 26 PM](https://user-images.githubusercontent.com/2402929/112689054-fd101580-8e36-11eb-8c5b-7c2227bf475d.png)
 see on my dashboard.

**Comment by davidnewhall** [comment]
If you can figure out where that metric shows up in the API, I can show you how to graph it. My fear is that it's fictional since it seems entirely inaccurate on my site.

**Comment by paulfantom** [comment]
Both values come from `list_health()` in stats API. The left one is `tx_bytes-r` from LAN subsystem, the right one is `tx_bytes-r` from WLAN subsystem.

**Comment by davidnewhall** [comment]
I assume `list_health()` comes from the php browser? I'll find the proper api path but that seems useful. I don't think that's one that gets pulled now.

**Comment by paulfantom** [comment]
Yeah, that's from https://api-browser-demo.artofwifi.net/#

I took a look at JS code from unifi demo site at https://demo.ui.com/manage/site/default/dashboard. The object responsible for left arrow is in HTML div with class `unifiNetworkStatusDiagramConnectorSpeed--withLeftArrowAfter`, for right one is in `unifiNetworkStatusDiagramConnectorSpeed--withRightArrowBefore`. Those in turn map to `networkStatusDiagramCtrl.siteHealthLan` and `networkStatusDiagramCtrl.siteHealthWlan` in JS code. Both of those functions use `tx_bytes-r` from different subsystems. I am 99% sure those are correct mappings.
