### ISSUE TITLE
Controller Version Suport - 6.0.x and newer?

### ISSUE THREAD

**Issue by ikkerus** [unpoller/unpoller#332]
Hey folks,

my unifi-poller is running properly since a week or so. On the official github README.md page there's a small icon saying 5.12.x and 5.13.x UniFi Controller Version supported. What about 6.0.x and the new 5.1.71? Will there be an update?

Couldn't find anything on the internet. 

Thanks, ikkerus

EDIT, Add: Found, that #324 is at least showing some issues with 6.1.70

**Comment by davidnewhall** [comment]
It probably works fine on most versions. Things change once in a while and we have to adjust. The last few comments on #324 show that happening in real time.

Really though, I just haven't updated the readme in a long time.

**Comment by ikkerus** [comment]
I just tried to help on #324 - and thanks for your reply.
I've sucessfully tested unifi-poller using dockr:latest with the following UniFi Controller Versions:

- 5.14.23
- 6.1.71

There are some slight adjustments needed for the official grafana dashboards though when running controller version 6.1.71.

**Comment by jesselee04** [comment]
Does this with with the Dream Machine Pro by chance?

2021/04/01 14:57:16 [ERROR] Controller 1 of 1 Auth or Connection Error, retrying: unifi controller: (user: poller): https://10.1.1.1:8443/api/login (status: 404 ): authentication failed


2021/04/01 14:57:16 [INFO] Poller->InfluxDB started, interval: 30s, dp: false, db: unifi, url: http://10.1.2.33:8086


2021/04/01 14:57:16 [INFO] Internal web server disabled!


2021/04/01 14:57:16 [INFO] Loki config missing (or disabled), Loki output disabled!


2021/04/01 14:57:16 [INFO] Prometheus exported at http://0.0.0.0:9130/ - namespace: unifipoller


2021/04/01 14:57:46 [INFO] Re-authenticating to UniFi Controller: https://10.1.1.1:8443


2021/04/01 14:57:46 [ERROR] metric fetch for InfluxDB failed: re-authenticating to https://10.1.1.1:8443: unifi controller: (user: poller): https://10.1.1.1:8443/api/login (status: 404 ): authentication failed


2021/04/01 14:58:16 [INFO] Re-authenticating to UniFi Controller: https://10.1.1.1:8443


2021/04/01 14:58:16 [ERROR] metric fetch for InfluxDB failed: re-authenticating to https://10.1.1.1:8443: unifi controller: (user: poller): https://10.1.1.1:8443/api/login (status: 404 ): authentication failed


2021/04/01 14:58:46 [INFO] Re-authenticating to UniFi Controller: https://10.1.1.1:8443


2021/04/01 14:58:46 [ERROR] metric fetch for InfluxDB failed: re-authenticating to https://10.1.1.1:8443: unifi controller: (user: poller): https://10.1.1.1:8443/api/login (status: 404 ): authentication failed


2021/04/01 14:59:16 [INFO] Re-authenticating to UniFi Controller: https://10.1.1.1:8443


2021/04/01 14:59:16 [ERROR] metric fetch for InfluxDB failed: re-authenticating to https://10.1.1.1:8443: unifi controller: (user: poller): https://10.1.1.1:8443/api/login (status: 404 ): authentication failed


2021/04/01 14:59:46 [INFO] Re-authenticating to UniFi Controller: https://10.1.1.1:8443


2021/04/01 14:59:46 [ERROR] metric fetch for InfluxDB failed: re-authenticating to https://10.1.1.1:8443: unifi controller: (user: poller): https://10.1.1.1:8443/api/login (status: 404 ): authentication failed


2021/04/01 15:00:16 [INFO] Re-authenticating to UniFi Controller: https://10.1.1.1:8443


2021/04/01 15:00:16 [ERROR] metric fetch for InfluxDB failed: re-authenticating to https://10.1.1.1:8443: unifi controller: (user: poller): https://10.1.1.1:8443/api/login (status: 404 ): authentication failed

**Comment by davidnewhall** [comment]
@jesselee04 - Please open a new issue.

**Comment by thundergreen** [comment]
Having issue as well logging into unifi Controller 6.1.71 . Erro message:

```
2021/04/09 20:13:15 [ERROR] metric fetch for InfluxDB failed: re-authenticating to https://192.168.1.1:443: unifi controller: (user: hassio): https://192.168.1.1:443/api/auth/login (status: 401 Unauthorized): authentication failed
```

**Comment by davidnewhall** [comment]
@thundergreen Please open a new issue.

**Comment by bullshit** [comment]
I have a working installation with v6.1.71. Did you use a user with the role 'Admin' and Permissions 'System Stats'. The role 'Admin' has as default permission 'Adopt'.

**Comment by rkm** [comment]
I've just successfully configured this for my controller v6.2.26. The only issue I encountered was that the "new" style controller UI hides the option to create a local admin with a password. Switching back to the old style dashboard restored this option.

**Comment by davidnewhall** [comment]
Ubiquiti made it clear they do not like this product, and will likely take steps to make it harder to use. Sucks. Glad you figured it out!

**Comment by bullshit** [comment]
They are getting evil ;(

**Comment by ymichel** [comment]
Using V2.1.3 but have the issue 
_controller: unexpected end of JSON input_
When using 6.5.5 from my PI. Interestingly, the docker container is working properly. Any insights on what I could have potentially done wrong?

**Comment by tablatronix** [comment]
Anyone know what this issue is or how to debug? Mine has stopped working and is giving me the same error, tried different roles, maxxed perms. nothing. UniFi OS UCK G2 Plus 2.4.5

**Comment by tablatronix** [comment]
I had to use an older role that was Custom, Could not create a new one that would allow auth. Switch to old UI and will see if I can find whats different

**Comment by davidnewhall** [comment]
@PianSom sent me a CK2 to play with so I'll have more ability to help with those things ... should be here soon.
