### ISSUE TITLE
Memory Leak? Tied to unifi-poller in a Docker container

### ISSUE THREAD

**Issue by lux4rd0** [unpoller/unpoller#339]
Hello - I'm using golift/unifi-poller:2.1 on: Linux 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux. Docker details:

```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:33:55 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:32:17 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

What I've found is that several times I'm seeing memory keep going up in a regular fashion until - well - it runs out of memory. Was curious if there are any others that have faced this issue? Or ways to help understand what might be consuming all the memory??

![Screen Shot 2021-04-15 at 11 56 44 AM](https://user-images.githubusercontent.com/30187533/114909283-97ce9500-9de2-11eb-9f11-8c87fb2c8d76.png)

Thanks!

_DS

**Comment by davidnewhall** [comment]
My Poller has been running 4 days and it's using around 100MB of ram. This is the `docker stats` output for my container. Poller is a pretty lightweight app. It could certainly have a bug causing a memory leak, but it should not use more than a couple hundred megabytes of ram during normal use. I have mine configured to collect _everything_ and send it to InfluxDB, Prometheus and Loki.

![Screen Shot 2021-04-15 at 12 45 02 PM](https://user-images.githubusercontent.com/2402929/114929307-783a6b00-9de8-11eb-8848-50e2b5e15678.png)

**Comment by davidnewhall** [comment]
And here's the others just to be _complete_.
```
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
b163180f13cb        prometheus          0.00%               334.4MiB / 125.9GiB   0.26%               7.63GB / 61.7MB     1.14GB / 1.29GB     23
813adff88c8c        Influxdb            2.28%               793.7MiB / 125.9GiB   0.62%               7.43GB / 189MB      4.08GB / 33.6GB     34
3f3df3589cc5        loki                0.01%               42.74MiB / 125.9GiB   0.03%               39.3MB / 4.57MB     131MB / 254MB       25
```

**Comment by lux4rd0** [comment]
I'm using about 30MB right now with a restart. I think under normal circumstances - it's all happy and does what it does really well. I think there's an exception that happens and I'm going to see what I can do to correlate it. There's no shell access in your docker image :) so things like grabbing a profile of the go routine has not been successful yet. But here's my Prometheus scrape memory details:

<img width="1616" alt="unifi-poller-prom" src="https://user-images.githubusercontent.com/30187533/114932422-1c2e1180-9dfd-11eb-96c2-7bb0c8ede05e.png">

I had container logs being sent over to Loki but for some reason - they died and I wasn't able to grab them. I'll keep a better look at things as it's now fallen into a pattern. :)

Thanks!

**Comment by davidnewhall** [comment]
Yeah that seems not so great. Maybe the logs will reveal something strange happening. 🤞 

This may be one of the few times I recommend enabling the web server. It's not super-well documented, but if you turn it on and set an api key you can `curl unifi-poller:37288/debug/vars` and it will print out internal go memory and runtime information.

Webserver usage is documented here: https://unifipoller.com/docs/advanced/webserver

Please give it a go and provide feedback. Those docs are new and I'm happy to update them if anything is confusing.

**Comment by lux4rd0** [comment]
I had the situation happen again but didn't have the Web server enabled on the container yet. I just made the updates and tested them for validation. This:

`http://unifi-poller:37288/`

It gives me this:

```
This is the main page.
And it's empty.
```

`http://unifi-poller:37288/debug/vars`

It gives me this:

`404 page not found`

With this in the container logs:

`2021/04/18 14:25:55 [INFO] 172.22.0.1 unifi-poller - [04/18/2021:14:25:55 +00:00] "GET http://localhost:37288/debug/vars HTTP/1.1" 404 19 "" "curl/7.29.0" 38µs`



I'll share more once I can get better correlation and causation.
Can you confirm the Web server logging configuration and 404 error?

On my side - this memory issue may be related to another docker issue that's been plaguing my system that seems to result in some weird networking stack issues while at the same time impacting my Loki docker driver. If they're related - it's possible that fixing one fixes the other. (I don't know which is the cause and which is the impact yet.)

Thanks!

_DS

**Comment by davidnewhall** [comment]
Well crap, I commented out the memory usage web handler.
https://github.com/unifi-poller/webserver/blob/b4db5feaea83ab0b1dff6a68800981a50689ee24/server.go#L111

A new docker tag `debug_vars` is building now. Docker has been slow lately, so I expect this to be available in an hour or so. Once it pops up, pull that, and `/debug/vars` should work..

**Comment by lux4rd0** [comment]
Cool - I just grabbed it and it's showing me some nice JSON metrics. Once I run into the issue - I'll pull those items and see what it looks like. Thanks for the weekend assistance!!

**Comment by lux4rd0** [comment]
Attaching the result of my /debug/vars
![memory](https://user-images.githubusercontent.com/30187533/115632656-d5915900-a2cd-11eb-835a-673765fc3f8d.png)

[unifi-poller.txt](https://github.com/unifi-poller/unifi-poller/files/6354413/unifi-poller.txt)

**Comment by davidnewhall** [comment]
Please share your poller configuration and the logs.  It's definitely using 600-700MB ram, but I have no idea how to reproduce this, so I need to see what it's doing and how it's configured in your environment.

**Comment by lux4rd0** [comment]
The logs always die the container messes up (pushing to Loki) - so I pulled the Loki log driver and restarted the container. That should hopefully give me logs the next time this happens. _(I'm still kind of maybe sort of suspicious something with Loki, in general, is causing this issue... but I'm not sure yet.)_

**Comment by davidnewhall** [comment]
Try disabling some things to see if you can narrow down what may be causing this. ie. turn all these off, and then turn them back on 1 at a time after it runs for a day or two without problems.
```
      UP_UNIFI_DEFAULT_SAVE_ALARMS: "true"
      UP_UNIFI_DEFAULT_SAVE_ANOMALIES: "true"
      UP_UNIFI_DEFAULT_SAVE_DPI: "true"
      UP_UNIFI_DEFAULT_SAVE_EVENTS: "true"
      UP_UNIFI_DEFAULT_SAVE_IDS: "true"
```

**Comment by lux4rd0** [comment]
@davidnewhall I've been running this for 30 days now without another issue. Will give it a little more time and then close this until it happens again...

**Comment by davidnewhall** [comment]
Interesting... Glad to hear things have normalized!

**Comment by lux4rd0** [comment]
Closing...
