### ISSUE TITLE
Dashboard for old Controller GUI to show Dropped Packages & AP Retry Rate

### ISSUE THREAD

**Issue by bondskin** [unpoller/unpoller#344]
All,

I am still using the old Controller GUI as it gives me much more information compared to the new GUI.
However, I like to have the two GUI dashboard graphs "Dropped Packages and Access Point Retry Rate" in Grafana, by using Unifi-Poller.

In the predefined Grafana Dashboards I did not find such graphs.
Is the relevant information being pulled by Unify-Poller? Which tables/fields contain the information?

thx
MIke

**Comment by davidnewhall** [comment]
> "Dropped Packages and Access Point Retry Rate" 

These sound like terms you'd see in the controller GUI. I have no idea what values these map to in the API. I'd recommend finding the numbers you're interested in the API output and then I can tell you where they're written to in InfluxDB or Prometheus. To see the API output, run `unifi-poller -j d` - this outputs all device json from the API endpoint on the controller.
