### ISSUE TITLE
unifi-poller on windows, keep running while logged out?

### ISSUE THREAD

**Issue by yldrmdgn** [unpoller/unpoller#345]
How can I make it as a persistent service on a windows server background with its parameter regardless of affecting log off. I have looked at some samples but could not find a solution. 
This is executed on a windows command line, below. However, I want to run it as a service. I have tried .bat, set command, nssm tool to create a service, but I could not attach its -c up.conf parameters. How can it be run as a service on a windows server? Thanks

unifi-poller.exe -c up.conf

**Comment by davidnewhall** [comment]
The default config file location on Windows is `C:\ProgramData\unifi-poller\up.conf`
If the config file is there you do not need to pass `-c anything` as a parameter.

Beyond that, this app has no special hooks to make it work as a Windows service. I'm afraid I do not use Windows enough to give you information on how to run this app without logging, or after logging out.  I'll leave this issue open in case someone else knows.

**Comment by platinummonkey** [comment]
Using powershell - Declare a service:

```
New-Service -Name "Unpoller" -DisplayName "Unpoller Service" -Description "Unpoller Service" -StartupType Manual -BinaryPathName "Path-To-Unpoller.exe --service"
```

Start the service:

```
Start-Service -Name "Unpoller"
```

Stop the service:

```
Stop-Service -Name "Unpoller"
```

Uninstall a service:

```
sc.exe Delete "Unpoller"
```

**Comment by davidnewhall** [comment]
Someone wrote a wiki entry for unpackerr on this topic. https://github.com/davidnewhall/unpackerr/wiki/Running-unpackerr-as-a-Windows-service

Should be mostly the same process. The procedure that @platinummonkey posted looks pretty easy though.
