### ISSUE TITLE
unifipoller.com site appears to have been taken over by a trash blog

### ISSUE THREAD

**Issue by moon127** [unpoller/unpoller#361]
It looks like unifipoller.com docs site has been taken over or their is a vhost config issue causing a blog about trash to be displayed instead?

**Comment by bondskin** [comment]
https://community.ui.com/questions/UniFi-Poller-Store-UniFi-Controller-Metrics-in-Prometheus-or-InfluxDB/58a0ea34-d2b3-41cd-93bb-d95d3896d1a1#answer/434c6ee6-f769-4120-8d91-98955e8e3c13
"Ubiquiti have issued a threatening cease and desist letter to the developer"

**Comment by stephen304** [comment]
Is there a mirror of the documentation anywhere? I'm trying to figure out what the installation entails.

**Comment by davidnewhall** [comment]
[UniFi_Poller_CD.pdf](https://github.com/unpoller/unpoller/files/6704089/UniFi_Poller_CD.pdf)

**Comment by stephen304** [comment]
I don't know anything about an old or new repo, I just got here from Googling unifi prometheus exporter and all the links in the readme seem to point to the "old" site. It would be great to have a quick getting started in the readme for anyone just discovering the project.

**Comment by davidnewhall** [comment]
readme updated.

**Comment by davidnewhall** [comment]
And keep in mind, a lot of the docs are wrong because of the impending application rename. All the downloads are still named `unifi-poller` (not `unpoller`, yet).
