### ISSUE TITLE
Poller attempting to authenticate at wrong controller hostname

### ISSUE THREAD

**Issue by crockk** [unpoller/unpoller#362]
Hi there,

I'm not sure if this is an issue with my docker networking or something else, but it seems to me that my dockerized instance of UnPoller is not using the configured hostname to attempt to authenticate with the controller.  Instead, the poller is attempting to use localhost. Here is the relevant log output:

```
2021/07/07 21:13:46 [INFO] Re-authenticating to UniFi Controller: https://127.0.0.1:8443
2021/07/07 21:13:46 [ERROR] metric fetch failed: re-authenticating to https://127.0.0.1:8443: unifi controller: making request: Get "https://127.0.0.1:8443/": dial tcp 127.0.0.1:8443: connect: connection refused
```

And my configuration which specifies the hostname for the controller is:
```
[unifi.defaults]
  # URL for the UniFi Controller. Do not add any paths after the host:port.
  # Do not use port 8443 if you have a UDM; just use "https://ip".
  url = "https://host.for.controller:8443"

  # Make a read-only user in the UniFi Admin Settings, allow it access to all sites.
  user = "poller"

  # Password for UniFi controller user (above).
  # If the password provided here begins with file:// then the password is read in from
  # the file path that follows the file:// prefix. ex: file:///etc/unifi/password.file
  # ex: file:///etc/unifi/passwd.file, windows: file://C:\\UserData\\Unifi\\Passwd.txt
  pass = "xxxxxxx"
```

As you can see, it seems to me like the poller is not using my passed-in configuration. Any ideas? For reference my docker run command is:
```
docker run -d --name unifi-poller --restart always -p 9009:9130 -v /etc/unifi-poller/unpoller.conf:/config/unpoller.conf golift/unifi-poller"`
```

**Comment by davidnewhall** [comment]
Resolved on Discord Let me know if I can help further!

**Comment by alexford** [comment]
Just for reference because I had the same problem: as of now, the conf file still needs to be called `unifi-poller.conf`, even though the documentation has been updated to `unpoller.conf`
