### ISSUE TITLE
InfluxDB sizing on Raspberry Pi

### ISSUE THREAD

**Issue by bondskin** [unpoller/unpoller#366]
Hi all,

Are there any recommendations on interval, timeouts and data retention settings for Unpoller?

The data collection via UnPoller works fine (interval 1m).
I tried to keep the data in InfluxDB for 30 days but it seems my Pi was not powerful enough to handle it.
Now I have changed it to two weeks and I will observe the situation.

**Comment by davidnewhall** [comment]
@PianSom has a lot of experience running this on a Pi. I think he gave up though and put it on a more powerful computer. 
I'd probably recommend an interval of 2m to cut the data collected in half. This may allow you to get to 30 days, or close to it.

**Comment by PianSom** [comment]
Yeah, I never looked back after moving to a nuc. I was on a Pi4 for quite a while but got fed up with the limitations. 

The other thing is to turn off dpi if you can manage without it
