### ISSUE TITLE
Provide alternate image registry to dockerhub

### ISSUE THREAD

**Issue by onedr0p** [unpoller/unpoller#368]
Hello,

In order to combat dockerhub's imposed rate limits it would be great to host these images on ghcr or quay.io. Are there on any thoughts from the community on this initiation?

**Comment by davidnewhall** [comment]
There haven't been new releases in a long time. I can't imagine this is a huge problem for folks. That said, Dockerhub killed my ability to build my projects automatically, wont respond to my support email, and want $300/year to use their builder. I'm not pleased and would love to use something else.

**Comment by onedr0p** [comment]
Switch to Github workflows and have your image built and pushed to GHCR, it's free.

**Comment by platinummonkey** [comment]
moved to ghcr.io - https://github.com/unpoller/unpoller/pkgs/container/unpoller
