### ISSUE TITLE
Using WAN2 as LAN port

### ISSUE THREAD

**Issue by gokou340** [unpoller/unpoller#374]
Hello!
I currently have my USG4 using WAN2(SFP) as the LAN1 port, this causes the LAN throughput on the USG dashboard to not have any results. I looked at the metrics that is pulled and I didn't see anything that I could use to grab metrics from eth3.

Is there a way to switch what port the LAN metrics are pulled from?

Thanks!

**Comment by platinummonkey** [comment]
hm, all the other ports should be reporting data, can you share your configuration and what outputs you're using?
