### ISSUE TITLE
Grafana+InfluxDB not on Default database

### ISSUE THREAD

**Issue by marcolino7** [unpoller/unpoller#377]
Hi,
I have setup influxdb + grafana. On grafana I have some other dashboard using same influxdb connection, so default dabase on the influx connection is not the one used by unpoller.
The result is that unpoller dashboard does not work, until I setup default db on influx connection, but this broke my other dashboard.
Is there a way to force dashboard to not use default connection and specify unflux DB name?

Thanks in advance

**Comment by obzbdc** [comment]
Do you have a datasource specifically named "InfluxDB-unifipoller"?
I have a default datasource of InfluxDB for other dashboards and one called "InfluxDB-unifipoller" which maps to the unifi database in Influx and everything just works...

If the above doesn't get you to a working setup let me know and I'll drop some screenshots here.

**Comment by davidnewhall** [comment]
>  until I setup default db on influx connection

I'm not sure what this means? One of the steps/directions is to create a database named `unifi`. InfluxDB has [no default database](https://docs.influxdata.com/influxdb/v1.8/introduction/get-started/).

> Is there a way to force dashboard to not use default connection and specify unflux DB name?

You may choose any database name you wish. You give the db name to the unpoller config. You give it to Grafana when you add the datasource.
