### ISSUE TITLE
USG cpu missing

### ISSUE THREAD

**Issue by tablatronix** [unpoller/unpoller#378]
For some reason my cpu reporting has been at 0% since like 10/7 
Any hints where I can test this endpoint and see whats going on? 
All other metrics seem to be ok

I am on beta channel. and update often so could have been a ui change? can anyone confirm same?

**Comment by platinummonkey** [comment]
is this still a problem on 2.4.6+ ?

**Comment by platinummonkey** [comment]
I too have a UDM Pro, so going to close this 👍
