### ISSUE TITLE
Values at USW between the correct values always to 0

### ISSUE THREAD

**Issue by futureweb** [unpoller/unpoller#379]
Hello,

first let me say thank you for this great tool ... !!

It works pretty well so far - but strangely, the values displayed on my switches are occasionally down to 0 ... although there is constant traffic through this post ... what could that have to do with?

Thank you, best regards from Tyrol
Andreas

![grafik](https://user-images.githubusercontent.com/1698881/140301630-82fbd0e5-590b-41ee-b874-781ee171f84c.png)

**Comment by futureweb** [comment]
changes interval = "30s" to interval = "1m" ... guess this should fix this behaviour! :-)

**Comment by davidnewhall** [comment]
Yeah, some controllers just don't update as often as every 30 seconds. Your fix sounds appropriate. Good luck!
