### ISSUE TITLE
Remove & update references to Unifi Poller in the documentation.

### ISSUE THREAD

**Issue by KzBoy** [unpoller/unpoller#381]
There are still references to `Unifi Poller` that need removed from the documentation.

The pages that I know of with refences are:
- https://github.com/KzBoy/unpoller.github.io/blob/master/documentation/docs/install/freebsd.md
- https://github.com/KzBoy/unpoller.github.io/blob/master/documentation/docs/install/linux.md
- https://github.com/KzBoy/unpoller.github.io/blob/master/documentation/docs/install/macos.md

There may be other pages too.

This might be a good project for a first timer.

**Comment by ajschroeder** [comment]
I'd be happy to update the documents with the name changes, however I just tried to install this on my FreeBSD system and there is no port/package called `unifi-poller` or `unpoller`. Is FreeBSD supported still?

**Comment by platinummonkey** [comment]
FreeBSD is supported, will look into where the ports were published. There are builds available in this repo’s releases page

**Comment by davidnewhall** [comment]
KzBoy already put I a huge PR for this... https://github.com/unpoller/unpoller.github.io/pull/3
ports history: https://github.com/unpoller/unpoller/issues/245

**Comment by ajschroeder** [comment]
Good to know it supported still. It would be great if the package could be built or installed using the ports/pkg system in FreeBSD.

From: Cody Lee ***@***.***>
Date: Tuesday, December 20, 2022 at 12:31 PM
To: unpoller/unpoller ***@***.***>
Cc: TheHitman1977 ***@***.***>, Comment ***@***.***>
Subject: Re: [unpoller/unpoller] Remove & update references to Unifi Poller in the documentation. (Issue #381)

FreeBSD is supported, will look into where the ports were published. There are builds available in this repo’s releases page
