### ISSUE TITLE
Incorrect docker-compose in documentation

### ISSUE THREAD

**Issue by Thelvaen** [unpoller/unpoller#383]
docs says:
```docker
  unpoller:
...
    volumes:
      - /YOURLOCALPATH/unpoller:/config
```

what works is:
```docker
  unpoller:
...
    volumes:
      - /YOURLOCALPATH/unpoller:/etc/unifi-poller/
```

**Comment by davidnewhall** [comment]
What's correct is:

https://github.com/unpoller/poller/blob/master/build_unix.go#L6

You likely had the wrong name for the file. Docs are definitely not accurate. A lot of it because of the repo name change.

**Comment by Thelvaen** [comment]
yeah, doc also mention the name as `unpoller.conf` and not one of the two in the go source file ^^

**Comment by Thelvaen** [comment]
Ok, so I just found that the doc in https://unpoller.com/docs/install/dockercompose & https://unpoller.com/docs/install/docker seems outdated, and that it's better to use the one in https://github.com/unpoller/unpoller.github.io ^^

**Comment by RiRa12621** [comment]
I fell hard over this. @davidnewhall anything one could help with to publish the latest version of the docs website?

**Comment by alexander-zimmermann** [comment]
@RiRa12621 me too. happy to help as well.
