### ISSUE TITLE
SFP+ LAN port is not being registered as part of the LAN group

### ISSUE THREAD

**Issue by Thelvaen** [unpoller/unpoller#384]
The SFP+ LAN port is not correctly assigned to the LAN group, hence unifipoller_device_lan_receive_bytes_total stays at 0, and graphs remains empty.
```
# HELP unifipoller_device_lan_receive_bytes_total LAN Receive Bytes Total
# TYPE unifipoller_device_lan_receive_bytes_total counter
unifipoller_device_lan_receive_bytes_total{name="Cerebro",port="lan",site_name="Default (default)",source="https://cerebro.lan.raven-ip.com"} 0
```
![unknown](https://user-images.githubusercontent.com/19350574/145748221-eb6a3a14-136b-4d86-b430-88c7f30d7928.png)

API dump sent by mail with the issue number here as reference.

**Comment by davidnewhall** [comment]
Thank you!!
