### ISSUE TITLE
user udm no read function

### ISSUE THREAD

**Issue by slashw** [unpoller/unpoller#387]
Made a reinstall after factory reset, then making a user unifipoller.
There is no more the read function for the user, only view.
Wil this be a problem?

Had it running until yesterday, then i f.ckt up my network and had to do a factory reset.
Now i am getting no data in grafana.
The network addresses are all the same as before.

When i look back in grafana i can see the data before the reset.

 unifi-poller -j d
2021/12/23 15:33:22 [ERROR] Controller 1 of 1 Auth or Connection Error, retrying: unifi controller: (user: poller): https://192.168.1.1/api/auth/login (status: 401 Unauthorized): authentication failed

2021/12/23 15:33:22 [ERROR] re-authenticating to https://192.168.1.1: unifi controller: (user: poller): htps://192.168.1.1/api/auth/login (status: 401 Unauthorized): authentication failed

**Comment by davidnewhall** [comment]
You need to adjust the permissions on that user to fix this.

**Comment by slashw** [comment]
This is what i thought also.
I am very sorry for my dumbness,  but i am a noob.
So my next question, where must i adjust these permissions?
My user unifipoller on the udm cant select the read function because it isn't there any more only the view  function (and some other)

**Comment by rtylerdavis** [comment]
So your unpoller user in the UDM Pro users setting is set to "view only" for unifi network, right?

**Comment by slashw** [comment]
The error was indeed from my udm settings. Apparently i had to use/make a different local username and passw.
I chanced it and went to bed (fed up with it) 
I looked this morning and it is back, but with no history.
Apparently it has made a new database?
Anyway, i am happy it is back.   

Thanks all for the input. @rtylerdavis , yes that was correct, but see above.
