### ISSUE TITLE
Unraid UnPoller Docker Unable To Write Data To UnfluxDB

### ISSUE THREAD

**Issue by GrantNagel** [unpoller/unpoller#388]
Despite having the correct credentials for both Influxdb and unifi the unraid docker does not seem to be populating the unifi database. Has anyone come across this issue?

Output from the unpoller log:
2021/12/27 14:24:51 [ERROR] influxdb.Write(points): {"code":"unauthorized","message":"Unauthorized"}

**Comment by davidnewhall** [comment]
This appears to be an invalid username and password for influxDB. By default, influx does not require a password, so this means you've modified that configuration. Something to look into there..

**Comment by ecdeveloper** [comment]
@GrantNNZ which InfluxDB version you're using? I had the same exact issue but I accidentally installed the latest one (influxdb@2.0.9), whereas UnPoller requires 1.8 or so.

**Comment by platinummonkey** [comment]
influx 2 support added recently
