### ISSUE TITLE
Incompatible error

### ISSUE THREAD

**Issue by sojab0on** [unpoller/unpoller#391]
After running the poller for a while and it worked great my system was rebooted for an update now it give an error 
This vesion of unifi-poller.amd64.exe is not compatibel with  this Windows-version 

system is running Windows 10 pro 21H2 

i have downloaded the most recent release version 
please check and release an update

**Comment by platinummonkey** [comment]
there's been a few releases since this time, can you verify again? https://github.com/unpoller/unpoller/releases
