### ISSUE TITLE
Grafana Dashboard Publish Snapshot 

### ISSUE THREAD

**Issue by Dedetwink** [unpoller/unpoller#397]
Hello,

I have created a Dashboard with Grafana.
I would like to Publish this Dashboard so that everyone that has the link is able to see what is in there and play with the pannels. 

I have used Docker on my VM and created a container for Grafana and one for Influxdb (my database). From an API I am importing data to the DB and then with this data I have created my different pannels.

When I try to publish the dashboard I don't find the option to select all the pages that are linked to it, and once published the panels are not working and I get this error:

![secondpage](https://user-images.githubusercontent.com/98647573/151661503-71b6520c-b386-40ac-849b-53e46f525367.PNG)

From what I could find in other issues I noticed that:
UP_UNIFI_DEFAULT_SAVE_DPI =true
should be configured as true. 

But I don't understand where should I look for it.
Any kind of guidance for this configuration would be much appreciated. Thank you.

**Comment by platinummonkey** [comment]
was this figured out? I'm not sure this is an unpoller specific issue or more of a general grafana issue
