### ISSUE TITLE
One AP missing in dashboard "UniFi-Poller: UAP Insights - InfluxDB"

### ISSUE THREAD

**Issue by jithinsarath** [unpoller/unpoller#400]
Env details:
Controller, Unpoller, Grafana, InfluxDB are running on Docker on a Pi. Brand new setup. 
A simple site with three UAP AC LRs

Issue:
In the dashboard "UniFi-Poller: UAP Insights - InfluxDB", there is no data for one of the three APs. Other two are showing up fine. 
The same data shows up in the other dashboard "UniFi-Poller: Client Insights - InfluxDB". See attached screenshots. 

I checked the DB and it appears that the data isn't even coming for the 3rd AP in uap measurement.

![uap_insights](https://user-images.githubusercontent.com/1292392/156223330-45360253-dc95-4a9b-a44c-1264196cff87.png)
![client_insights](https://user-images.githubusercontent.com/1292392/156223369-48dd9337-c96f-4a43-a54f-cc1a9a7278d7.png)

**Comment by davidnewhall** [comment]
Restarting your controller will probably fix it. Controller just isn't providing that data.

**Comment by jithinsarath** [comment]
🤦‍♂️ The proverbial solution to all problems. Restart. My bad, please close this issue.
