### ISSUE TITLE
unable to get server version - udmpro 1.11.1

### ISSUE THREAD

**Issue by benchristian88** [unpoller/unpoller#403]
Getting this error in logs of unifipoller 

2022/03/09 21:57:47.234498 updateweb.go:193: [INFO] Re-authenticating to UniFi Controller: http://192.168.3.1
2022/03/09 21:57:47.234624 updateweb.go:213: [DEBUG] Requesting http://192.168.3.1/ to determine API paths
2022/03/09 21:57:47.241938 updateweb.go:213: [DEBUG] Requesting http://192.168.3.1/api/login, with params: true, cookies: 0
2022/03/09 21:57:47.271093 updateweb.go:213: [DEBUG] Requested http://192.168.3.1/api/login: elapsed 29ms, returned 450 bytes
2022/03/09 21:57:47.271226 updateweb.go:213: [DEBUG] Requesting http://192.168.3.1/status, with params: false, cookies: 0
2022/03/09 21:57:47.279219 updateweb.go:213: [DEBUG] Requested http://192.168.3.1/status: elapsed 8ms, returned 450 bytes
2022/03/09 21:57:47.279668 logger.go:27: [ERROR] metric fetch for InfluxDB failed: re-authenticating to http://192.168.3.1: unifi controller: unable to get server version: invalid character '<' looking for beginning of value**

trying to connect to udmpro 1.11.1.  user is "view only", limited admin.  this is a new install, so trying to get past this step, and then hopefully graphana and influx work.

**Comment by davidnewhall** [comment]
Use `https://`

**Comment by benchristian88** [comment]
thanks, that worked. cheers
