### ISSUE TITLE
Unable to access Grafana with running unraid unifi-poller template

### ISSUE THREAD

**Issue by Gtsupq** [unpoller/unpoller#404]
I have installed the unraid template for unpoller (golift-unitifpoller) on my unraid server. 

I've completed the variables in the template for the unifi (UDM) controller and influxDB. Once started, this works fine and I can see metrics logged to the DB in the logs from the docker instance.  I am unable to access through any grafana instance however. 

I have installed the official grafana instance from the community apps on unraid and tried the unraid IP host address and receive a bad gateway error when I attempt to add the influxdb host ip as the new datasource. I suspect this is a docker networking issue but unsure how to resolve.  Any assistance on what I may be doing wrong?  Also, I thought this all in one docker for unpoller contained an instance of grafana but when this is running, no external port to host mappings exist exposing any grafana instance.  

thanks

**Comment by davidnewhall** [comment]
https://unpoller.com/docs/install/grafana

**Comment by davidnewhall** [comment]
The important part is `http://influxdb1:8086`. As long as your containers are on a custom bridge, you can use the container name as the host name (through docker DNS).

**Comment by Gtsupq** [comment]
Networking is currently set to Bridge.  So If I change this to custom (br0) , assign a IP for the unpoller docker, I can then use the address of http://influxdb1:8086 as the http url within the grafana docker?

also, I assume I would have to change the influxDB host url in the main unpoller docker as well to accomodate the networking change?

**Comment by davidnewhall** [comment]
I don't know what br0 is, but probably not, unless you made it.

https://docs.docker.com/network/bridge/

**Comment by davidnewhall** [comment]
> also, I assume I would have to change the influxDB host url in the main unpoller docker as well to accomodate the networking change?

Did you try _that_ hostname in Grafana?

**Comment by Gtsupq** [comment]
> 

Yes I did, and received the same error. I suspect its something I am doing wrong with the networking. 
in my unraid docker section, I have 2 dockers. (unifi-poller and grafana) 

The network in both of them was set to bridge and when I originally tried adding the http://influxdb1:8086/ as the http url in the grafana docker I receive the bad gateway message. When I set it to http://ip-of-myunraid-server:8086, I received a "cannot fetch" error... so thought I was progressing but maybe not.

in my unraid template, I have the following networking options outside of bridge. (host, none, or custom (br0) , where br0 refers to the main host NIC)

Ill have a look at the docker network bridge link you have set.

**Comment by davidnewhall** [comment]
Do unifi-poller logs indicate it's writing metrics to influx?

**Comment by Gtsupq** [comment]
yes, have just put back the unpoller container network back to bridge and in the logs I can see the following. (occurring every 30 secs) 

2022/03/20 22:18:08.949749 updateweb.go:213: [DEBUG] Found 1 site(s): default
2022/03/20 22:18:08.954989 logger.go:17: [INFO] UniFi Metrics Recorded. Site: 1, Client: 37, Gateways: 1, UAP: 4, USW: 4, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 136, Fields: 4431, Err: 0, Dur: 5ms

**Comment by davidnewhall** [comment]
Yup looks good. If this app can reach it, grafana should be able to as well.

**Comment by Gtsupq** [comment]
Just had a look in the Grafana docker logs and can see the following.

logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/11/query remote_addr=192.168.1.102 referer=http://192.168.1.200:3000/datasources/edit/e5c2iEPnk t=2022-03-20T22:26:47.23+1300 lvl=eror msg="Data proxy error" error="http: proxy error: dial tcp: lookup influxdb1 on 192.168.1.1:53: no such host"

Looks like a docker dns error. Ive not changed anything in that area so maybe there is some other step I have missed ?

**Comment by davidnewhall** [comment]
You should put your containers in a custom bridge. You make one with the `docker network create` command documented on the link above.

**Comment by platinummonkey** [comment]
closing as this looks resolved
