### ISSUE TITLE
Unable fetch data from unifi controller Unmarshalling Device Type: uap, usw

### ISSUE THREAD

**Issue by oqilkarimov** [unpoller/unpoller#411]

**Comment by davidnewhall** [comment]
_No description provided._ is where you write what's going on.

**Comment by oqilkarimov** [comment]
After launching unifi-poller gives an error in the logs Unmarshalling Device type: uap, usw as shown in the screenshot
![Screenshot 2022-05-19 11:43:14](https://user-images.githubusercontent.com/18390620/169229762-9501a497-7d6d-4919-aa26-443be658d3b4.png)
t

**Comment by davidnewhall** [comment]
That's not an error?

**Comment by oqilkarimov** [comment]
I'm sorry... it wasn't a problem with unpoller I had trouble with scrapping from unpoller. I has fixed already
