### ISSUE TITLE
Error logs

### ISSUE THREAD

**Issue by d2freak82** [unpoller/unpoller#413]
The metric output of Unifipoller/Grafana is great - love the data, I'm curious is there a way to sort through error logs coming from the Unifi Controller - for example a firewall error into an error where I can parse or search through the data to troubleshoot issues with Unifi.
I love the system, just want to make sure I'm getting all I can from it - any advice would be appreciated.

**Comment by davidnewhall** [comment]
That's not really what unpoller is about. it just collects metrics from the UniFi API. As for logs, you could stick those in Loki and build Grafana dashboards with them. That would look something like: enabling syslog server on your controller, send the logs to a syslog server that writes them to disk. On that same server you'd run promtail to send the log file(s) to Loki.

You could also run something like Notifiarr on that server to watch the logs for key words (regexes) and send them to a Discord channel for notifications.

https://grafana.com/oss/loki/
https://grafana.com/docs/loki/latest/
