### ISSUE TITLE
Add threat management worldmap for IDS/IPS logs

### ISSUE THREAD

**Issue by TehloWasTaken** [unpoller/unpoller#414]
Currrently in the Unifi Controller a Threat Map is seen which _should_ show you the locations of incoming threats. Sadly this doesn't work properly and only displays your own location, as it sees this as its 'source'.

Since UNPoller supports the addition of IDS/IPS data through Loki as a datasource, it would be neat to have a worldmap or some kind of visualization in a dashboard to see the actual sources of incoming attacks etc like below:

![image](https://user-images.githubusercontent.com/51698749/173793228-460df8c2-80bd-4479-bda1-874f1d625984.png)

**Comment by davidnewhall** [comment]
This isn't something I'm going to build, sorry. The data is there, so you're welcome to build it yourself.

**Comment by platinummonkey** [comment]
added additional info, but agreed, the viz in loki would probably need to be done elsewhere.
