### ISSUE TITLE
unpoller can't find my second site - configuration issue!

### ISSUE THREAD

**Issue by JPFreeski** [unpoller/unpoller#418]
Hey all. I'm stumped. Config is below.

I've tried every variation of:

- UP_UNIFI_DEFAULT_SITE_0=["all"]

Defining the second site for example:

- UP_UNIFI_DEFAULT_SITE_1=["default"]
- UP_UNIFI_DEFAULT_SITE_2=["xyzxyz"]

I just cannot get my second site discovered. Does anyone have any insight as to what my configuration is missing? I've tried environment variables and config file to no avail!

Thanks for your time!

   unifi_poller:
    image: golift/unifi-poller:latest
    container_name: unifi_poller
    restart: unless-stopped
    ports:
      - '9130:9130'
    environment:
      - UP_INFLUXDB_DISABLE=true
      - UP_POLLER_DEBUG=false
      - UP_UNIFI_DYNAMIC=false
      - UP_PROMETHEUS_HTTP_LISTEN=0.0.0.0:9130
      - UP_PROMETHEUS_NAMESPACE=unifipoller
      - UP_UNIFI_CONTROLLER_0_USER=xxxxxx
      - UP_UNIFI_CONTROLLER_0_PASS=xxxxxx
      - UP_UNIFI_CONTROLLER_0_SAVE_DPI=true
      - UP_UNIFI_CONTROLLER_0_URL=https://my.ip.addr:8443
      - UP_UNIFI_DEFAULT_SITE_0=["all"]

**Comment by davidnewhall** [comment]
If `all` does not show the site, then the user doesn't have access to see it.

**Comment by JPFreeski** [comment]
Thank you David!

If I had a dollar for ever permissions related issue I've had...
