### ISSUE TITLE
Grafana Dashboards linked in Docs reference unifipoller

### ISSUE THREAD

**Issue by rderewianko** [unpoller/unpoller#420]
Hi There,
When using Prometheus and grafana and referencing the templates listed in 
https://unpoller.com/docs/install/grafana

the metrics all reference unifipoller, however this has changed, and its now just unifi

E.g. 
unifipoller_device_info --> unifi_device_info

**Comment by dutts** [comment]
It now appears to have changed back to `unifipoller_`, but the dashboards now reference `unpoller_`
