### ISSUE TITLE
Open TCP connections

### ISSUE THREAD

**Issue by solipsist01** [unpoller/unpoller#421]
I'd like to be able to graph open connections on the USG3p

the cli command: conntrack -C gives me this output, but causes high cpu load when i pipe the output to graphite.
I couldn't find the metric in the prometheus browser.

Am i missing something obvious, or how would i go about to derive / calculate it from other metrics? or could it be added?

Thank you for this awesome project.

**Comment by davidnewhall** [comment]
That's probably not a metric exposed in the UniFi API. Doesn't sound familiar.

**Comment by solipsist01** [comment]
Bummer :)
