### ISSUE TITLE
unpoller container reboot loop caused by bug in 7.2.92 when hosting a UXG

### ISSUE THREAD

**Issue by atringle** [unpoller/unpoller#422]
There seems to be a bug stopping unpoller from uploading its info to influxdb starting with 7.2.92 specifically on a controller with a UXG. I know 

Ever since the controller was updated the grafana dashboard stopped showing any data (if i show data for a time range before the update it works).

When I enable debug on the unpoller I see the following
![image](https://user-images.githubusercontent.com/99745711/185203298-9adac77d-8d97-405b-ab3e-7593e89f6384.png)

Seems to be hitting a  invalid memory address or nil pointer dereference when processing batchUXG for influx.
Also once this occurs it restarts the docker container.

**Comment by davidnewhall** [comment]
Dang. Looks like they changed the API :(

**Comment by phil-ioniq** [comment]
Facing the same issue with unpoller v2.4.2, unifi version 7.2.95

**Comment by platinummonkey** [comment]
`v2.4.5` should include a fix
