### ISSUE TITLE
List Alarms or List Events will crash the UniFi Controller - Network Application

### ISSUE THREAD

**Issue by aledantas2k12** [unpoller/unpoller#426]
UniFi OS UDR 2.5.11

Not sure how to deal with this issue ( It's not unpoller but the awful coding from Ubiquiti)
The following will crash your controller:
https://UDR_IP_ADDRESS/proxy/network/api/s/default/rest/event
https://UDR_IP_ADDRESS/proxy/network/api/s/default/rest/alarm

Everything else is working.

**Comment by bondskin** [comment]
Hi, which UNA version are you running on the UDR?

**Comment by aledantas2k12** [comment]
UniFi OS (2.5.11) and Network (7.3.69 Early Access) - I also tried with
the Latest Official Firmware and it didn't work.

**Comment by aledantas2k12** [comment]
> Hi, which UNA version are you running on the UDR?

UniFi OS (2.5.11) and Network (7.3.69 Early Access) - I also tried with the Latest Official Firmware and it didn't work.

**Comment by platinummonkey** [comment]
still having issues with this? I haven't been able to reproduce

**Comment by platinummonkey** [comment]
closing as this seems to be a unifi software issue, not an unpoller issue

**Comment by davidnewhall** [comment]
Perhaps we can add a bool to not pull this endpoints? The app probably needs a few more tunable to reduce data into the time series.
