### ISSUE TITLE
Query Breakdown - Unifi-Poller Network Sites - InfluxDB

### ISSUE THREAD

**Issue by lslamp** [unpoller/unpoller#427]
I have installed grafana and using influxdb to monitor my unifi network.

The issue I have is, one of the graphs within the template that I have downloaded has no data. I have tried to look at it and see why but I cannot figure out what it is trying to extract. Below is the query.
The panel is trying to show Data Transfer by Category.

SELECT non_negative_derivative(sum(“rx_bytes”), 1s) AS “Bytes Rx”, non_negative_derivative(sum(“tx_bytes”), 1s) AS “Bytes Tx” FROM “sitedpi” WHERE (“site_name” =~ /^$site$/) AND $timeFilter GROUP BY time($__interval), “category”

Looking at the query I think that the issue is the table name “sitedpi”. If I run the command SHOW MEASUREMENTS; I do not see a table called “sitedpi”, but I have no clue what table to put in its place to get data to be presented to the graph.

Below is the results of the SHOW MEASUREMENTS;

Show Measurements;
name: measurements
name

clients
subsystems
uap
uap_radios
uap_vaps
usg
usg_networks
usg_wan_ports
usw
usw_ports

Any help would be much appreciated

Thanks
Lawrence

**Comment by lslamp** [comment]
@davidnewhall It is enabled.

![image](https://user-images.githubusercontent.com/6013759/196621087-781978d9-54d7-48ec-8b87-b8583fbc9ab1.png)

**Comment by dtatools** [comment]
You also need to enable it in the unpoller config file.

**Comment by davidnewhall** [comment]
You must also enable DPI collection in the unpoller config file. This data consumes a massive amount of space, so it's opt-in only.

**Comment by lslamp** [comment]
@davidnewhall 
Thanks a million for the great support.
It worked.

Lawrence
