### ISSUE TITLE
After Some Fiddling A Nice Dashboard for my UbiQuiti - USW-PRO-48-POE is running

### ISSUE THREAD

**Issue by jimthedj65** [unpoller/unpoller#429]
Thanks for all the hard work puting this together, took me a while to work through all the options and fix some of my own mistakes. All running and thanks.  I tried joining the discord group but it seems to have expired.

![Screenshot 2022-10-29 at 02 19 26](https://user-images.githubusercontent.com/46975497/198753057-1f5a5d54-5b57-4633-85b6-09b8efed8bcd.png)

**Comment by platinummonkey** [comment]
thanks!

**Comment by davidnewhall** [comment]
http://golift.io/discord is where you can find the devs.

Would you mind updating the discord link/icon in the readme, @platinummonkey ?

**Comment by platinummonkey** [comment]
fixed!
