### ISSUE TITLE
Install script broken + new version not available in apt repo

### ISSUE THREAD

**Issue by thetravellor** [unpoller/unpoller#434]
pi@dns:~ $ curl -s https://golift.io/repo.sh | sudo bash -s - unpoller
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
Get:1 https://download.docker.com/linux/raspbian bullseye InRelease [26.7 kB]
Hit:2 https://packages.grafana.com/oss/deb stable InRelease                                                                                                    
Hit:3 https://repos.influxdata.com/debian bullseye InRelease                                                                                                   
Hit:5 http://archive.raspberrypi.org/debian bullseye InRelease                                                                                                 
Get:6 https://pkgs.tailscale.com/stable/raspbian buster InRelease                      
Hit:7 http://raspbian.raspberrypi.org/raspbian bullseye InRelease                                                     
Hit:4 https://packagecloud.io/golift/pkgs/ubuntu focal InRelease
Fetched 32.2 kB in 2s (15.7 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package unpoller

pi@dns:~ $ curl -s https://golift.io/repo.sh | sudo bash -s - unifi-poller

Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
Get:1 https://download.docker.com/linux/raspbian bullseye InRelease [26.7 kB]
Hit:2 https://packages.grafana.com/oss/deb stable InRelease                                                                                                    
Hit:3 http://archive.raspberrypi.org/debian bullseye InRelease                                                                                                 
Hit:4 http://raspbian.raspberrypi.org/raspbian bullseye InRelease                                                                                              
Get:5 https://pkgs.tailscale.com/stable/raspbian buster InRelease                                                                               
Hit:7 https://repos.influxdata.com/debian bullseye InRelease        
Hit:6 https://packagecloud.io/golift/pkgs/ubuntu focal InRelease
Fetched 32.2 kB in 2s (16.7 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
unifi-poller is already the newest version (2.1.3-884).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by platinummonkey** [comment]
👋 im actively working on getting new builds and packages built. If you need something right now there are binaries already published in the releases GitHub section.

**Comment by platinummonkey** [comment]
this should be fixed now, can you confirm?

**Comment by thetravellor** [comment]
Does not appear to be, no:

pi@dns:~ $ curl -s https://golift.io/repo.sh | sudo bash -s - unpoller
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
Get:1 https://download.docker.com/linux/raspbian bullseye InRelease [26.7 kB]
Get:2 https://packages.grafana.com/oss/deb stable InRelease [5,812 B]                                                                                          
Hit:4 https://repos.influxdata.com/debian bullseye InRelease                                                                                                   
Get:5 https://pkgs.tailscale.com/stable/raspbian buster InRelease                         
Hit:6 http://archive.raspberrypi.org/debian bullseye InRelease      
Hit:7 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:3 https://packagecloud.io/golift/pkgs/ubuntu focal InRelease
Reading package lists... Done
E: Repository 'https://packages.grafana.com/oss/deb stable InRelease' changed its 'Origin' value from 'grafana stable' to '. stable'
E: Repository 'https://packages.grafana.com/oss/deb stable InRelease' changed its 'Label' value from 'grafana stable' to '. stable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package unpoller
pi@dns:~ $

**Comment by davidnewhall** [comment]
Need 386 and armhf too. Every release has 4 architectures.

**Comment by thetravellor** [comment]
awesome let us know when its fixed

**Comment by thetravellor** [comment]
Ok, so now two issues. This is very broken.

1. I have previously installed unifi-poller using apt.
2. Apt thinks unpoller and unifi-poller are different packages, so you cannot do apt-get upgrade unpoller 
3. Running apt-get install unpoller has severe errors.



`pi@dns:~ $ sudo apt-get upgrade unifi-poller
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
unifi-poller is already the newest version (2.1.3-884).
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@dns:~ $ sudo apt-get install unpoller
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  unpoller
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 4,436 kB of archives.
After this operation, 11.0 MB of additional disk space will be used.
Get:1 https://packagecloud.io/golift/pkgs/ubuntu focal/main armhf unpoller armhf 2.1.8+git [4,436 kB]
Fetched 4,436 kB in 3s (1,692 kB/s)   
Selecting previously unselected package unpoller.
(Reading database ... 191063 files and directories currently installed.)
Preparing to unpack .../unpoller_2.1.8+git_armhf.deb ...
Unpacking unpoller (2.1.8+git) ...
Setting up unpoller (2.1.8+git) ...
Invalid unit name "{{BINARY}}" escaped as "\x7b\x7bBINARY\x7d\x7d" (maybe you should use systemd-escape?).
Failed to enable unit: Unit file \x7b\x7bBINARY\x7d\x7d.service does not exist.
Invalid unit name "{{BINARY}}" escaped as "\x7b\x7bBINARY\x7d\x7d" (maybe you should use systemd-escape?).
Failed to restart \x7b\x7bBINARY\x7d\x7d.service: Unit \x7b\x7bBINARY\x7d\x7d.service not found.
dpkg: error processing package unpoller (--configure):
 installed unpoller package post-installation script subprocess returned error exit status 5
Errors were encountered while processing:
 unpoller
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Comment by platinummonkey** [comment]
Hmmm 🤔 I think I have a pi to test with. I was testing on an ubuntu arm64 docker container.

**Comment by davidnewhall** [comment]
Check out the `Makefile` actions for building the pre- and post- install scripts. They are templates and cannot be used as-is.

**Comment by davidnewhall** [comment]
Ideally the Makefile would work in GH actions, so folks can use it to build locally.

**Comment by platinummonkey** [comment]
🤔 i think I see it. Was already using a before-hook to generate the html files. Seems straightforward.

**Comment by platinummonkey** [comment]
this should be fixed now with 2.1.9

**Comment by thetravellor** [comment]
Hi, no, its not.

pi@dns:~ $ sudo apt-get install unpoller
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  unpoller
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 4,469 kB of archives.
After this operation, 11.0 MB of additional disk space will be used.
Get:1 https://packagecloud.io/golift/pkgs/ubuntu focal/main armhf unpoller armhf 2.1.9+git [4,469 kB]
Fetched 4,469 kB in 3s (1,746 kB/s)   
Selecting previously unselected package unpoller.
(Reading database ... 191064 files and directories currently installed.)
Preparing to unpack .../unpoller_2.1.9+git_armhf.deb ...
Unpacking unpoller (2.1.9+git) ...
Setting up unpoller (2.1.9+git) ...
Failed to enable unit: Unit file unpoller.service does not exist.
Failed to restart unpoller.service: Unit unpoller.service not found.
dpkg: error processing package unpoller (--configure):
 installed unpoller package post-installation script subprocess returned error exit status 5
Processing triggers for man-db (2.9.4-2) ...
Errors were encountered while processing:
 unpoller
E: Sub-process /usr/bin/dpkg returned an error code (1)

There is also still no upgrade path from unifi-poller to unpoller.

**Comment by thetravellor** [comment]
pi@dns:~ $ sudo apt-get remove unpoller
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  unpoller
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 11.0 MB disk space will be freed.
Do you want to continue? [Y/n] 
(Reading database ... 191092 files and directories currently installed.)
Removing unpoller (2.1.9+git) ...
Failed to stop unpoller.service: Unit unpoller.service not loaded.
Failed to disable unit: Unit file unpoller.service does not exist.
dpkg: error processing package unpoller (--remove):
 installed unpoller package pre-removal script subprocess returned error exit status 1
dpkg: too many errors, stopping
Failed to enable unit: Unit file unpoller.service does not exist.
Failed to restart unpoller.service: Unit unpoller.service not found.
dpkg: error while cleaning up:
 installed unpoller package post-installation script subprocess returned error exit status 5
Errors were encountered while processing:
 unpoller
Processing was halted because there were too many errors.
E: Sub-process /usr/bin/dpkg returned an error code (1)
pi@dns:~ $ which unifi-poller
/usr/bin/unifi-poller

**Comment by thetravellor** [comment]
pi@dns:~ $ ls -l /var/lib/dpkg/info | grep unpoller
-rw-r--r-- 1 root root     407 Nov 15 09:04 unpoller.conffiles
-rw-r--r-- 1 root root     960 Nov 15 10:04 unpoller.list
-rw-r--r-- 1 root root    1061 Nov 15 09:04 unpoller.md5sums
-rwxr-xr-x 1 root root    1003 Nov 15 09:04 unpoller.postinst
-rwxr-xr-x 1 root root     447 Nov 15 09:04 unpoller.prerm

sudo rm /var/lib/dpkg/info/unpoller*

**Comment by thetravellor** [comment]
If I move to docker, can I simply use the unifi-poller config files to a docker config directory?

**Comment by platinummonkey** [comment]
yes you can, It looks like now the service is missing from the deb package 🤔

**Comment by platinummonkey** [comment]
should be fixed again ^ turns out the install path was incorrect 🤦

**Comment by bondskin** [comment]
on my Pi I just tried to install (took me a while to realise that using apt it does not work):
"unifi-poller is already the newest version (2.1.3-884)."

using "sudo apt-get install unpoller" got it started:

Preparing to unpack .../unpoller_2.3.0+git_armhf.deb ...
Unpacking unpoller (2.3.0+git) ...
Setting up unpoller (2.3.0+git) ...
Failed to enable unit: Unit file unpoller.service does not exist.
Failed to restart unpoller.service: Unit unpoller.service not found.
dpkg: error processing package unpoller (--configure):
 installed unpoller package post-installation script subprocess returned error exit status 5
Processing triggers for man-db (2.8.5-2) ...
Errors were encountered while processing:
 unpoller
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by platinummonkey** [comment]
should be fixed in 2.3.1 now from #450

**Comment by bondskin** [comment]
Setting up unpoller (2.3.1+git) ...
 Post Install of an clean install
/var/lib/dpkg/info/unpoller.postinst: 52: /var/lib/dpkg/info/unpoller.postinst: []: not found

pi@raspberrypi:~ $ unpoller
2022/12/05 09:28:24 [INFO] Loading Configuration File: /etc/unifi-poller/up.conf
2022/12/05 09:28:24 [INFO] UniFi Poller v Starting Up! PID: 4847
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc pc=0x43abe4]

goroutine 20 [running]:
github.com/unpoller/unpoller/pkg/datadogunifi.(*DatadogUnifi).Run(0x211e1e0, {0x72e3c4, 0x200e028})
        /home/runner/work/unpoller/unpoller/pkg/datadogunifi/datadog.go:193 +0x24
github.com/unpoller/unpoller/pkg/poller.(*UnifiPoller).runOutputMethods.func1(0x212a2d0)
        /home/runner/work/unpoller/unpoller/pkg/poller/outputs.go:85 +0x38
created by github.com/unpoller/unpoller/pkg/poller.(*UnifiPoller).runOutputMethods
        /home/runner/work/unpoller/unpoller/pkg/poller/outputs.go:84 +0xac

**Comment by bmatheny** [comment]
@bondskin I'm seeing the same crash. @platinummonkey I ping'd you on the PR that introduced it (or at least that showed up from the bisect).

**Comment by bmatheny** [comment]
Huh. Interestingly; I created an up.conf script by hand (because of #443), disabled the datadog plugin, and updated to v2.3.1. I'm not seeing this crash with that combination. Just sharing in case it's helpful for whoever tracks this down.

**Comment by platinummonkey** [comment]
2.4.0 seems to work for me now (releasing currently). The bug was a nil pointer for the log interface which expected the plugin to have a non-nil collector assigned

**Comment by qbatten** [comment]
Hm, getting that same up.conf error with 2.4.0. I'm using Docker with the example docker-compose file. Any thoughts?
(Also this project is *awesome*! Thanks for your work on it!)

**Comment by platinummonkey** [comment]
2.4.1 also released with a default config. Closing this as I believe this is finally fixed. Sorry for the trouble here. Reopen if this is not the case 🙇
