### ISSUE TITLE
updated version does not show in docker hub

### ISSUE THREAD

**Issue by fate8383** [unpoller/unpoller#435]
I am not sure if this is something me problem but I done see any update or image changed in the docker hub after new version. last update was 2 years ago in docker hub, how do I get this new version?

**Comment by platinummonkey** [comment]
👋 im actively working on getting this builds to work again.

**Comment by fate8383** [comment]
well it is working for me with whatever is there from 2 years back :)

**Comment by davidnewhall** [comment]
The image on dockerhub will be deprecated in favor of a new name. It's unlikely anything will ever push into `unifi-poller` again.

**Comment by platinummonkey** [comment]
`ghcr.io/unpoller/unpoller` is the registry location now use the tag `latest-${arch}` 

arch options are `arm64` `arm64v8` and `armv7` additional each tag has a similar tagged release

**Comment by fate8383** [comment]
great, however I have been using the docker compose example in this rapository which still exist, and stacked all garafana and influx with it, not sure how to do from different registry the unpoller image. also I see golift is completely cleared on docker hub so will there be a documentation update for the whole new registry and similar stack example?

**Comment by fate8383** [comment]
https://hub.docker.com/r/platinummonkey/unpoller/tags this could work if it will be updated with the new version?

**Comment by platinummonkey** [comment]
yeah I need to update a bunch of things 😄 and helpers.

**Comment by davidnewhall** [comment]
It's quite a challenge migrating an entire build system you didn't write. Thanks so much @platinummonkey!

**Comment by platinummonkey** [comment]
> https://hub.docker.com/r/platinummonkey/unpoller/tags this could work if it will be updated with the new version?

https://github.com/unpoller/unpoller/releases will contain the tags that should also be pushed as well until I update these docs

**Comment by fate8383** [comment]
ghcr.io/unpoller/unpoller:latest vs golift/unifi-poller:latest how do I use the new image in the docker compose? I am confused :)

**Comment by platinummonkey** [comment]
It will be ghcr.io/unpoller/unpoller

**Comment by mje-nz** [comment]
Is the new container set to private? I get "denied" when I try to pull it. I can pull GHCR images from other projects.

**Comment by davidnewhall** [comment]
> Is the new container set to private? I get "denied" when I try to pull it. I can pull GHCR images from other projects.

it was. it's not now.
