### ISSUE TITLE
InfluxDB failed invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by jsrichie** [unpoller/unpoller#468]
2022/12/17 17:17:58 [ERROR] metric fetch for InfluxDB failed: re-authenticating to http://10.0.0.1: unifi controller: unable to get server version: invalid character '<' looking for beginning of value

Fresh Install and getting this error
Network 7.2.95

**Comment by platinummonkey** [comment]
This looks like something is incorrect and it’s spitting back html at you

**Comment by davidnewhall** [comment]
Your controller is not listening on an http port. Fix that.

**Comment by jsrichie** [comment]
Was able to sort this out
