### ISSUE TITLE
How to install latest version

### ISSUE THREAD

**Issue by KOTIJim** [unpoller/unpoller#477]
Hello 

Forgive my ignorance, but I am trying to use the latest and greatest version (2.4.6) but the script to install in Linux (curl -s https://golift.io/repo.sh | sudo bash -s - unifi-poller) Installs version 2.1.3. 
I have tried cloning the repo and building myself but again I'm having trouble with that, again probably due to ignorance on my behalf:

`koti@dash:~/unpoller$ sudo make
git clean -xdf
Removing .metadata.make
docker images -f "dangling=true" -q | xargs docker rmi
"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images
make: *** [Makefile:69: clean] Error 123
`

Any help on installing the latest release please.

Regards

Jim

**Comment by davidnewhall** [comment]
The name changed. Install the new package.
```
sudo apt install unpoller
```

**Comment by KOTIJim** [comment]
Thanks :)
