### ISSUE TITLE
Grafana, InfluxDB, Unpoller and DPI Dashboard

### ISSUE THREAD

**Issue by TheLucidOne** [unpoller/unpoller#492]
Under InfluxDB 1.8 and 1.8.4 (tried both), for the DPI dashboard in Grafana (tried multiple versions of 9.3, 9.2, 8.x), I'm getting the following error (also on Network Sites dashboard on the 'data transfer by category' panel).

`InfluxDB Error: unsupported spread iterator type: *query.stringInterruptIterator`

This was working until a week ago and I've even rebuilt several ways, from the ground up.  Not sure what I may have misconfigured at this point.  Anyone else having this issue?

**Comment by platinummonkey** [comment]
https://github.com/unpoller/dashboards/issues/20#issuecomment-1364716049

**Comment by platinummonkey** [comment]
fixed in v2.7.9
