### ISSUE TITLE
Documentation, docker, InfluxDB issues all around

### ISSUE THREAD

**Issue by jknyght9** [unpoller/unpoller#495]
I had high hopes, but I've wasted an entire day trying to figure this out! This entire project revolves around InfluxDB, Grafana, and your poller technology; however, your documentation is subpar at best. Your docker-compose documentation refers to Influx 2.5; however, you've stated the project only works with Influx 1.8.X. Why would you post something that does not work? Furthermore, pulled all Influx versions down to 1.8; however, I continue to have issues getting a dashboard up. I seriously hope you guys do some QA on your project soon.

**Comment by davidnewhall** [comment]
hahahaha

**Comment by jknyght9** [comment]
Wow, that's professional

**Comment by davidnewhall** [comment]
Good luck.

**Comment by jknyght9** [comment]
Perhaps its QA that needs to be performed on the admins of this project

**Comment by davidnewhall** [comment]
Thanks for your highly encouraging and extremely detailed feedback. Definitely keeps us motivated.
