### ISSUE TITLE
Operation Aborted

### ISSUE THREAD

**Issue by justinmstark** [unpoller/unpoller#499]
Hi,

Going through all the steps with the installation and reached:

curl -s https://golift.io/repo.sh | bash -s - unifi-poller 
(documentation still shows unpoller)
[https://unpoller.com/docs/install/linux/]

and the systems shows the unifi-poller install (v2.1.30884) but... 
when it comes to "Is this OK [y/N]" thje operation aborts.

Am I missing something really simple?

Thanks.

**Comment by davidnewhall** [comment]
`sudo apt install unpoller` will get you there now.

**Comment by justinmstark** [comment]
I like the idea but...

curl -s https://golift.io/repo.sh | bash -s -unpoller

This says, no match for **unpoller**

**Comment by davidnewhall** [comment]
How about pasting the entire thing, so we can infer your OS from the output?

**Comment by justinmstark** [comment]
Sorry David...

[root@homeassist ~]# curl -s https://golift.io/repo.sh | bash -s - unpoller
/usr/bin/which: no apt in (/root/.local/bin:/root/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin)
/usr/bin/which: no brew in (/root/.local/bin:/root/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin)
Updating Subscription Management repositories.
Last metadata expiration check: 0:00:02 ago on Fri 06 Jan 2023 11:19:10.
No match for argument: unpoller
Error: Unable to find a match: unpoller

**Comment by davidnewhall** [comment]
Can you verify that the repo file was created? Find it at `/etc/yum.repos.d/golift.repo`

And try to install the package manually with:
```
sudo yum install unpoller
```

**Comment by justinmstark** [comment]
Thanks...

[root@homeassist yum.repos.d]# more golift.repo
[golift]
name=golift
baseurl=https://packagecloud.io/golift/pkgs/el/6/$basearch
repo_gpgcheck=1
gpgcheck=1
enabled=1
gpgkey=https://packagecloud.io/golift/pkgs/gpgkey
       https://packagecloud.io/golift/pkgs/gpgkey/golift-pkgs-7F7791485BF8996D.pub.gpg
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300

but...
[root@homeassist yum.repos.d]# sudo yum install unpoller
Updating Subscription Management repositories.
Last metadata expiration check: 0:03:51 ago on Fri 06 Jan 2023 11:19:10.
No match for argument: unpoller
Error: Unable to find a match: unpoller

Really appreciate assistance too.

**Comment by davidnewhall** [comment]
I found the problem. Give me a few minutes to fix it.

**Comment by justinmstark** [comment]
Thanks.  You are a legend...

**Comment by davidnewhall** [comment]
Try this:
```
sudo  yum -q makecache -y --disablerepo='*' --enablerepo='golift'
sudo yum install unpoller
```

**Comment by justinmstark** [comment]
so close...

[root@homeassist yum.repos.d]# sudo  yum -q makecache -y --disablerepo='*' --enablerepo='golift'
[root@homeassist yum.repos.d]# sudo yum install unpoller
Updating Subscription Management repositories.
Last metadata expiration check: 0:00:10 ago on Fri 06 Jan 2023 11:30:31.
Dependencies resolved.
=============================================================================================================================================================
 Package                              Architecture                       Version                                    Repository                          Size
=============================================================================================================================================================
Installing:
 unpoller                             x86_64                             2.7.5+git-1                                golift                             5.0 M

Transaction Summary
=============================================================================================================================================================
Install  1 Package

Total download size: 5.0 M
Installed size: 13 M
Is this ok [y/N]: y
Downloading Packages:
unpoller-2.7.5+git-1.x86_64.rpm                                                                                              1.8 MB/s | 5.0 MB     00:02
-------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                        1.8 MB/s | 5.0 MB     00:02
Package unpoller-2.7.5+git-1.x86_64.rpm is not signed
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'yum clean packages'.
Error: GPG check FAILED

**Comment by davidnewhall** [comment]
Okay, give this a whirl..
```
sudo yum clean all
sudo yum -q makecache -y --disablerepo='*' --enablerepo='golift'
sudo yum install unpoller
```

**Comment by davidnewhall** [comment]
First time around, I put the packages into the repository. They were uploaded to the wrong one. Second time around, I signed the packages. #500 fixes both of these problems. Thanks for working through that with me!
