### ISSUE TITLE
Discord Invite Shows as Invalid

### ISSUE THREAD

**Issue by koensayr** [unpoller/unpoller#505]
Was looking to get some help and the Discord invite link located:

https://unpoller.com/docs/help/

Takes you to discord but shows the invite link as invalid

<img width="615" alt="Screenshot 2023-01-07 at 4 36 54 PM" src="https://user-images.githubusercontent.com/4297325/211175385-06c60551-7085-44d2-9386-f3814d5c3ec2.png">

**Comment by davidnewhall** [comment]
https://golift.io/discord
