### ISSUE TITLE
Support InfluxDB v2 Auth (ie: InfluxDB Cloud)

### ISSUE THREAD

**Issue by koensayr** [unpoller/unpoller#506]
It would be amazing if Unpoller support token based authorization for InfluxDB Cloud. According to the documentation for the InfluxDB Cloud (https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/v1/auth/create/) v1 username and password authorization mechanisms isn't support on InfluxDB Cloud

This represents a feature request to update the authorization mechanism to support token based authorization.

**Comment by platinummonkey** [comment]
Already should work with the auth_token option for influx 2+

**Comment by koensayr** [comment]
Thanks, I'll have to take a look at the code then, since it appears its not documented.
