### ISSUE TITLE
Client DPI field type conflict

### ISSUE THREAD

**Issue by benchristian88** [unpoller/unpoller#512]
Just upgraded to 2.7.10 and getting the following error, with no client dpi stats being recorded.

2023/01/14 06:32:33 [ERROR] influxdb.Write(points): {"error":"partial write: field type conflict: input field \"rx_bytes\" on measurement \"clientdpi\" is type float, already exists as type string dropped=2965"}

Great tool, thanks, love my unifi graphs.

**Comment by davidnewhall** [comment]
The metric type was changed (fixed) which means you have to clear all metrics with that type. Sucks, but this happens once in a while.

`DELETE FROM "clientdpi"`

**Comment by benchristian88** [comment]
thanks. I use the home assistant add-on, and i am not super familiar with influx so will see what i can find about how to delete the data. thanks
