### ISSUE TITLE
Reducing cardinality

### ISSUE THREAD

**Issue by michaelarchi** [unpoller/unpoller#515]
This is more a question than an issue. 

I'd like to keep cardinality in my influxDB as low as possible, to reduce RAM usage and thus power usage. 
The following is a view on the tags with the highest cardinalities, as per https://docs.influxdata.com/influxdb/cloud/write-data/best-practices/resolve-high-cardinality/#count-unique-tag-values (note that I removed some values at the end). 

table_result | _value | tag
-- | -- | --
0 | 172 | _field
1 | 7 | _measurement
2 | 0 | _start
3 | 0 | _stop
4 | 12 | ap_mac
5 | 10 | ap_name
6 | 84 | bssid
7 | 7 | channel
8 | 1 | desc
9 | 15 | device_name
10 | 4 | essid
11 | 1 | flowctrl_rx
12 | 1 | flowctrl_tx
13 | 1 | has_sfp
14 | 4 | id
15 | 1 | is_guest
16 | 2 | is_wired
17 | 76| mac
18 | 3 | media
19 | 4 | model
20 | 125| name
21 | 15 | oui
22 | 2 | poe_enable
23 | 1 | poe_mode

The 'mac' and 'name' tags have a large contribution to cardinality, and I do not necessarily need them in my dashboards (note that the names of the APs are useful, it's those of the clients that I don't need - but I'm ok with just getting rid of all names if that's a possibility).

As both name and mac is a key, I cannot simply delete them once they are ingested in influxdb (as they are part of influxdb's index). Instead I need to delete the complete measurement. 

Is there a way to filter out certain keys or any other way to simply reduce cardinality?

**Comment by davidnewhall** [comment]
Tags and field filters sounds like a reasonable idea. When I wrote this code I knew nothing about influxdb, but I've learned a lot since. This code has improved a bit, but still has a ways to go. Thanks for your insight and investigation here, it's very helpful!

**Comment by michaelarchi** [comment]
Any quick workaround you see to stop ingesting client's data?

**Comment by platinummonkey** [comment]
Some cardinality might can be reduced by using “drop_pii = true” in the config. This should drop ip and MAC addresses for example to empty strings

**Comment by michaelarchi** [comment]
Great idea, I did not know that flag existed. I'm trying it out.
