### ISSUE TITLE
Error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by emarcelcom** [unpoller/unpoller#519]
This error just started popping up on 15 Feb 2023. 

`
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x91d2d4]
`

Here is the log from the container:
`2023/02/16 14:43:30 [INFO] Loading Configuration File: /etc/unpoller/up.conf
2023/02/16 14:43:30.929918 start.go:98: [DEBUG] Debug Logging Enabled
2023/02/16 14:43:30.929995 start.go:101: [INFO] UniFi Poller v2.7.11 Starting Up! PID: 1
2023/02/16 14:43:30.930021 inputs.go:72: [DEBUG] initializing 1 inputs
2023/02/16 14:43:30.930059 inputs.go:78: [DEBUG] inititalizing input... unifi
2023/02/16 14:43:30.930110 updateweb.go:219: [DEBUG] Requesting https://10.0.0.1:443/ to determine API paths
2023/02/16 14:43:31.118197 updateweb.go:219: [DEBUG] Using NEW UniFi controller API paths for https://10.0.0.1:443/
2023/02/16 14:43:31.118286 updateweb.go:219: [DEBUG] Requesting https://10.0.0.1:443/api/auth/login, with params: true, cookies: 0
2023/02/16 14:43:31.639539 updateweb.go:219: [DEBUG] Requested https://10.0.0.1:443/api/auth/login: elapsed 521ms, returned 4529 bytes
2023/02/16 14:43:31.639613 updateweb.go:219: [DEBUG] Requesting https://10.0.0.1:443/proxy/network/status, with params: false, cookies: 1
2023/02/16 14:43:31.659902 updateweb.go:219: [DEBUG] Requested https://10.0.0.1:443/proxy/network/status: elapsed 20ms, returned 76 bytes
2023/02/16 14:43:31.660130 updateweb.go:219: [DEBUG] Authenticated with controller successfully, https://10.0.0.1:443
2023/02/16 14:43:31.660148 updateweb.go:219: [DEBUG] Checking Controller Sites List
2023/02/16 14:43:31.660204 updateweb.go:219: [DEBUG] Requesting https://10.0.0.1:443/proxy/network/api/stat/sites, with params: false, cookies: 1
2023/02/16 14:43:31.786708 updateweb.go:219: [DEBUG] Requested https://10.0.0.1:443/proxy/network/api/stat/sites: elapsed 127ms, returned 913 bytes
2023/02/16 14:43:31.787273 updateweb.go:219: [DEBUG] Found 1 site(s): default
2023/02/16 14:43:31.787318 updateweb.go:195: [INFO] Found 1 site(s) on controller https://10.0.0.1:443: default (Default)
2023/02/16 14:43:31.787337 updateweb.go:195: [INFO] Configured UniFi Controller 1 of 1:
2023/02/16 14:43:31.787350 updateweb.go:195: [INFO]    => URL: https://10.0.0.1:443 (verify SSL: false)
2023/02/16 14:43:31.787361 updateweb.go:195: [INFO]    => Version:  (3a1XXXf9-XXXX-XXXX-a5a5-726XXXXXe2a)
2023/02/16 14:43:31.787371 updateweb.go:195: [INFO]    => Username: unifipoller (has password: true)
2023/02/16 14:43:31.787387 updateweb.go:195: [INFO]    => Hash PII false / Drop PII false / Poll Sites: all
2023/02/16 14:43:31.787405 updateweb.go:195: [INFO]    => Save Sites true / Save DPI false (metrics)
2023/02/16 14:43:31.787416 updateweb.go:195: [INFO]    => Save Events false / Save IDS false (logs)
2023/02/16 14:43:31.787426 updateweb.go:195: [INFO]    => Save Alarms false / Anomalies false (logs)
2023/02/16 14:43:31.787435 updateweb.go:195: [INFO]    => Save Rogue APs: false
2023/02/16 14:43:31.787449 inputs.go:84: [DEBUG] input successfully initialized ... unifi
2023/02/16 14:43:31.787477 inputs.go:90: [DEBUG] collecting input errors...
2023/02/16 14:43:31.787489 inputs.go:107: [DEBUG] returning error: %!w(<nil>)
2023/02/16 14:43:31.787497 start.go:107: [DEBUG] staring outputs
2023/02/16 14:43:31.787509 outputs.go:96: [DEBUG] output plugin disabled for WebServer
2023/02/16 14:43:31.787518 outputs.go:96: [DEBUG] output plugin disabled for datadog
2023/02/16 14:43:31.787527 outputs.go:91: [DEBUG] output plugin enabled, starting run loop for influxdb
2023/02/16 14:43:31.787543 outputs.go:96: [DEBUG] output plugin disabled for loki
2023/02/16 14:43:31.787553 outputs.go:96: [DEBUG] output plugin disabled for prometheus
2023/02/16 14:43:31.787627 logger.go:18: [INFO] InfluxDB enabled
2023/02/16 14:43:31.787742 logger.go:18: [INFO] Poller->InfluxDB started, version: 1, interval: 30s, dp: false, db: telegraf-db, url: http://influxdb:8086, bucket: , org:
2023/02/16 14:44:01.816212 updateweb.go:219: [DEBUG] Requesting https://10.0.0.1:443/proxy/network/api/stat/sites, with params: false, cookies: 1
2023/02/16 14:44:01.935846 updateweb.go:219: [DEBUG] Requested https://10.0.0.1:443/proxy/network/api/stat/sites: elapsed 120ms, returned 913 bytes
2023/02/16 14:44:01.936165 updateweb.go:219: [DEBUG] Found 1 site(s): default
2023/02/16 14:44:01.936195 updateweb.go:219: [DEBUG] Polling Controller, retreiving UniFi Clients, site Default (default)
2023/02/16 14:44:01.936255 updateweb.go:219: [DEBUG] Requesting https://10.0.0.1:443/proxy/network/api/s/default/stat/sta, with params: false, cookies: 1
2023/02/16 14:44:02.097759 updateweb.go:219: [DEBUG] Requested https://10.0.0.1:443/proxy/network/api/s/default/stat/sta: elapsed 162ms, returned 36555 bytes
2023/02/16 14:44:02.103759 updateweb.go:219: [DEBUG] Requesting https://10.0.0.1:443/proxy/network/api/s/default/stat/device, with params: false, cookies: 1
2023/02/16 14:44:02.196487 updateweb.go:219: [DEBUG] Requested https://10.0.0.1:443/proxy/network/api/s/default/stat/device: elapsed 93ms, returned 89986 bytes
2023/02/16 14:44:02.199625 updateweb.go:219: [DEBUG] Unmarshalling Device Type: usw, Model: USMINI, site Default (default)
2023/02/16 14:44:02.201807 updateweb.go:219: [DEBUG] Unmarshalling Device Type: usw, Model: USMINI, site Default (default)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x91d2d4]`

**Comment by platinummonkey** [comment]
can you dump what it's collecting? `unpoller -c /etc/unpoller/up.conf -d -j`

**Comment by emarcelcom** [comment]
How to run this command? I run it with docker-compose ...

**Comment by platinummonkey** [comment]
`docker run docker pull ghcr.io/unpoller/unpoller:latest -d -j -v /path/to/your/up.conf:/etc/unpoller/up.conf` for docker users

**Comment by emarcelcom** [comment]
I run poller this way:

`  unpoller:
    container_name: unifi-poller
    restart: unless-stopped
    #image: golift/unifi-poller:latest
    image: ghcr.io/unpoller/unpoller:latest
    environment:
      - UP_PROMETHEUS_DISABLE=true
      - UP_INFLUXDB_DB=${INFLUXDB_DB}
      - UP_INFLUXDB_USER=${INFLUXDB_ADMIN_USER}
      - UP_INFLUXDB_PASS=${INFLUXDB_ADMIN_PASSWORD}
      - UP_INFLUXDB_URL=http://influxdb:8086
      - UP_UNIFI_DEFAULT_USER=${UNIFI_USER}
      - UP_UNIFI_DEFAULT_PASS=${UNIFI_PASS}
      - UP_UNIFI_DEFAULT_URL=${UNIFI_URL}
      - UP_POLLER_DEBUG=${POLLER_DEBUG}
      - UP_UNIFI_DEFAULT_SAVE_DPI=${POLLER_SAVE_DPI}`

**Comment by emarcelcom** [comment]
Does it change a lot if I say that I'm still running Influxdb v1.8?

**Comment by platinummonkey** [comment]
so nil pointer is going to be because of some expected data source is not present and the plugin is attempting to access it to write out some data. the command I gave will help print out what data you have (feel free to munch some macs/ips if you need to with some filler "REDACTED", mostly I'm looking for the structure and can compare what might have changed potentially with a firmware upgrade.

**Comment by emarcelcom** [comment]
The point is that I can't run `unpoller -c /etc/unpoller/up.conf -d -j` because the container is crashing ...

**Comment by platinummonkey** [comment]
it crashes with this command? `docker run ghcr.io/unpoller/unpoller:latest -d -j -v /path/to/your/up.conf:/etc/unpoller/up.conf` specifically?

**Comment by emarcelcom** [comment]
Looks like my up.conf file is not being read:

> # ls -la
total 20
drwxr-xr-x 2 root root  4096 Feb 16 19:36 .
drwxr-xr-x 5 root root  4096 Feb 16 19:36 ..
-rw-r--r-- 1 root root 10255 Feb 16 19:31 up.conf
root@docker:/opt/unpoller# docker run ghcr.io/unpoller/unpoller:latest -d -j -v /opt/unpoller/up.conf:/etc/unpoller/up.conf
2023/02/16 18:37:14 [INFO] Checking inputs...
2023/02/16 18:37:14 [INFO] 	(1/1) Checking input unifi...
2023/02/16 18:37:14 [ERROR] 		 unifi Failed: unifi controller: making request: Get "https://127.0.0.1:8443/": dial tcp 127.0.0.1:8443: connect: connection refused
2023/02/16 18:37:14 [INFO] Checking outputs...
2023/02/16 18:37:14 [INFO] 	(1/5) Checking output WebServer...
2023/02/16 18:37:14 [INFO] 		 WebServer is OK
2023/02/16 18:37:14 [INFO] 	(2/5) Checking output datadog...
2023/02/16 18:37:14 [INFO] 		 datadog is OK
2023/02/16 18:37:14 [INFO] 	(3/5) Checking output influxdb...
2023/02/16 18:37:14 [ERROR] 		 influxdb Failed: unsuccessful ping to influxdb1
2023/02/16 18:37:14 [INFO] 	(4/5) Checking output loki...
2023/02/16 18:37:14 [INFO] 		 loki is OK
2023/02/16 18:37:14 [INFO] 	(5/5) Checking output prometheus...
2023/02/16 18:37:14 [INFO] 		 prometheus is OK
2023/02/16 18:37:14 [ERROR] No all checks passed, please fix the logged issues.
root@docker:/opt/unpoller#

**Comment by emarcelcom** [comment]
root@docker:/opt/unpoller# docker run ghcr.io/unpoller/unpoller:latest unpoller -d -j -c /etc/unpoller/up.conf -v /opt/unpoller/up.conf:/etc/unpoller/up.conf
unpoller, version 2.7.11 (branch: HEAD (88ec77227ca54881868c5229a25455faadf41b70), revision: 1)
  build user:       goreleaser
  build date:       2023-01-23T23:38:04Z
  go version:       go1.19.5
  platform:         linux/amd64
  started:          2023-02-16 18:50:52.85218162 +0000 UTC m=+0.000450496
root@docker:/opt/unpoller#

**Comment by platinummonkey** [comment]
okay that works, copy-paste both of the results from here in a gist perhaps.

the devices data
`docker run ghcr.io/unpoller/unpoller:latest unpoller -j devices -c /etc/unpoller/up.conf -v /opt/unpoller/up.conf:/etc/unpoller/up.conf`

and the clients data
`docker run ghcr.io/unpoller/unpoller:latest unpoller -j clients -c /etc/unpoller/up.conf -v /opt/unpoller/up.conf:/etc/unpoller/up.conf`

**Comment by emarcelcom** [comment]
It seems that the UNIFI device has not been collecting metrics as expected, which has caused unpoller service to fail. 
 After restarting the UNIFI Network App all metrics are fetched by the unpuller again! It's just the way how unpoller handles errors. Many thanks for your assistance.
