### ISSUE TITLE
webserver directory stat error / not found

### ISSUE THREAD

**Issue by akalderon** [unpoller/unpoller#521]
stat error for /usr/lib/unpoller/web as well as /usr/lib/unifi-poller/web on docker image
1) where are the web server files located within the image? 
2) how does one attach or connect to console on the docker image - all usual methods to run a shell session (sh or bash) seem to fail?

**Comment by platinummonkey** [comment]
> stat error for /usr/lib/unpoller/web as well as /usr/lib/unifi-poller/web on docker image

Can you share how you're invoking docker here?

> 1. where are the web server files located within the image?
> 2. how does one attach or connect to console on the docker image - all usual methods to run a shell session (sh or bash) seem to fail?

**Comment by akalderon** [comment]
The below works fine without the UP_WEBSERVER_ENABLE=true variable.  Once added, I am getting both confirmation that webserver is enabled as well as stat error in the logs indicating that the web server files are not found

unifi-poller:
    restart: unless-stopped
    container_name: unifi-poller
    image: ghcr.io/unpoller/unpoller
    depends_on:
      - influxdb
      - chronograf
    environment:
      - UP_INFLUXDB_DB=unifipoller
      - UP_INFLUXDB_USER=<obfuscated>
      - UP_INFLUXDB_PASS=<obfuscated>
      - UP_INFLUXDB_URL=http://influxdb:8086
      - UP_UNIFI_DEFAULT_USER=<obfuscated>
      - UP_UNIFI_DEFAULT_PASS=<obfuscated>
      - UP_UNIFI_DEFAULT_URL=<obfuscated>
      - UP_POLLER_DEBUG=false
      - UP_UNIFI_DEFAULT_SAVE_DPI=false
      - UP_WEBSERVER_ENABLE=true
    links:
      - influxdb

**Comment by WillGunn** [comment]
Using the golift docker image on unraid, this seems to be back.  I've tried both `/usr/local/lib/unpoller/web` and `/usr/lib/unpoller/web`
