### ISSUE TITLE
Docker Compose install method examples do not work on Raspberry Pi

### ISSUE THREAD

**Issue by vidia** [unpoller/unpoller#533]
I just went through the process of installing unpoller on a Raspberry Pi and ran into an issue with the [docker compose instructions](https://unpoller.com/docs/install/dockercompose). These instructions default influxdb to version 2.5 but according to [this](https://github.com/influxdata/influxdata-docker/issues/460) bug in influx, Influx v2 does not support 32-bit ARM, and according to the dependencies page of unpoller, Influx v2+ is not recommended. 

Switching InfluxDB to version 1.8 resolves the issue and allows me to launch as expected. 

Relevant error (infortunately a bit garbled by portainer, but I was able to associate it with influx, despite grafana being listed last): 

```
failed to deploy a stack: unpoller 
Pulling chronograf 
Pulling influxdb 
Pulling grafana 
Pulling f5f4dd548a3b 
Pulling fs layer 159188936457 
Pulling fs layer ec3798527a7b 
Pulling fs layer no matching manifest for linux/arm/v7 in the manifest list entries 
```

At the end of the day this isn't an unpoller issue, but documentation could be clearer to make this easier on others. 

- Align version reccommendations in the dependencies and docker-compose documentation. (The Dependencies page for Influx (https://unpoller.com/docs/dependencies/influxdb) mentions explicitly to avoid version 2, but the sample docker compose file uses version 2.5)
- Add a mention of the Influx version to the docs around authentication. After downgrading to 1.8 in the docker compose file, the ADMIN_TOKEN (and later the token instructions in Grafana) cause issues (since support for this was added in influx v2). In the short term I had to disable HTTP_AUTH to get Grafana to connect to influx, but there are definitely better solutions. 

I assume using v2 is the end goal, but during the transition things got a bit confusing. 

_(Loving the Grafana visuals by the way, I've been looking for a way to track unifi data better for a while and this has been great)_

**Comment by platinummonkey** [comment]
we've reverted this back to v1.8 series of influx
