### ISSUE TITLE
Compatibility with UDMP 2.4.x and 2.5.x

### ISSUE THREAD

**Issue by diegobaccino** [unpoller/unpoller#534]
Before I go upgrading my Unifi Dream Machine Pro to the latest version (2.5.17) and potentially break UnPoller integration, I wanted to ask if someone has upgraded and can validate UnPoller works with no issues. I'm still running UDM Pro v1.12.38 and need to upgrade to 2.4.27 first to jump to 2.5.17. 

I would appreciate it very much.

**Comment by platinummonkey** [comment]
I'm on 2.5.17 and it continues to function.
