### ISSUE TITLE
Retention policies/Continuous queries - common solutions (Influxdb)

### ISSUE THREAD

**Issue by psyciknz** [unpoller/unpoller#544]
I guess similar to #259 
Are thhere any common continuous queries and retrention policy setups that can be shared documented?  I have CQs on clients and some of the other tables.  But after turning on DPI I noticed a space blow out in my influxdb.  And was curious if there were some base CQs people had worked out, that could be added to the documentation.  To help people manage space.

That or the ability to assign a single measurement to a different retention policy.  Ie ClientDPI to a 30 day retention policy rather than use the database default autogen.

**Comment by psyciknz** [comment]
Yes, it is specific to iinflux.
I've updated the title to reflect that.  But I believe the questions still stand.

**Comment by platinummonkey** [comment]
perhaps https://community.influxdata.com/t/how-to-create-a-retention-policy-for-measurement/21190 answers your question?

I imagine the duration depends on:
- How much storage space each deployment would have
- How long they need to keep it for any contractual reason
- How much they are willing to keep paying for storage and maintenance costs
