### ISSUE TITLE
Is UDMP's temperature accurate when running the latest OS?

### ISSUE THREAD

**Issue by cdalvaro** [unpoller/unpoller#547]
I was comparing some charts in Grafana between the unpoller metrics and the node-exporter metrics, and I have found that one of the unpoller's temperature is much higher than the other.

These are the temperatures registered by unpoller:

![Screen Shot 2023-04-21 at 18 21 06](https://user-images.githubusercontent.com/16347742/233686369-bb74f4b2-3103-4bc4-bdda-8d0d824e4d5d.png)

And these are the ones that node-exporters read from the udm-pro:

![Screen Shot 2023-04-21 at 18 22 38](https://user-images.githubusercontent.com/16347742/233686612-2de3411f-96c7-483f-b738-b5406a29e079.png)

Finally this is the output I get from the command `sensors`, which is in agreement with node-exporter metrics:

```
adt7475-i2c-4-2e
Adapter: i2c-0-mux (chan_id 3)
in1:         885.00 mV (min =  +0.00 V, max =  +2.99 V)
+3.3V:         3.23 V  (min =  +2.96 V, max =  +3.63 V)
fan1:        4393 RPM  (min =    0 RPM)
fan2:        1347 RPM  (min =    0 RPM)
fan3:        1347 RPM  (min =    0 RPM)
fan4:        1347 RPM  (min =    0 RPM)
temp1:        +57.5°C  (low  = -63.0°C, high = +191.0°C)
                       (crit = +100.0°C, hyst = +96.0°C)
Board Temp:   +54.8°C  (low  = -63.0°C, high = +191.0°C)
                       (crit = +100.0°C, hyst = +96.0°C)
temp3:        +54.5°C  (low  = -63.0°C, high = +191.0°C)
                       (crit = +100.0°C, hyst = +96.0°C)
```

Maybe there is an issue with the CPU temperature registered by unpoller?

**Comment by platinummonkey** [comment]
this would be whatever the device API reports back, so if it differs this would be a unifi bug to file
