### ISSUE TITLE
Failed to parse line protocol

### ISSUE THREAD

**Issue by DawidCh** [unpoller/unpoller#548]
Hey.
I'm trying to configure unpoller with influx cloud. I have downloaded the newest docker image for controller (7.3) and the newest for unpoller. In the bucket, in grafana cloud, I can only see usw_port measurements, no others.
Previously I was running my setup on influx db in AWS, no issues.
Now in the logs I can see:
influxdb2client E! Write error: invalid: failed to parse line protocol: error writing line 2: Unable to insert iox::column_type::tag type into column wan_ip with type iox::column_type::field::string
What can I do to solve it?

**Comment by DawidCh** [comment]
Here is configuration taken from influx cloud "to be used with telegraf to connect":
[[outputs.influxdb_v2]]
  urls = ["https://eu-central-1-1.aws.cloud2.influxdata.com"]
  token = "$INFLUX_TOKEN"
  organization = "superorg"
  bucket = "telegraf"
The data are being stored in the influx db so I assume configuration is right:
![image](https://user-images.githubusercontent.com/14540695/235070001-61a6c13d-fd13-42dc-9bb3-1d5afd93a33c.png)

I'm gonna look for more detailed logs.

**Comment by platinummonkey** [comment]
looks like this is solved?

**Comment by DawidCh** [comment]
> looks like this is solved?

Actually no. I couldn't get it working and I didn't find anything in the logs so I moved to influx on premise.

**Comment by platinummonkey** [comment]
yeah I'm not sure this is something I can sustainably support, we use their open source client and if it's incompatible with their cloud offering this might be an issue to file with influx
