### ISSUE TITLE
USG Dashboard Error - Templating [Host]

### ISSUE THREAD

**Issue by drmmr763** [unpoller/unpoller#551]
<img width="1618" alt="image" src="https://user-images.githubusercontent.com/643104/236652386-04943674-dda2-46f9-aa79-671590d9f1d3.png">

I get the above error with the USG Dashboard (https://grafana.com/grafana/dashboards/10416). I didn't customize the dashboard at all this is direct from import. 

Sadly the error seems to kill the dashboard entirely:
<img width="1664" alt="image" src="https://user-images.githubusercontent.com/643104/236652435-7d8b9ba2-a5e5-44ac-a16d-47d5479e3e98.png">

All the rest of them work and show data as expected. Any ideas on how to fix this?

**Comment by x86txt** [comment]
Same error here with the UXG. The USW dashboards work fine and pull the switch ports form my UXG.
