### ISSUE TITLE
docker compose influxdb not creating setting up initial admin account and dbs/orgs

### ISSUE THREAD

**Issue by NoOneAtHome** [unpoller/unpoller#558]
Posted this on Discord too and didn't get any response thought i would try here 

I am using the docs here, https://unpoller.com/docs/install/dockercompose/ and after setting my values in .env and  bringing the docker up the influx db log is littered with:

[httpd] 172.19.0.5 - - [17/May/2023:23:39:12 +0000] "POST /api/v2/write?bucket=unpoller&org=unpoller&precision=ns HTTP/1.1 " 404 45 "-" "influxdb-client-go/2.12.3 (linux; amd64)" 070bec88-f50c-11ed-806c-0242ac130002 25

As expected unpoller has this in the logs:
2023/05/17 23:39:12 influxdb2client E! Write error: 404 Not Found: database not found: "unpoller"

I also see this in the lnfluxdb log 
ts=2023-05-17T23:45:06.442465Z lvl=info msg="Auth is enabled but shared-secret is blank. BearerAuthentication is disabled." log_id=0hs1V530000 service=httpd

It appears that for reasons i do not understand it is not honoring DOCKER_INFLUXDB_INIT_MODE, DOCKER_INFLUXDB_INIT_USERNAME,DOCKER_INFLUXDB_INIT_PASSWORD or DOCKER_INFLUXDB_INIT_ADMIN_TOKEN from the .env

**Comment by bashmail** [comment]
I am also having same kind of problem. I am getting this error while adding data source in grafana

InfluxDB returned error: error authorizing query: create admin user first or disable authentication error reading influxDB

**Comment by Toasterme** [comment]
Same as the other guy said, any fix for thsi ?

**Comment by austinbrowder** [comment]
It would appear that the unpoller documentation and docker-compose file are written with configs for influxdb v2+ which do not work on influxdb 1.8 (which is used by unpoller). I had to change my env variables as follows AND use basic auth on my grafana influxdb data source to get around this.

```
environment:
    - INFLUXDB_DB=${INFLUXDB_DB}
    - INFLUXDB_HTTP_AUTH_ENABLED=${INFLUXDB_HTTP_AUTH_ENABLED}
    - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
    - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
```
