### ISSUE TITLE
Compatibility with UDMPro 3.0.x? 

### ISSUE THREAD

**Issue by diegobaccino** [unpoller/unpoller#561]
Hi all-  I don't have a test environment for my Unifi system, so I can't test. Can someone confirm that there are no issues when migrating the UDM Pro to 3.0.x? Much appreciated.

**Comment by benchristian88** [comment]
No issues on mine. Been keeping udm pro and unpoller up to date and all working well . Running 3.0.20 on udm pro. And 2.7.20 unpoller now and working fine

**Comment by diegobaccino** [comment]
Thank you for your input .

> No issues on mine. Been keeping udm pro and unpoller up to date and all working well . Running 3.0.20 on udm pro. And 2.7.20 unpoller now and working fine
