### ISSUE TITLE
No sites found?

### ISSUE THREAD

**Issue by dennisbrouwer91** [unpoller/unpoller#563]
Hi,

Running a UDM Pro on 3.x here, just configured unpoller but only seeing this every couple of seconds : 
logger.go:18: [INFO] UniFi Metrics Recorded. Site: 0, Client: 0, Gateways: 0, UAP: 0, USW: 0, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 0, Fields: 0, Err: 0, Dur: 1ms

No data, any idea what might be going on?

**Comment by davidnewhall** [comment]
Seems like the user account you're using doesn't have access to the api data. Try a different user account to verify.

**Comment by dennisbrouwer91** [comment]
When i log in with the user to the Unifi Console (UDMP) i can see the site and all the data, so that does not seem to be the problem.

**Comment by cromulon-actual** [comment]
Same issue, and the problem exists in the variables. When you look at the query being set for Controller, you get data. When you look at the one that's trying to pull "Site" you get no data.

**Comment by dennisbrouwer91** [comment]
Any update on this? Still not working with an UDMP

**Comment by platinummonkey** [comment]
share your config along with additional logs. In addition the version of unpoller and the version of UDMP.

**Comment by dennisbrouwer91** [comment]
Version container : v2.7.13
UDMP Version : v3.1.15
Unifi version : 7.4.162
Logs : 
2023/08/09 08:57:57.018604 logger.go:18: [INFO] UniFi Metrics Recorded. Site: 0, Client: 0, Gateways: 0, UAP: 0, USW: 0, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 0, Fields: 0, Err: 0, Dur: 2ms

**Comment by platinummonkey** [comment]
Can you post the config and all the logs. That’s only part of the information

**Comment by dennisbrouwer91** [comment]
[unpoller_config.txt](https://github.com/unpoller/unpoller/files/12302024/unpoller_config.txt)
Added Unpoller config. There are not more logs, this is logged every few seconds.

**Comment by platinummonkey** [comment]
the startup logs is what I’m looking for. This contains more information about the initial connection and discovery. For a container just restart the container and it’ll restart the process. (Fwiw there is also a newer version of the container available on ghcr.io)

**Comment by dennisbrouwer91** [comment]
I guess default, in a UDMP you don't have an option to create multiple sites, it's limited to the default one.

**Comment by dennisbrouwer91** [comment]
According to the URL from the Unifi controller, it's indeed `default`

**Comment by platinummonkey** [comment]
hm, do me a favor and update to the latest 2.8.1 release, there should be more logs here 🤔 I would have expected this to pick it up.

**Comment by dennisbrouwer91** [comment]
Done, see logs. Same result :( 

`
2023/08/09 16:08:51 | stdout | 2023/08/09 14:08:51.076130 logger.go:19: [INFO] UniFi Metrics Recorded. Site: 0, Client: 0, Gateways: 0, UAP: 0, USW: 0, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 0, Fields: 0, Err: 0, Dur: 3ms
2023/08/09 16:08:21 | stdout | 2023/08/09 14:08:21.043682 logger.go:19: [INFO] Poller->InfluxDB started, version: 1, interval: 30s, dp: false, db: unifi, url: http://192.168.2.117:8086, bucket: , org:
2023/08/09 16:08:21 | stdout | 2023/08/09 14:08:21.043593 logger.go:19: [INFO] InfluxDB enabled
2023/08/09 16:08:21 | stdout | 2023/08/09 14:08:21.043575 outputs.go:101: [DEBUG] output plugin disabled for prometheus
2023/08/09 16:08:21 | stdout | 2023/08/09 14:08:21.043567 outputs.go:101: [DEBUG] output plugin disabled for loki
2023/08/09 16:08:21 | stdout | 2023/08/09 14:08:21.043553 outputs.go:95: [DEBUG] output plugin enabled, starting run loop for influxdb
2023/08/09 16:08:21 | stdout | 2023/08/09 14:08:21.043544 outputs.go:101: [DEBUG] output plugin disabled for datadog
2023/08/09 16:08:21 | stdout | 2023/08/09 14:08:21.043535 outputs.go:101: [DEBUG] output plugin disabled for WebServer
2023/08/09 16:08:21 | stdout | 2023/08/09 14:08:21.043522 start.go:110: [DEBUG] staring outputs
2023/08/09 16:08:21 | stdout | 2023/08/09 14:08:21.043513 inputs.go:116: [DEBUG] returning error: %!w(<nil>)
2023/08/09 16:08:21 | stdout | 2023/08/09 14:08:21.043503 inputs.go:97: [DEBUG] collecting input errors...
2023/08/09 16:08:21 | stdout | 2023/08/09 14:08:21.043486 inputs.go:89: [DEBUG] input successfully initialized ... unifi
2023/08/09 16:08:21 | stdout | 2023/08/09 14:08:21.043471 updateweb.go:196: [INFO]    => Save Rogue APs: false
2023/08/09 16:08:21 | stdout | 2023/08/09 14:08:21.043460 updateweb.go:196: [INFO]    => Save Alarms false / Anomalies false (logs)
2023/08/09 16:08:21 | stdout | 2023/08/09 14:08:21.043451 updateweb.go:196: [INFO]    => Save Events false / Save IDS false (logs)
2023/08/09 16:08:21 | stdout | 2023/08/09 14:08:21.043444 updateweb.go:196: [INFO]    => Save Sites true / Save DPI true (metrics)
2023/08/09 16:08:21 | stdout | 2023/08/09 14:08:21.043437 updateweb.go:196: [INFO]    => Hash PII false / Drop PII false / Poll Sites: default
2023/08/09 16:08:21 | stdout | 2023/08/09 14:08:21.043428 updateweb.go:196: [INFO]    => Username: unifipoller (has password: true)
2023/08/09 16:08:21 | stdout | 2023/08/09 14:08:21.043420 updateweb.go:196: [INFO]    => URL: https://192.168.2.1 (verify SSL: false)
2023/08/09 16:08:21 | stdout | 2023/08/09 14:08:21.043391 updateweb.go:196: [INFO] No controllers configured. Polling dynamic controllers only! Defaults:
2023/08/09 16:08:21 | stdout | 2023/08/09 14:08:21.043354 inputs.go:80: [DEBUG] inititalizing input... unifi
2023/08/09 16:08:21 | stdout | 2023/08/09 14:08:21.043331 inputs.go:72: [DEBUG] initializing 1 inputs
2023/08/09 16:08:21 | stdout | 2023/08/09 14:08:21.043322 start.go:104: [INFO] UniFi Poller v2.8.1 Starting Up! PID: 1
2023/08/09 16:08:21 | stdout | 2023/08/09 14:08:21.043278 start.go:101: [DEBUG] Debug Logging Enabled
2023/08/09 16:08:21 | stdout | 2023/08/09 14:08:21 [INFO] Loading Configuration File: /etc/unpoller/up.conf

`

**Comment by platinummonkey** [comment]
try launching this with the `-d` flag  I'm curious if this sheds more info about the udm response here.

**Comment by dennisbrouwer91** [comment]
Doesn't look like more info is there with debug logs : 



```
2023/08/10 08:00:10 | stdout | 2023/08/10 06:00:10.818789 logger.go:19: [INFO] Poller->InfluxDB started, version: 1, interval: 30s, dp: false, db: unifi, url: http://192.168.2.117:8086, bucket: , org:
-- | -- | --
2023/08/10 08:00:10 | stdout | 2023/08/10 06:00:10.818658 logger.go:19: [INFO] InfluxDB enabled
2023/08/10 08:00:10 | stdout | 2023/08/10 06:00:10.818646 outputs.go:101: [DEBUG] output plugin disabled for prometheus
2023/08/10 08:00:10 | stdout | 2023/08/10 06:00:10.818630 outputs.go:101: [DEBUG] output plugin disabled for loki
2023/08/10 08:00:10 | stdout | 2023/08/10 06:00:10.818619 outputs.go:95: [DEBUG] output plugin enabled, starting run loop for influxdb
2023/08/10 08:00:10 | stdout | 2023/08/10 06:00:10.818609 outputs.go:101: [DEBUG] output plugin disabled for datadog
2023/08/10 08:00:10 | stdout | 2023/08/10 06:00:10.818599 outputs.go:101: [DEBUG] output plugin disabled for WebServer
2023/08/10 08:00:10 | stdout | 2023/08/10 06:00:10.818587 start.go:110: [DEBUG] staring outputs
2023/08/10 08:00:10 | stdout | 2023/08/10 06:00:10.818578 inputs.go:116: [DEBUG] returning error: %!w(<nil>)
2023/08/10 08:00:10 | stdout | 2023/08/10 06:00:10.818558 inputs.go:97: [DEBUG] collecting input errors...
2023/08/10 08:00:10 | stdout | 2023/08/10 06:00:10.818542 inputs.go:89: [DEBUG] input successfully initialized ... unifi
2023/08/10 08:00:10 | stdout | 2023/08/10 06:00:10.818528 updateweb.go:196: [INFO]    => Save Rogue APs: false
2023/08/10 08:00:10 | stdout | 2023/08/10 06:00:10.818513 updateweb.go:196: [INFO]    => Save Alarms false / Anomalies false (logs)
2023/08/10 08:00:10 | stdout | 2023/08/10 06:00:10.818501 updateweb.go:196: [INFO]    => Save Events false / Save IDS false (logs)
2023/08/10 08:00:10 | stdout | 2023/08/10 06:00:10.818490 updateweb.go:196: [INFO]    => Save Sites true / Save DPI true (metrics)
2023/08/10 08:00:10 | stdout | 2023/08/10 06:00:10.818479 updateweb.go:196: [INFO]    => Hash PII false / Drop PII false / Poll Sites: default
2023/08/10 08:00:10 | stdout | 2023/08/10 06:00:10.818462 updateweb.go:196: [INFO]    => Username: unifipoller (has password: true)
2023/08/10 08:00:10 | stdout | 2023/08/10 06:00:10.818449 updateweb.go:196: [INFO]    => URL: https://192.168.2.1 (verify SSL: false)
2023/08/10 08:00:10 | stdout | 2023/08/10 06:00:10.818420 updateweb.go:196: [INFO] No controllers configured. Polling dynamic controllers only! Defaults:
2023/08/10 08:00:10 | stdout | 2023/08/10 06:00:10.818384 inputs.go:80: [DEBUG] inititalizing input... unifi
2023/08/10 08:00:10 | stdout | 2023/08/10 06:00:10.818362 inputs.go:72: [DEBUG] initializing 1 inputs
2023/08/10 08:00:10 | stdout | 2023/08/10 06:00:10.818354 start.go:104: [INFO] UniFi Poller v2.8.1 Starting Up! PID: 1
2023/08/10 08:00:10 | stdout | 2023/08/10 06:00:10.818285 start.go:101: [DEBUG] Debug Logging Enabled
2023/08/10 08:00:10 | stdout | 2023/08/10 06:00:10 [INFO] Loading Configuration File: /etc/unpoller/up.conf

```

**Comment by davidnewhall** [comment]
I feel like we need the logs when it tries to poll the controller. Looks like it's not running long enough for that to happen in these logs.

> No controllers configured.

This also makes me go hm since influxdb can't poll dynamic controllers. I'm hoping this log line is just out of place. Try setting this to false.
```
[unifi]
dynamic = false
```

**Comment by dennisbrouwer91** [comment]
Strange, after setting the dynamic setting to false, restarting the container it started working! Thanks so much for the support.

**Comment by spali** [comment]
Can confirm that.
Only started to work after setting `UP_UNIFI_DYNAMIC: "false"` in compose.
Maybe documentation example of prometheus should be corrected for this.
