### ISSUE TITLE
Adding Unifi devices to my network causes spikes in data

### ISSUE THREAD

**Issue by johannbrink** [unpoller/unpoller#564]
I have a strange scenario that causes spikes in the graphs. The selected data is for the switch port connected to my Reolink CCTV NVR. I have the camera feed open on my computer and there are no dropped video frames whatsoever, so I suspect it is a reporting issue. 

The purple line that hovers around the 6MB/s mark is the expected behaviour. Have a look at the line before 14:10 and after 15:15. It starts flip-flopping between zero and double the expected rate. Before 14:10 I had a spare USW Flex Mini switch connected to my main switch, but with no other devices connected. I disconnected this switch at 14:10. At 15:15 I switch on a spare AP that I have that is meshed to one of the other wired AP's. It has the same behaviour.

This happens on both the Clients data set and the USW data sets in the Influx db. 

![Screenshot 2023-06-14 at 3 25 38 pm](https://github.com/unpoller/unpoller/assets/14206717/51fe657c-7470-4c29-b2c4-5157fe6f443b)
![Screenshot 2023-06-14 at 3 33 33 pm](https://github.com/unpoller/unpoller/assets/14206717/75366641-a28a-4c41-b0f5-dbac212759f2)

**Comment by davidnewhall** [comment]
This happens when the controller does not update within the polling interval. Try a longer polling interval. From 30 to 60 seconds usually corrects this behavior.

**Comment by johannbrink** [comment]
Hi David, thank you for the tip. I adjusted the interval and it made somewhat of a difference, but still slightly problematic.
![Screenshot 2023-06-15 at 4 46 51 pm](https://github.com/unpoller/unpoller/assets/14206717/a4a235da-e13d-4a3e-bd9f-f4f83d6ee906)

First section: 30s interval extra devices disabled
2nd section: 45s & 60s intervals with extra devices enabled
3rd section: 60s interval with extra devices disabled again.
