### ISSUE TITLE
UNIFI Controller monitoring error with docker

### ISSUE THREAD

**Issue by bolvia** [unpoller/unpoller#574]
Good morning my friend!!

I'm facing an error that I saw that you were able to resolve... "https://127.0.0.1:8443/": dial tcp 127.0.0.1:8443: connect: connection refused

Can you give me a boost?

**Comment by kacprzak-michael** [comment]
App inside container?

**Comment by davidnewhall** [comment]
The error means you're using the wrong url. Fix that in your configuration.

**Comment by bolvia** [comment]
Good afternoon my friend!

Do you say the url of the controller?

I put https://172.20.20.11, exactly what I use to access a controller

Em dom., 16 de jul. de 2023 às 13:42, David Newhall <
***@***.***> escreveu:

**Comment by bolvia** [comment]
My help with this please

**Comment by bolvia** [comment]
nano unifi-poller.conf

[unifi.defaults]
 url = "https://172.20.20.11:8443"
 user = "unifi-poller"
 pass = "teste@123"
 save_dpi = true
[influxdb]
 url = "http://172.20.20.87:8086"

**Comment by davidnewhall** [comment]
Provide more info.

1. How did you install the app?
2. At what path is your config file?
3. What command did you use to restart after you edited the config file?
4. How did you confirm it restarted?
5. Are the other configuration directives being applied? (share the log file.....)

**Comment by bolvia** [comment]
Opa.. segue extamente o que diz neste video

https://www.youtube.com/watch?v=OaKcQUb2gYc

**Comment by bolvia** [comment]
Oops.. follow exactly what it says in this video

https://www.youtube.com/watch?v=OaKcQUb2gYc

**Comment by bolvia** [comment]
Good afternoon sir.

I solved my problem by adjusting the directories I installed. I was
installing the files in the wrong folders and etc.. Mine communicated
with the same controller's ip


Em ter., 18 de jul. de 2023 às 14:02, Witt ***@***.***>
escreveu:
