### ISSUE TITLE
New beta controller 7.5.165 (first 7.5) seems to have a changed data structure again

### ISSUE THREAD

**Issue by user45876** [unpoller/unpoller#575]
Hi,

7.5 seems to have changed the data structure again. Since upgrading, this is showing in the log and the data in influx is stopping right after the controller update:

`2023/07/17 23:05:04 [ERROR] metric fetch for InfluxDB failed: unifi.GetClients(https://192.168.128.254): json: cannot unmarshal number 129.78061073228582 into Go struct field Client.data.tx_bytes-r of type int64: error initializing inputs `

I will see if I can get a json payload tomorrow accorgint to https://github.com/unpoller/unpoller/issues/47 .

Thanks for your great work :)

**Comment by user45876** [comment]
OK, got the export - unfoirtunately it is way too long - I sanitized most of it but it is 43k lines. Is there anything that is most important?

**Comment by okleinschmidt** [comment]
> Hi,
> 
> 7.5 seems to have changed the data structure again. Since upgrading, this is showing in the log and the data in influx is stopping right after the controller update:
> 
> `2023/07/17 23:05:04 [ERROR] metric fetch for InfluxDB failed: unifi.GetClients(https://192.168.128.254): json: cannot unmarshal number 129.78061073228582 into Go struct field Client.data.tx_bytes-r of type int64: error initializing inputs `
> 
> I will see if I can get a json payload tomorrow accorgint to #47 .
> 
> Thanks for your great work :)

Same for me.

```
2023/07/18 06:38:11 [ERROR] metric fetch failed: unifi.GetClients(https://udm.xxxx.org): json: cannot unmarshal number 52.96005706134095 into Go struct field Client.data.tx_bytes-r of type int64: error initializing inputs
```

**Comment by EisernUnion** [comment]
same here 

metric fetch for InfluxDB failed: unifi.GetClients(https://xx.xxxxxxxx): json: cannot unmarshal number 10.788414181292264 into Go struct field Client.data.bytes-r of type int64
2023/07/18 08:36:02.595960 influxdb.go:269: [INFO] UniFi Metrics Recorded. Sites: 0, Clients: 0, UAP: 0, USG/UDM: 0, USW: 0, IDS Events: 0, Points: 0, Fields: 0, Errs: 1, Elapsed: 1ms

**Comment by user45876** [comment]
So this seems to be the fields around tx_byets-r for a switch:

          ],
          "poe_class": "Class 3",
          "poe_current": "102.53",
          "poe_enable": true,
          "poe_good": true,
          "poe_power": "4.91",
          "poe_voltage": "47.88",
          "rx_broadcast": 308,
          "rx_bytes": 2081919027331,
          "rx_dropped": 0,
          "rx_errors": 0,
          "rx_multicast": 0,
          "rx_packets": 1682536375,
          "satisfaction": 100,
          "satisfaction_reason": 0,
          "speed": 100,
          "stp_pathcost": 200000,
          "stp_state": "forwarding",
          "tx_broadcast": 251482,
          "tx_bytes": 55052624446,
          "tx_dropped": 0,
          "tx_errors": 0,
          "tx_multicast": 1179472,
          "tx_packets": 859226496,
          "up": true,
          "tx_bytes-r": 53278.4325591951,
          "rx_bytes-r": 2021725.0170209548,
          "bytes-r": 2075003.44958015,
          "port_security_enabled": true,
          "stp_port_mode": true,
          "native_networkconf_id": "xxxxxxxx",
          "name": "xxxxxxxx",
          "isolation": false,
          "port_security_mac_address": [
            "xx:xx:xx:xx:xx:xx"
          ],
          "masked": false,
          "aggregated_by": false
        },

And for a UAP:

      },
      "led_override": "off",
      "disconnected_at": 1689616613,
      "architecture": "mips",
      "has_fan": false,
      "has_eth1": false,
      "model_incompatible": false,
      "model_in_eol": false,
      "vwire_table": [],
      "has_temperature": false,
      "switch_caps": {},
      "snmp_location": "",
      "model_in_lts": false,
      "kernel_version": "4.4.153",
      "serial": "xxxxxxxx",
      "fixed_ap_available": true,
      "led_override_color_brightness": 100,
      "adopted": true,
      "hash_id": "xxxxxxxx",
      "device_id": "xxxxxxxx",
      "uplink": {
        "uplink_mac": "xxxxxxxx",
        "uplink_device_name": "xxxxxxxx",
        "uplink_remote_port": 3,
        "port_idx": 1,
        "type": "wire",
        "tx_bytes": 9439049,
        "rx_bytes": 8855542,
        "tx_packets": 28686,
        "rx_packets": 22255,
        "tx_bytes-r": 1844.064401137184,
        "rx_bytes-r": 1065.9183643407428,
        "full_duplex": true,
        "ip": "xxxxxxxx",
        "mac": "xxxxxxxx",
        "name": "xxxxxxxx",
        "netmask": "0.0.0.0",
        "num_port": 1,
        "rx_dropped": 0,
        "rx_errors": 0,
        "rx_multicast": 0,
        "speed": 1000,
        "tx_dropped": 14,
        "tx_errors": 4093,
        "up": true,
        "max_speed": 1000,
        "uplink_source": "lldp_uplink"
      },

Does this help?

**Comment by platinummonkey** [comment]
release is building for `v2.7.15` that should fix this

**Comment by platinummonkey** [comment]
ha, thanks unifi 🙃

**Comment by platinummonkey** [comment]
ah this is a fun one - yet another reason to finish this integration test 🙃

**Comment by aolik08** [comment]
'''influxdb.Write(points): {"error":"partial write: field type conflict: input field \"anomalies\" on measurement \"clients\" is type string, already exists as type integer dropped=11"}'''

but why not use float instead of int?

**Comment by platinummonkey** [comment]
influx permanently casts a storage series type as the first that it records. So since it was always an int64 type prior it's forever that (or the metric name needs to change, or drop all data prior and start fresh). It's an influx decision.

**Comment by EisernUnion** [comment]
verflixt ... ... but within my influxdb for unifipoller .... there is no data ... (dont know why... for me its a fresh start anyway)...

**Comment by hanneskaiser** [comment]
Did another quick test with v2.7.19 -> Grafana looks a lot better, dashboards show now more data then before.
I cleared my influxdb once more, all data removed before testing.
Then looked through all graphs on each dashboard:
2 graphs in Client Insights dashboard still have the same issue as before:
- Client Transmit Retries
- Client Wifi Tx Attempts

Both with same error as with 2.7.18: InfluxDB Error: unsupported derivative iterator type: *query.stringInterruptIterator

**Comment by hanneskaiser** [comment]
Another test with v2.7.20, influx db cleared again before the test --> all graphs are showing data, didn't see any obvious issues at a first walk through all graphs.

Thanks to all for this quick fix, you are amazing.

**Comment by okleinschmidt** [comment]
Thank you so much for the quick fix, awesome!!
Can confirm also prometheus works again. I had to change all metrics from `unifipoller_*` to `unpoller_*`

**Comment by user45876** [comment]
Same, confirming that it is working again. Thank you so much :)
