### ISSUE TITLE
Dashboard USG Insight - Bandwidth usage realtime

### ISSUE THREAD

**Issue by hermawans** [unpoller/unpoller#587]
how to change the dashboard instead of previewing the bandwidth speed test with the current real-time bandwidth usage?

![Screenshot 2023-08-01 at 17 06 14](https://github.com/unpoller/unpoller/assets/94463753/47501483-0982-4467-a67c-2d0a2378f8c5)

**Comment by daNutzzzzz** [comment]
I would like to know too

**Comment by SemoTech** [comment]
I third that, we really need Bandwidth Usage info, ideally per ISP when using dual-WAN connections!

**Comment by lslamp** [comment]
Was anything ever done to view the current real-time bandwidth usage?

**Comment by daNutzzzzz** [comment]
> Was anything ever done to view the current real-time bandwidth usage?

nope
