### ISSUE TITLE
Unifi: (Docker / Unpoller / Prometheus / Grafana)

### ISSUE THREAD

**Issue by daNutzzzzz** [unpoller/unpoller#591]
Hi,

Im trying to set this up using Prometheus and im running into an issue:

When loading unpoller container im getting the following syntax error in the logs which puts the container in a constant reboot loop

```
[ERROR] env unmarshal: UP_POLLER_DEBUG: strconv.ParseBool: parsing "\"false\"": invalid syntax
[INFO] Loading Configuration File: /etc/unifi-poller/up.conf
[ERROR] env unmarshal: UP_POLLER_DEBUG: strconv.ParseBool: parsing "\"false\"": invalid syntax
[INFO] Loading Configuration File: /etc/unifi-poller/up.conf
[ERROR] env unmarshal: UP_POLLER_DEBUG: strconv.ParseBool: parsing "\"false\"": invalid syntax
[INFO] Loading Configuration File: /etc/unifi-poller/up.conf
[ERROR] env unmarshal: UP_POLLER_DEBUG: strconv.ParseBool: parsing "\"false\"": invalid syntax
[INFO] Loading Configuration File: /etc/unifi-poller/up.conf
```

Im used the https://[raw.githubusercontent.com/unpoller/unpoller/master/examples/up.conf.example](https://raw.githubusercontent.com/unpoller/unpoller/master/examples/up.conf.example) file as a base and have tweaked it accordingly for my setup.

I've validated the syntax against a TOML validator and it passes.

**Comment by davidnewhall** [comment]
Seems like you're passing in an env variable with quotes in it. Docker compose is bad about that. :(
