### ISSUE TITLE
Scaling Unifi Poller - How many controllers/sites are possible?

### ISSUE THREAD

**Issue by Chris-CWLLC** [unpoller/unpoller#595]
I just came across this project after a customer asked for a way to monitor a location "without logging in". I have successfully deployed UnPoller and provided this customer with a scrubbed, single dashboard. I had to restrict the configuration to pull only this one sites data on a controller with 50 sites (700ish devices, 2000+ users) and I also have about a dozen stand alone console implementations.

What are the basic guidelines for reducing the amount of data polled so I can begin building single-customer multi-site dashboards across multiple unifi instances. I'm really only concerned with the WAN subsystem to monitor WAN link health and system uptime.

I'm not familiar with InfluxDB so I'm not capable of reviewing the DB to see how much data each subsystem is responsible for. I'm also comfortable extending the polling period well beyond 60 seconds. 300 would be perfectly adequate.

**Comment by platinummonkey** [comment]
Just shard the configuration across many instances (containers, vms or separate processes or all those combined). It’ll horizontally scale with devices and go is very efficient.

currently there is no way to limit to a specific type of data but look at the config if you want to scrub pii data to drop some tags. 

Beyond that for your data store, you’ll need to do your own estimations and costs, as that’s outside the scope of support here.
