### ISSUE TITLE
USG Insights - InfluxDB showing no data. Query Error

### ISSUE THREAD

**Issue by AxelFooley** [unpoller/unpoller#598]
This is a fresh install, i've used docker compose.

My UDM-SE is reachable at https://10.0.110.1, i've imported all dashboards from Grafana marketplace without making any change to them.
All dashboards work fine except for Client Insights and USG Insights.

USG Insights throws this error:

![image](https://github.com/unpoller/unpoller/assets/5037273/664ec61e-73cc-4fc8-b76d-8030e4624081)

Client insights throws this error:

![image](https://github.com/unpoller/unpoller/assets/5037273/93d70bac-7a9e-4381-8932-7c7cb361cc50)

My env file looks like this:

```
#influxdb
INFLUXDB_HTTP_AUTH_ENABLED=true
INFLUXDB_ADMIN_USER=unpoller
INFLUXDB_ADMIN_PASSWORD=unpoller
INFLUXDB_DB=unpoller
INFLUXDB_ORG=unpoller
INFLUXDB_BUCKET=unpoller
INFLUXDB_ADMIN_TOKEN=unpoller

#grafana
GRAFANA_USERNAME=admin
GRAFANA_PASSWORD=admin

#unifi-poller
POLLER_TAG=latest
POLLER_DEBUG=false
POLLER_SAVE_DPI=true
UNIFI_USER=unpoller
UNIFI_PASS=XXXXX
UNIFI_URL=https://10.0.110.1
UP_UNIFI_DEFAULT_SAVE_DPI=true
```

**Comment by davidnewhall** [comment]
What version of Grafana is throwing these errors?

**Comment by benchristian88** [comment]
same issue running grafana 10.2.0.  all the data is there but lots of the graphs and data queries are showing no data. 

this is the original query on the UAP Insights, 
SELECT last("ip") AS "Address", last("uptime") AS "Uptime", last("last_seen") *1000 AS "Last Seen", last("cpu") AS "CPU", last("user-num_sta") AS "Users", last("guest-num_sta") AS "Guests" FROM "uap" WHERE ("name" =~ /^$AP$/ AND "site_name" =~ /^$Site$/) AND $timeFilter GROUP BY "name", "model", "serial", "site_name", "source", "type", "version", "mac"

If I delete the  /^$AP$/  field, it works.  eg.
SELECT last("ip") AS "Address", last("uptime") AS "Uptime", last("last_seen") *1000 AS "Last Seen", last("cpu") AS "CPU", last("user-num_sta") AS "Users", last("guest-num_sta") AS "Guests" FROM "uap" WHERE $timeFilter GROUP BY "name", "model", "serial", "site_name", "source", "type", "version", "mac"

the switch insights pages also now don't allow the drop downs to select the various switch ports etc.  
will try a grafana rollback and see what happens.  

anguler plugin giving error as deprecated too, but i think you already have issue for that.

**Comment by SeekingHelp24** [comment]
Stupid question (hope this isn't the wrong place) but how do I roll back the grafana version? I am on 10.2.0 and seeing so many N/A and I am not skilled enough at this point to fix the variables, but sort of need this in full function as quickly as possible I am running all 3 via Docker-Compose

**Comment by AxelFooley** [comment]
Just change grafana/grafana:latest in your docker compose file into grafana/grafana:10.0.3

**Comment by SeekingHelp24** [comment]
> Just change grafana/grafana:latest in your docker compose file into grafana/grafana:10.0.3

Thank you! That was far more simple that Google results were telling me! I feel sort of dull now!

**Comment by RedSpid3r** [comment]
> Just change grafana/grafana:latest in your docker compose file into grafana/grafana:10.0.3

Fixed my issue of Grafana graphs being blank. Thanks!
