### ISSUE TITLE
Prometheus error

### ISSUE THREAD

**Issue by groupe3sun** [unpoller/unpoller#600]
I have this message : 
expected value after metric, got "\n" ("INVALID") while parsing: "unpoller\n"

Unifi controller : 7.2.92.0
Prometheus : 2.45.0

**Comment by platinummonkey** [comment]
sounds like a configuration issue, post your config and which version of unpoller you are on

**Comment by groupe3sun** [comment]
Unpoller version 2.8.1 branch HEAD revision 1

configuration prometheus :  
- job_name: 'unpoller'
    metrics_path: /unifi
    scrape_interval: 30s
    static_configs:
      - targets: ['127.0.0.1:9130']

up.conf : 
[prometheus]
  disable = false
  # This controls on which ip and port /metrics is exported when mode is "prometheus".
  # This has no effect in other modes. Must contain a colon and port.
  http_listen = "0.0.0.0:9130"
  # Adding an SSL Cert and Cert Key will make Poller listen with SSL/https.
  ssl_cert_path = ""
  ssl_key_path  = ""
  # Errors are rare. Setting this to true will report them to Prometheus.
  report_errors = false
  ## Record data for disabled or down (unlinked) switch ports.
  dead_ports = false

**Comment by davidnewhall** [comment]
Where does this message appear? Which log? Is there any more context around the error you can add?

> expected value after metric, got "\n" ("INVALID") while parsing: "unpoller\n"

Is this still happening with the latest version?
