### ISSUE TITLE
[ERROR] listen tcp 192.168.2.65:9100: bind: cannot assign requested address

### ISSUE THREAD

**Issue by khisanthax** [unpoller/unpoller#629]
Hello,

I'm using prometheus on a different VM than where I stinaleld unpoller.  When I use the external address: UP_PROMETHEUS_HTTP_LISTEN=192.168.2.65:9100 I get [ERROR] listen tcp 192.168.2.65:9100: bind: cannot assign requested address.  I made sure to change all the ports to 9100.  Is there something else I can do to get this to work on a prometheus on another VM?

**Comment by platinummonkey** [comment]
this would be a system specific issue. Be sure nothing else is running there and your user has privileges to bind to that port.
