### ISSUE TITLE
Grafana-Prometheus Dashboards using 'unpoller' in all metrics

### ISSUE THREAD

**Issue by DrewBiermann** [unpoller/unpoller#633]
Grafana-Prometheus Dashboards using 'unpoller' in all metrics but the metric data pulled in from the controller via prometheus is labeled 'unifipoller'.

E.g. `unpoller_client_uptime_seconds` vs `unifipoller_client_uptime_seconds`

Dashboards show up empty unless you go in and modify this.

**Comment by RedEchidnaUK** [comment]
Not sure if you fixed this, but I found the same issue. What confused me, I had it was working using a local install, then I ran it in a Docker container using the community Docker compose example and I noticed all of the metrics started with `unifipoller`. 

I realised that the community Docker compose example sets the `UP_PROMETHEUS_NAMESPACE=unifipoller`, and that's the issue, it should be `UP_PROMETHEUS_NAMESPACE=unpoller`

**Comment by DrewBiermann** [comment]
@RedEchidnaUK I didn't catch that initially. Looking at my compose file now it does have it set to unifipoller. I wish I had seen that before I went and edited all the queries in the dashboards ha ha. Your solution is obviously the quickest fix.

**Comment by DrewBiermann** [comment]
@RedEchidnaUK has the easiest fix. Just modify your docker-compose to us `UP_PROMETHEUS_NAMESPACE=unpoller `and the dashboards will work.
