### ISSUE TITLE
Can't connect to UDM:  Auth or Connection Error, retrying: unifi controller

### ISSUE THREAD

**Issue by Jsalas424** [unpoller/unpoller#639]
I haven't been able to connect to my Unifi Dream Machine. I have unpoller installed in an Ubuntu 20.04 VM. 

Relevant logs:
```
jon@monitor:~$ tail -f -n100  /var/log/syslog /var/log/messages | grep unpoller
tail: cannot open '/var/log/messages' for reading: No such file or directory
Nov  8 21:03:02 monitor unpoller[33626]: 2023/11/08 21:03:02.541623 updateweb.go:222: [DEBUG] Collecting controller data: https://192.168.1.2:8443 ()
Nov  8 21:03:02 monitor unpoller[33626]: 2023/11/08 21:03:02.541661 updateweb.go:196: [INFO] Re-authenticating to UniFi Controller: https://192.168.1.2:8443
Nov  8 21:03:31 monitor systemd[1]: Stopping unpoller - Telemetry and Observability for your UniFi Network...
Nov  8 21:03:31 monitor systemd[1]: unpoller.service: Succeeded.
Nov  8 21:03:31 monitor systemd[1]: Stopped unpoller - Telemetry and Observability for your UniFi Network.
Nov  8 21:03:36 monitor systemd[1]: Started unpoller - Telemetry and Observability for your UniFi Network.
Nov  8 21:03:36 monitor unpoller[33676]: 2023/11/08 21:03:36 [INFO] Loading Configuration File: /etc/unpoller/up.conf
Nov  8 21:03:36 monitor unpoller[33676]: 2023/11/08 21:03:36.326987 start.go:101: [DEBUG] Debug Logging Enabled
Nov  8 21:03:36 monitor unpoller[33676]: 2023/11/08 21:03:36.327040 start.go:104: [INFO] UniFi Poller v2.9.2 Starting Up! PID: 33676
Nov  8 21:03:36 monitor unpoller[33676]: 2023/11/08 21:03:36.327055 inputs.go:72: [DEBUG] initializing 1 inputs
Nov  8 21:03:36 monitor unpoller[33676]: 2023/11/08 21:03:36.327088 inputs.go:80: [DEBUG] inititalizing input... unifi
Nov  8 21:03:36 monitor unpoller[33676]: 2023/11/08 21:03:36.327120 updateweb.go:222: [DEBUG] Requesting https://192.168.1.2/ to determine API paths
Nov  8 21:05:46 monitor unpoller[33676]: 2023/11/08 21:05:46.244114 updateweb.go:209: [ERROR] Controller 1 of 1 Auth or Connection Error, retrying: unifi controller: making request: Get "https://192.168.1.2/": dial tcp 192.168.1.2:443: connect: connection timed out
```

My UDM is at 192.168.1.2, and I can use the credentials listed in my config file to successfully log in. 

User config:
<img width="401" alt="image" src="https://github.com/unpoller/unpoller/assets/51519895/cfbb81a5-3e0e-42ba-970c-a878bbbc08cd">

Confirmed that it's not my firewall blocking calls:
<img width="1139" alt="Screen Shot 2023-11-08 at 9 31 24 PM" src="https://github.com/unpoller/unpoller/assets/51519895/c8d1379a-9143-4e8c-ab4d-33acae6537cc">

Config file:
```
[prometheus]
  disable = false
  # This controls on which ip and port /metrics is exported when mode is "prometheus".
  # This has no effect in other modes. Must contain a colon and port.
  http_listen = "0.0.0.0:9130"
  # Adding an SSL Cert and Cert Key will make Poller listen with SSL/https.
  ssl_cert_path = ""
  ssl_key_path  = ""
  # Errors are rare. Setting this to true will report them to Prometheus.
  report_errors = false
  ## Record data for disabled or down (unlinked) switch ports.
  dead_ports = false

[unifi.defaults]
  # URL for the UniFi Controller. Do not add any paths after the host:port.
  # Do not use port 8443 if you have a UDM; just use "https://ip".
  url = "https://192.168.1.2"

  # Make a read-only user in the UniFi Admin Settings, allow it access to all sites.
  user = "unifipoller"

  pass = "password"

  sites = ["all"]

  save_sites = true
```

UniFi OS Version | 3.1.16

Thanks for any help

**Comment by davidnewhall** [comment]
```
Get "https://192.168.1.2/": dial tcp 192.168.1.2:443: connect: connection timed out
```

Ubuntu is throwing an error that the connection to your controller is timing out. Might be a different firewall in the way. Can other tools reach the controller from the Ubuntu system? curl?

**Comment by Jsalas424** [comment]
> ```
> Get "https://192.168.1.2/": dial tcp 192.168.1.2:443: connect: connection timed out
> ```
> 
> Ubuntu is throwing an error that the connection to your controller is timing out. Might be a different firewall in the way. Can other tools reach the controller from the Ubuntu system? curl?

The only other firewall would be the UDM itself. If I curl or ping the UDM, I can watch it pass through the pfsense firewall then proceed no further. I can still ping and curl other devices on the UDM's subnet, just not the UDM itself. 

```
jon@monitor:~$ ping 192.168.1.1
PING 192.168.1.1 (192.168.1.1) 56(84) bytes of data.
64 bytes from 192.168.1.1: icmp_seq=1 ttl=64 time=0.401 ms
64 bytes from 192.168.1.1: icmp_seq=2 ttl=64 time=0.566 ms
64 bytes from 192.168.1.1: icmp_seq=3 ttl=64 time=0.536 ms
^C
--- 192.168.1.1 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2042ms
rtt min/avg/max/mdev = 0.401/0.501/0.566/0.071 ms

jon@monitor:~$ curl 192.168.1.1
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

jon@monitor:~$ ping 192.168.1.2
PING 192.168.1.2 (192.168.1.2) 56(84) bytes of data.
^C
--- 192.168.1.2 ping statistics ---
144 packets transmitted, 0 received, 100% packet loss, time 146421ms

jon@monitor:~$ curl 192.168.1.2
^C
```

Since I use pfsense to do all the routing,, my UDM fw rules are very sparse:
<img width="801" alt="image" src="https://github.com/unpoller/unpoller/assets/51519895/3cac735f-1ae0-4d22-88f7-e80736f9217a">

At the time of writing this ticket, I only had the "Allow mgmt Network access to all VLAN" rule in place. I have tried and failed to add the "Allow Monitor access to UDM" rule.

The Monitoring VM and the UDM are in different VLANs. The UDM doesn't route traffic between VLAN's, I just have tagged frames passed to pfsense with the "Allow mgmt Network access to all VLAN" rule. 
<img width="782" alt="image" src="https://github.com/unpoller/unpoller/assets/51519895/93263bad-1014-412e-991f-3a3e08947270">

**Comment by davidnewhall** [comment]
> jon@monitor:~$ curl 192.168.1.2
> ^C

You're not able to reach the controller from the ubuntu server? I'm not sure we can troubleshoot a linux routing problem in a GitHub issue. Try another computer; unpoller runs on mac and windows too.

--- 
> The only other firewall would be the UDM itself ...

> Since I use pfsense to do all the routing ...

pfsense is a firewall, so is ubuntu when iptables (or any other netlink filter) are enabled.

> If I curl or ping the UDM, I can watch it pass through the pfsense firewall then proceed no further

The controller never replied with a SYN packet? Sounds like something prevented it.

**Comment by Jsalas424** [comment]
I installed unpoller in a container on the same subnet as the UDM. No issues connecting, this was something to do with VLANs. I then pointed my prometheus config to scrape unpoller metrics from the CT across the VLAN and that worked fine.
