### ISSUE TITLE
grafana 10.1.5 is the latest version in docker works for influx data graphs

### ISSUE THREAD

**Issue by fate8383** [unpoller/unpoller#644]
Hi, I am using grafana with latest tag and it seems like since 10.1.5 all my unpoller influx data is not showing in the grafana. I rolled back to 10.1.5 and they all came back. I am using other stuff in Grafana and latest is something i need to use, is there any way to keep unpoller graphs to be consistent with latest tag? Am I doing something wrong?

**Comment by platinummonkey** [comment]
see #633 and perhaps many other similar issues
