### ISSUE TITLE
Authentication failed on indluxDB and grafana

### ISSUE THREAD

**Issue by galihprad** [unpoller/unpoller#645]
![Screenshot from 2023-11-21 08-54-03](https://github.com/unpoller/unpoller/assets/25057923/136a3b54-feaf-4536-8e3b-c6aa38e1f815)

I use docker
Version:           24.0.4
API version:       1.43
Go version:        go1.20.5

Grafana (docker) and
InfluxDB 1.8 (docker)

The poller, influxdb, and grafana works well before. It start failed about 5 days ago (16 november).
Is there any API change in unifi controller? (but not updated yet in the poller). 
I could login with the same username and password in unifi controller. 
But  failed when the poller try to login to the unifi controller.
(It start failed about 5 days ago (16 november))

**Comment by platinummonkey** [comment]
The title and screenshot don’t match. This looks like your unifi user changed or permissions changed on an update.
