### ISSUE TITLE
Metric fetch for InfluxDB failed: unifi.GetSites(), get 401 : invalid status code from server

### ISSUE THREAD

**Issue by galihprad** [unpoller/unpoller#647]
![Screenshot from 2023-11-27 09-51-56](https://github.com/unpoller/unpoller/assets/25057923/d8957c27-39a9-48cd-b364-7d57e66bf7b4)

I use docker
Version: 24.0.4
API version: 1.43
Go version: go1.20.5

Grafana (docker) and
InfluxDB 1.8 (docker)

Recently the unifi-poller, grafana, and influxdb works well. But it start error with some different log (since about 16 november), this screenshot is the latest error log.
I wait for the solution.
Thank you

**Comment by platinummonkey** [comment]
401 is an authentication failure status code. People have recently had problems with unpoller users getting reset on upgrades
