### ISSUE TITLE
USW Insights - No Detail Data shown

### ISSUE THREAD

**Issue by futureweb** [unpoller/unpoller#651]
Hey there,
directly installed on Centos 7, no Docker. Was already running smothly, but with no changes now all Detail Data in USW Insights are missing. Already tried re-importing Grafana Dashboard, also updated unpoller to latest version (yum repository)

Dashboard looking like:

![grafik](https://github.com/unpoller/unpoller/assets/1698881/e8a69cc6-5349-4513-8c9a-136a73c8c84f)

Logs not showing any errors I can spot?

```
Dec  4 18:45:26 localhost systemd: Started unpoller - Telemetry and Observability for your UniFi Network.
Dec  4 18:45:26 localhost unpoller: 2023/12/04 18:45:26 [INFO] Loading Configuration File: /etc/unpoller/up.conf
Dec  4 18:45:26 localhost unpoller: 2023/12/04 18:45:26 [INFO] UniFi Poller v2.9.4 Starting Up! PID: 9766
Dec  4 18:45:27 localhost unpoller: 2023/12/04 18:45:27 [INFO] Found 1 site(s) on controller https://xxxxxxx:8443/: default (xxxxxxxxx)
Dec  4 18:45:27 localhost unpoller: 2023/12/04 18:45:27 [INFO] Configured UniFi Controller 1 of 1:
Dec  4 18:45:27 localhost unpoller: 2023/12/04 18:45:27 [INFO]    => URL: https://xxxxxxxxxxx:8443/ (verify SSL: false)
Dec  4 18:45:27 localhost unpoller: 2023/12/04 18:45:27 [INFO]    => Version: 8.0.7 (096e0535-0699-4f5f-afe6-4655cbd582e7)
Dec  4 18:45:27 localhost unpoller: 2023/12/04 18:45:27 [INFO]    => Username: xxxxx (has password: true)
Dec  4 18:45:27 localhost unpoller: 2023/12/04 18:45:27 [INFO]    => Hash PII false / Drop PII false / Poll Sites: all
Dec  4 18:45:27 localhost unpoller: 2023/12/04 18:45:27 [INFO]    => Save Sites true / Save DPI false (metrics)
Dec  4 18:45:27 localhost unpoller: 2023/12/04 18:45:27 [INFO]    => Save Events false / Save IDS false (logs)
Dec  4 18:45:27 localhost unpoller: 2023/12/04 18:45:27 [INFO]    => Save Alarms false / Anomalies false (logs)
Dec  4 18:45:27 localhost unpoller: 2023/12/04 18:45:27 [INFO]    => Save Rogue APs: false
Dec  4 18:45:27 localhost unpoller: 2023/12/04 18:45:27 [INFO] Prometheus is enabled
Dec  4 18:45:27 localhost unpoller: 2023/12/04 18:45:27 [INFO] InfluxDB enabled
Dec  4 18:45:27 localhost unpoller: 2023/12/04 18:45:27 [INFO] Poller->InfluxDB started, version: 1, interval: 30s, dp: false, db: unifi, url: http://127.0.0.1:8086, bucket: , org:
Dec  4 18:45:27 localhost unpoller: 2023/12/04 18:45:27 [INFO] Prometheus exported at http://0.0.0.0:9130/ - namespace: unpoller
Dec  4 18:45:58 localhost unpoller: 2023/12/04 18:45:58 [INFO] UniFi Metrics Recorded. Site: 1, Client: 204, Gateways: 1, UAP: 83, USW: 13, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 830, Fields: 24364, Err: 0, Dur: 477ms
Dec  4 18:46:28 localhost unpoller: 2023/12/04 18:46:28 [INFO] UniFi Metrics Recorded. Site: 1, Client: 204, Gateways: 1, UAP: 83, USW: 13, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 830, Fields: 24367, Err: 0, Dur: 221ms
Dec  4 18:46:58 localhost unpoller: 2023/12/04 18:46:58 [INFO] UniFi Metrics Recorded. Site: 1, Client: 201, Gateways: 1, UAP: 83, USW: 13, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 827, Fields: 24265, Err: 0, Dur: 237ms
Dec  4 18:47:28 localhost unpoller: 2023/12/04 18:47:28 [INFO] UniFi Metrics Recorded. Site: 1, Client: 202, Gateways: 1, UAP: 83, USW: 13, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 828, Fields: 24299, Err: 0, Dur: 192ms
Dec  4 18:47:58 localhost unpoller: 2023/12/04 18:47:58 [INFO] UniFi Metrics Recorded. Site: 1, Client: 202, Gateways: 1, UAP: 83, USW: 13, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 828, Fields: 24299, Err: 0, Dur: 171ms
Dec  4 18:48:28 localhost unpoller: 2023/12/04 18:48:28 [INFO] UniFi Metrics Recorded. Site: 1, Client: 202, Gateways: 1, UAP: 83, USW: 13, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 828, Fields: 24299, Err: 0, Dur: 173ms
Dec  4 18:48:58 localhost unpoller: 2023/12/04 18:48:58 [INFO] UniFi Metrics Recorded. Site: 1, Client: 201, Gateways: 1, UAP: 83, USW: 13, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 827, Fields: 24265, Err: 0, Dur: 195ms
Dec  4 18:49:28 localhost unpoller: 2023/12/04 18:49:28 [INFO] UniFi Metrics Recorded. Site: 1, Client: 201, Gateways: 1, UAP: 83, USW: 13, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 827, Fields: 24262, Err: 0, Dur: 194ms
Dec  4 18:49:58 localhost unpoller: 2023/12/04 18:49:58 [INFO] UniFi Metrics Recorded. Site: 1, Client: 198, Gateways: 1, UAP: 83, USW: 13, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 824, Fields: 24160, Err: 0, Dur: 220ms
Dec  4 18:50:28 localhost unpoller: 2023/12/04 18:50:28 [INFO] UniFi Metrics Recorded. Site: 1, Client: 198, Gateways: 1, UAP: 83, USW: 13, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 824, Fields: 24160, Err: 0, Dur: 237ms
```

Hope someone here got an idea what's going wrong?!?

Thank you! :-)

**Comment by manicmoose** [comment]
Known issue.
You'll need to roll back to Grafana 10.1.5 or earlier, or try and fix the graphs yourself.
It's currently unknown what is wrong with them that newer Grafana doesn't like.

**Comment by futureweb** [comment]
@manicmoose thank you - that did the trick! :-)

Here's a general approach:

1. **Backup:** Before proceeding with any downgrade, it's crucial to back up your Grafana configuration and data.

2. **Remove Existing Grafana Installation:**
   ```bash
   sudo yum remove grafana
   ```

3. **Disable Grafana Repository:** If you have the Grafana repository enabled, you might want to disable it to prevent automatic updates.
   ```bash
   sudo vi /etc/yum.repos.d/grafana.repo
   ```

   Comment out or remove the lines that start with `enabled=1`.

4. **Download Grafana RPM for Version 10.1.5:**
   Check the Grafana release page (https://grafana.com/grafana/download) for the specific version you want and get the download link for the RPM file.

   ```bash
   wget https://dl.grafana.com/oss/release/grafana-10.1.5-1.x86_64.rpm
   ```

5. **Install the Downgraded Version:**
   ```bash
   sudo yum localinstall grafana-10.1.5-1.x86_64.rpm
   ```

6. **Prevent Automatic Updates:**
   To avoid accidental updates, you can exclude Grafana from future updates by adding it to the exclude list in `/etc/yum.conf`:
   ```bash
   sudo vi /etc/yum.conf
   ```

   Add the following line:
   ```
   exclude=grafana*
   ```

7. **Start Grafana:**
   ```bash
   sudo systemctl start grafana-server
   ```

8. **Enable Grafana at Boot:**
   ```bash
   sudo systemctl enable grafana-server
   ```

**Comment by bigjohns97** [comment]
I have found the issue with the latest version, it has to do with the variables defined at the top, if you remove these from the query panels then everything starts working again. 

For me this is better than rolling back as I never used those filters anyways and just used these as static dashboards.

IMO this issue should remain open until the panels are updated, I don't see Grafana changing back to support whatever the incompatibility is, these panels and this project will probably have to update.

**Comment by bigjohns97** [comment]
After digging a little bit further it's just the site variable it has troubles with, if you remove that from the downstream variables everything starts working.

**Comment by bigjohns97** [comment]
OK this is odd, it seems that after 10.1.5-1 they did some sort of attempted conversion because if you go back and write the original query for the Site variable everything works again.

`SHOW TAG VALUES FROM "clients" WITH KEY = "site_name"  WHERE source =~ /^$Controller$/`

**Comment by manicmoose** [comment]
Good pickup, @bigjohns97.
I also played with this briefly and I found that I simply need to edit the 'Site' variable and untick the 2 "Selection Options" at the bottom, hit 'Apply' and then save the dashboard.
All working with Grafana 10.2.3

**Comment by futureweb** [comment]
Do I understand right? Everything working again with Grafana >10.1.5? In this Case I would let the Ticket closed, otherwise I could reopen it?
