### ISSUE TITLE
Can't connect to influxDB 2.0

### ISSUE THREAD

**Issue by ymurawski** [unpoller/unpoller#652]
Hi i tried to config the unpoller settings file. I tried it with password and token but none of them works.
There is always an error called
`2023/12/07 14:13:26 [ERROR] influxdb.Write(points): {"code":"unauthorized","message":"Unauthorized"}
`
this is my config file 
`[influxdb]
  disable = false
  # InfluxDB does not require auth by default, so the user/password are probably unimportant.
  url  = "http://127.0.0.1:8086"
  user = "admin"
  # Password for InfluxDB user (above).
  # If the password provided here begins with file:// then the password is read in from
  # the file path that follows the file:// prefix. ex: file:///etc/influxdb/passwd.file
  pass = "cviIsiLTW6dKY0m3iu9VxWn8jSwIgRoe6-sY7b-F9JtF1Oht76upt2JSV81dx2yn-8lQjaJ-Z-KKc-DObP3Oig=="
  # Be sure to create this database. See the InfluxDB Wiki page for more info.
  db = "unifi"
  # If your InfluxDB uses a valid SSL cert, set this to true.
  verify_ssl = false
  # The UniFi Controller only updates traffic stats about every 30 seconds.
  # Setting this to something lower may lead to "zeros" in your data.
  # If you're getting zeros now, set this to "1m"
  interval = "30s"
  ## Record data for disabled or down (unlinked) switch ports.
  dead_ports = false
`

Any ideas ? the db (bucket) is created

**Comment by opello** [comment]
While I didn't get this error specifically, I did infer from reading the code that you can just set it to output to infludbv2 using something like:

```toml
[influxdb]
  disable = false
  url  = "http://172.17.0.1:8086"
  auth_token = ""
  org = ""
  bucket = ""
```

It is a documentation deficiency and I wasn't exactly sure how to address it.

#456 shows the change being made, and the [output plugin README.md](https://github.com/unpoller/unpoller/blob/a148f669da27c08a1daf5036abaf2b5e1b3c14c5/pkg/influxunifi/README.md) shows an example in YAML.  However, the [configuration documentation](https://unpoller.com/docs/install/configuration/#overview) mentions [this example configuration file](https://github.com/unpoller/unpoller/blob/master/examples/up.conf.example) which is TOML.

Not being a regular developer of Go programs, [the configuration structure changes from the PR](https://github.com/unpoller/unpoller/pull/456/files#diff-04a37838f672e29d96a612cfc126f8f9ce117a15eb7cf91dbd1d09b8d42bdce1R46-R53) sure seemed like it could "just work" to shove the data into the up.conf's `[influxdb]` section, and happily it did.

Is just adding a few lines to the sample config the right answer?  Happy to open a PR for that if you like.  And is it worth writing down somewhere that up.conf could be a TOML, YAML, JSON, or even XML file?  Or is that not intended as a first-class feature to maintain?  Or is that not even a true conclusion to have drawn?

**Comment by opello** [comment]
Surely the "auth_token" ensures that access is authenticated?  I didn't mean to suggest that an empty string worked as the value.  I had to fill in the token I generated.

**Comment by platinummonkey** [comment]
ah yeah, `auth_token` triggers the v2 client usage for influx v2. Their authentication standards changed during v2 and their go client expects an authentication token.
