### ISSUE TITLE
[Prometheus] No data on dashboards

### ISSUE THREAD

**Issue by cyberm8** [unpoller/unpoller#653]
**Environment**

- Unifi versions: I have two instances: one is self-hosted and the other is on a dream machine, both running 7.5.187
- Prometheus version: v2.48.0
- Grafana version: 10.2.1
- Unpoller version: 2.9.4

**Issue**

I imported all the dashboards for Prometheus and none of them is showing any piece of data.

![image](https://github.com/unpoller/unpoller/assets/117109145/de76c507-5591-4f48-aaf6-02144fda3f1d)

**Configurations**

Two servers running Docker are involved: one hosts Unifi and Unpoller, the other one hosts grafana and prometheus.

I followed the docs to add a new container in the docker-compose file of the self-hosted Unifi instance.

```yml
# docker-compose of server 1 (unifi and unpoller)
[...]

  unpoller:
    image: ghcr.io/unpoller/unpoller:v2.9.4
    container_name: unpoller
    restart: always
    environment:
      - UP_INFLUXDB_DISABLE=true
      - UP_POLLER_DEBUG=false
      - UP_UNIFI_DYNAMIC=false
      - UP_PROMETHEUS_HTTP_LISTEN=0.0.0.0:9130
      - UP_PROMETHEUS_NAMESPACE=unifipoller
      # First controller (local, self hosted)
      - UP_UNIFI_CONTROLLER_0_SAVE_ALARMS=true
      - UP_UNIFI_CONTROLLER_0_SAVE_ANOMALIES=true
      - UP_UNIFI_CONTROLLER_0_SAVE_DPI=false
      - UP_UNIFI_CONTROLLER_0_SAVE_EVENTS=true
      - UP_UNIFI_CONTROLLER_0_SAVE_IDS=false
      - UP_UNIFI_CONTROLLER_0_SAVE_SITES=true
      - UP_UNIFI_CONTROLLER_0_URL=https://unifi.lan.xyz.fr:443
      - UP_UNIFI_CONTROLLER_0_USER=unifipoller
      - UP_UNIFI_CONTROLLER_0_PASS=hidden
      # Second controller (remote dream machine)
      - UP_UNIFI_CONTROLLER_1_SAVE_ALARMS=true
      - UP_UNIFI_CONTROLLER_1_SAVE_ANOMALIES=true
      - UP_UNIFI_CONTROLLER_1_SAVE_DPI=false
      - UP_UNIFI_CONTROLLER_1_SAVE_EVENTS=true
      - UP_UNIFI_CONTROLLER_1_SAVE_IDS=false
      - UP_UNIFI_CONTROLLER_1_SAVE_SITES=true
      - UP_UNIFI_CONTROLLER_1_URL=https://unifi2.lan.xyz.fr:443
      - UP_UNIFI_CONTROLLER_1_USER=unifipoller
      - UP_UNIFI_CONTROLLER_1_PASS=hidden
    ports:
      - 9130:9130
```

As I already had a prometheus and a grafana up and running, I decided not to add an influxdb instance just for unpoller.

```yml
# docker-compose of server 2 (grafana and prometheus)
[...]
      # Install plugins for grafana
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel,natel-discrete-panel
```

```yml
# prometheus.yaml
[...]

# Unifi APs (Unpoller)
  - job_name: 'unifipoller'
    scrape_interval: 30s
    static_configs:
      - targets:
        - https://unifi.xyz.fr:443
        - https://unifi2.lan.xyz.fr:443
    metrics_path: /scrape
    relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: hidden_ip_of_server_hosting_unpoller:9130
```

Running `curl http://0.0.0.0:9130/metrics` shows a lot of data about clients, APs...
Unpoller logs seem to indicate that everything is running fine (every 30 seconds, data is polled).

```
2023/12/10 16:40:49.253399 logger.go:19: [INFO] UniFi Measurements Exported. Site: 1, Client: 56, UAP: 15, USG/UDM: 0, USW: 2, DPI Site/Client: 1/0, Desc: 172, Metric: 4322, Err: 0, 0s: 1640, Req/Total: 38.4ms / 47.6ms
2023/12/10 16:40:56.493198 logger.go:32: [ERROR] metric fetch failed: filter path requested but dynamic lookups disabled: error initializing inputs
2023/12/10 16:41:19.205982 updateweb.go:222: [DEBUG] Collecting controller data: https://unifi.lan.xyz.fr:443 ()
2023/12/10 16:41:19.206003 updateweb.go:222: [DEBUG] Polling controller: https://unifi.lan.xyz.fr:443 ()
2023/12/10 16:41:19.206054 updateweb.go:222: [DEBUG] Requesting https://unifi.lan.xyz.fr:443/api/stat/sites, with params: false, cookies: 2
2023/12/10 16:41:19.207772 updateweb.go:222: [DEBUG] Requested https://unifi.lan.xyz.fr:443/api/stat/sites: elapsed 2ms, returned 790 bytes
2023/12/10 16:41:19.207862 updateweb.go:222: [DEBUG] Found 1 site(s): default
2023/12/10 16:41:19.207872 updateweb.go:222: [DEBUG] Polling Controller, retreiving Site DPI data, site Foo (default)
2023/12/10 16:41:19.207890 updateweb.go:222: [DEBUG] Requesting https://unifi.lan.xyz.fr:443/api/s/default/stat/sitedpi, with params: true, cookies: 2
2023/12/10 16:41:19.208656 updateweb.go:222: [DEBUG] Requested https://unifi.lan.xyz.fr:443/api/s/default/stat/sitedpi: elapsed 1ms, returned 48 bytes
2023/12/10 16:41:19.208684 updateweb.go:222: [DEBUG] Polling Controller, retreiving Client DPI data, site Foo (default)
2023/12/10 16:41:19.208704 updateweb.go:222: [DEBUG] Requesting https://unifi.lan.xyz.fr:443/api/s/default/stat/stadpi, with params: true, cookies: 2
2023/12/10 16:41:19.209416 updateweb.go:222: [DEBUG] Requested https://unifi.lan.xyz.fr:443/api/s/default/stat/stadpi: elapsed 1ms, returned 30 bytes
2023/12/10 16:41:19.209433 updateweb.go:222: [DEBUG] Polling Controller, retreiving UniFi Clients, site Foo (default)
2023/12/10 16:41:19.209449 updateweb.go:222: [DEBUG] Requesting https://unifi.lan.xyz.fr:443/api/s/default/stat/sta, with params: false, cookies: 2
2023/12/10 16:41:19.212078 updateweb.go:222: [DEBUG] Requested https://unifi.lan.xyz.fr:443/api/s/default/stat/sta: elapsed 3ms, returned 75931 bytes
2023/12/10 16:41:19.215283 updateweb.go:222: [DEBUG] Requesting https://unifi.lan.xyz.fr:443/api/s/default/stat/device, with params: false, cookies: 2
2023/12/10 16:41:19.229267 updateweb.go:222: [DEBUG] Requested https://unifi.lan.xyz.fr:443/api/s/default/stat/device: elapsed 14ms, returned 422983 bytes
2023/12/10 16:41:19.232342 updateweb.go:222: [DEBUG] Unmarshalling Device Type: uap, Model: U7LR, site Foo (default)
2023/12/10 16:41:19.232667 updateweb.go:222: [DEBUG] Unmarshalling Device Type: uap, Model: U7IW, site Foo (default)
2023/12/10 16:41:19.233598 updateweb.go:222: [DEBUG] Unmarshalling Device Type: uap, Model: U7LR, site Foo (default)
2023/12/10 16:41:19.234384 updateweb.go:222: [DEBUG] Unmarshalling Device Type: uap, Model: U6IW, site Foo (default)
2023/12/10 16:41:19.235414 updateweb.go:222: [DEBUG] Unmarshalling Device Type: usw, Model: USAGGPRO, site Foo (default)
2023/12/10 16:41:19.237220 updateweb.go:222: [DEBUG] Unmarshalling Device Type: uap, Model: U7LR, site Foo (default)
2023/12/10 16:41:19.237973 updateweb.go:222: [DEBUG] Unmarshalling Device Type: uap, Model: U7LR, site Foo (default)
2023/12/10 16:41:19.238692 updateweb.go:222: [DEBUG] Unmarshalling Device Type: uap, Model: U7LR, site Foo (default)
2023/12/10 16:41:19.239414 updateweb.go:222: [DEBUG] Unmarshalling Device Type: uap, Model: U7LR, site Foo (default)
2023/12/10 16:41:19.240126 updateweb.go:222: [DEBUG] Unmarshalling Device Type: uap, Model: U7LR, site Foo (default)
2023/12/10 16:41:19.240890 updateweb.go:222: [DEBUG] Unmarshalling Device Type: uap, Model: U7LR, site Foo (default)
2023/12/10 16:41:19.241665 updateweb.go:222: [DEBUG] Unmarshalling Device Type: uap, Model: U7LR, site Foo (default)
2023/12/10 16:41:19.242591 updateweb.go:222: [DEBUG] Unmarshalling Device Type: usw, Model: USAGGPRO, site Foo (default)
2023/12/10 16:41:19.243880 updateweb.go:222: [DEBUG] Unmarshalling Device Type: uap, Model: U7IW, site Foo (default)
2023/12/10 16:41:19.244798 updateweb.go:222: [DEBUG] Unmarshalling Device Type: uap, Model: U6IW, site Foo (default)
2023/12/10 16:41:19.246265 updateweb.go:222: [DEBUG] Unmarshalling Device Type: uap, Model: U7LR, site Foo (default)
2023/12/10 16:41:19.246928 updateweb.go:222: [DEBUG] Unmarshalling Device Type: uap, Model: U7IW, site Foo (default)
2023/12/10 16:41:19.257477 logger.go:19: [INFO] UniFi Measurements Exported. Site: 1, Client: 56, UAP: 15, USG/UDM: 0, USW: 2, DPI Site/Client: 1/0, Desc: 172, Metric: 4322, Err: 0, 0s: 1621, Req/Total: 41.2ms / 51.5ms
```

Am I doing something wrong?
If Prometheus isn't the preferred method, I'm willing to give InfluxDB a try.

Thank you very much,

**Comment by jrsecor** [comment]
I'm getting the same results via InfluxDB - logs show that data is getting exported correctly, but none of the grafana dashboards are loading information (except one that shows device info sort of) Not sure what changed, but in my searches, all I've found so far is your report here with no solutions. Have you found anything out since you posted this?

It should be noted that everything was working at one point and just stopped recently (I hadn't checked for a while so I don't know exact date...)

**Comment by wranglatang** [comment]
I have the same problem with a fresh install of unpoller yesterday feeding into an Influx DB. Removing the site site where clause seems to get most of the widgets working! I did notice that the only option in the "Site" filter at the top of each dashboard is "All"

**Comment by jpcapone** [comment]
I have a fresh install with prometheus and I am experiencing this issue.  How exactly do we remove the where clause from the panel?  I would appreciate any assistance, thanks!

**Comment by EisernUnion** [comment]
I just deleted the 'site' variable in each dashboard ....how often i got crazy with this f*** variable in the last years .... :)
@jpcapone

![image](https://github.com/unpoller/unpoller/assets/42810795/99f91d06-0010-45c3-9e04-bee14ff4dbd9)

**Comment by jpcapone** [comment]
Interesting I think what I am seeing here is pointing to another issue:
![image](https://github.com/unpoller/unpoller/assets/47680328/4e79d104-da2f-4b5f-a1d0-e76bdc2e12f2)

**Comment by EisernUnion** [comment]
I made a mistake and had to load a backup (homeassistant, a week old)...... and: Everything is still working....looks like homeassistant updated Grafana recently which caused the issues...
Now Homeassistant is running Grafana at version 9.1.1 , but Grafana itself shows version Grafana v10.1.2 (8e428858dd).... so strange....

@jpcapone

within the query remove the conditional usage of the "site" variable

![image](https://github.com/unpoller/unpoller/assets/42810795/1a236a0c-b4ab-49e1-bd5a-11075192b9c5)

either by removing it in the editing mode (the penicl) or by clicking on the filter

**Comment by user45876** [comment]
@EisernUnion Regarding versions, one is the version of the addon (9.1.x), the other one is the 'real', the embedded Grafana Version (10.x).

**Comment by wranglatang** [comment]
I’m running grafana in unraid and not as a HA add on. I will do a test to see if using an old version of grafana solves the problem.

**Comment by wranglatang** [comment]
Okay! I have done some testing. the version of Grafana that I was running when I spotted the problem was 10.1.6, I tried a collection of previous version's once I got to version [10.0.1](https://hub.docker.com/layers/grafana/grafana/10.0.1/images/sha256-1caf984a3f2e07ea4f5ffd25c16fad0ed0ddac043467e8b9ddaf4cbbc6299ec4?context=explore) of grafana the dashboard sprung into life.

**Comment by EisernUnion** [comment]
Grafana v10.1.2 (8e428858dd) also works fine on HA
![image](https://github.com/unpoller/unpoller/assets/42810795/01cf7200-e642-4141-9ac9-36d6d035dcd7)

This Update : HA 9.11 to 9.12 including a version jump of Grafana from 10.1.2 to 10.2.3 caused my outage... which is actually the last working between 10.1.2 and 10.2.3 is unclear

**Comment by jpcapone** [comment]
> I made a mistake and had to load a backup (homeassistant, a week old)...... and: Everything is still working....looks like homeassistant updated Grafana recently which caused the issues... Now Homeassistant is running Grafana at version 9.1.1 , but Grafana itself shows version Grafana v10.1.2 (8e428858dd).... so strange....
> 
> @jpcapone
> 
> within the query remove the conditional usage of the "site" variable
> 
> ![image](https://private-user-images.githubusercontent.com/42810795/296116655-1a236a0c-b4ab-49e1-bd5a-11075192b9c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNTM3MTYsIm5iZiI6MTcwNTI1MzQxNiwicGF0aCI6Ii80MjgxMDc5NS8yOTYxMTY2NTUtMWEyMzZhMGMtYjRhYi00OWUxLWJkNWEtMTEwNzUxOTJiOWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDE3MzAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MTUyNmFjOWE1NGI3NzAwNjgxY2RlYjE2YTI0YzQxMjFiOTc2MDBmNjE0YjIzMGE1NTc4ZDQxYmFlYzM3NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0jbfcQf_AzHBtRPQ7SRWLvF8w-CFY4_epBBjmGM7VWE)
> 
> either by removing it in the editing mode (the penicl) or by clicking on the filter

I have also found that renaming instances of unpoller to unifipoller within the queries helps with getting some of the panels to light up. 

example: `sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unpoller_device_vap_ccq_ratio{site_name=~"$Site", name=~"$AP"})`

In order for this to work I have to rename unpoller to unifipoller and remove` {site_name=~"$Site", name=~"$AP"}`

Is there a better way?  Am I missing something?
