### ISSUE TITLE
Correct version of influxdb and is the error below caused by the wrong verison?

### ISSUE THREAD

**Issue by Close04** [unpoller/unpoller#656]
Hi everyone!

What is the actual good version of influxdb to be used with unpoller? Is it dependent on the installation method?

- One place suggests 1.7.7 or newer (but below 2.x): https://unpoller.com/docs/poller/faq
- Another says 1,8,x or newer (but below 2.x): https://unpoller.com/docs/dependencies/influxdb
- Another place suggests 2.5: https://unpoller.com/docs/install/synology

I'm installing on a Synology NAS so went for option #3 and I get the dreaded "[ERROR] influxdb.Write(points): {"code":"unauthorized","message":"Unauthorized"}" error when using 2.5 so I'm wondering first if I'm using the correct version before investigating deeper. In theory everything is set up correctly I think. I've had some different issues with latest or 1.8.x so I'm not getting good comparative results for now.

When unpoller starts it logs "InfluxDB started, version:1 [...]". Where is this version picked up from? Is there a specific configuration for it? I tried searching the documentation but with the question above still standing it's hard to get a clear answer.

Thanks!

**Comment by davidnewhall** [comment]
It does not work natively with influx db 2. I use 1.8.x. 1.10 and 1.11 probably work too.

**Comment by Close04** [comment]
Aye, that seems to be the solution. InfluxDB 1.8.9 at the moment works just fine. Thank you very much!

I have a completely different problem right now, with the useful dashboards not showing anything for a UDM, but that's for a different discussion.
