### ISSUE TITLE
Docker Compose yaml missing chronograf reference

### ISSUE THREAD

**Issue by rightfittech** [unpoller/unpoller#657]
The current yaml has a "depends_on" entry for chronograf but there is no service. The website shows the config but the GitHub entry doesn't. Here's what the website shows:

chronograf:
    image: chronograf:latest
    restart: always
    ports:
      - '8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}

**Comment by platinummonkey** [comment]
this is fixed
