### ISSUE TITLE
Auth login issue

### ISSUE THREAD

**Issue by andrewm659** [unpoller/unpoller#658]
Having an issue with Network app 8.0.24 and latest unpoller.  It won't auth against the unpoller.

Controller 1 of 1 Auth or Connection Error, retrying: unifi controller: (user: $USERNAME): https://1.2.3.4:8443/api/login (status: 400 ): authentication failed

**Comment by platinummonkey** [comment]
hey there, check that the upgrade didn't botch your user credentials like many others. Currently this is working fine for others.

**Comment by andrewm659** [comment]
This is a new install..

**Comment by platinummonkey** [comment]
[Did you create a local user](https://unpoller.com/docs/install/controllerlogin)?

**Comment by andrewm659** [comment]
I created this but it also created a ui.com account...

**Comment by platinummonkey** [comment]
ensure this is set 
![image](https://github.com/unpoller/unpoller/assets/310993/509a35e9-f7b4-4104-9759-ae83d0df53f5)


Also suggest using a custom-defined read-only role 
![image](https://github.com/unpoller/unpoller/assets/310993/1d8d722d-2020-4df0-9cbd-fd36bcf68f28)

**Comment by andrewm659** [comment]
Was on the new user interface.  Fixed!!
