### ISSUE TITLE
"stat_" prefix and throughput display questions

### ISSUE THREAD

**Issue by kirsch33** [unpoller/unpoller#663]
Hello, loving unpoller so far! Couple of questions that I cant figure out:

1. what is the significance of the entries with a "stats_" prefix? for example, what's the difference between "bytes" and "stat_bytes"?
2. What is generally accepted best practice for displaying throughput from a switch using Grafana? I am currently using this query (see screenshot) but a bit confused on what to set the time grouping to. I have it to 1m right now. should it be "$interval" or maybe something else totally?
![2024-01-12_10-34](https://github.com/unpoller/unpoller/assets/37373320/b7547c2d-a1d2-49ed-af46-70674516b378)

**Comment by platinummonkey** [comment]
There are some dashboards available in unpoller/dashboards and available through grafana integrations 

stat_ is just data reported from the API
