### ISSUE TITLE
[Prometheus] Not all data shown on Grafana dashboard

### ISSUE THREAD

**Issue by hirnschmalz** [unpoller/unpoller#668]
I installed and configured everything as described in the official documentation. I already have a dedicated Grafana and Prometheus instance in the latest version running.

The problem is, that some graphs has **No data**.

I already looked over all the issues related to this topic but could not find a solution.

# USW Insights

<img width="1181" alt="image" src="https://github.com/unpoller/unpoller/assets/4834988/3cd61683-63d1-47da-9915-a1446d2f4357">

# USG Insights

<img width="1186" alt="image" src="https://github.com/unpoller/unpoller/assets/4834988/d9701244-b78f-44eb-8275-188654442eb3">

# Network Sites

<img width="1181" alt="image" src="https://github.com/unpoller/unpoller/assets/4834988/df82f818-f00d-4fe6-b1a8-79b18242d976">

**Comment by platinummonkey** [comment]
See #653

**Comment by hirnschmalz** [comment]
@platinummonkey thank you for the hint. I already stumbled upon this issue (as upon many others). I tried to remove the `$Site` variable wich broke all widgets. After re-adding the variable at least the widgets that worked before were working again.

Also the defined namespace (`unifipoller` vs. `unpoller`) as discussed in #633 can not be the problem since the metrics are exported with `unpoller` prefixed.

<img width="1294" alt="image" src="https://github.com/unpoller/unpoller/assets/4834988/b3a620e3-abef-4efc-a8a5-2107be581b1e">

Maybe some more information on my environment

* USG 3P 4.4.57
* Self hosted Unifi Controller on Linux (8.0.24)
* Grafana 10.3.1
* Prometheus 2.49.1

**Comment by hirnschmalz** [comment]
@platinummonkey the problem is the `$__interval` variable. See also https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/ for more information.

So from my point of view `$__interval` should be replaced with `$__rate_interval`
