### ISSUE TITLE
UDM Pro - Install Error - API

### ISSUE THREAD

**Issue by Pauzi2304** [unpoller/unpoller#669]
During the installation i get the error: "[ERROR] metric fetch for InfluxDB failed: re-authenticating to https://XXX.XXX.XXX.XXX:8443: unifi controller: (user: Unifipoller): https://XXX.XXX.XXX.XXX:8443/api/login (status: 404 ): authentication failed: error initializing inputs"

Maybe it is the wrong api directory as you can read at "https://ubntwiki.com/products/software/unifi-controller/api"

I am using UDM Pro - UniFi OS 3.2.9

**Comment by platinummonkey** [comment]
Most controllers listen on 443 instead and ensure you have a local user not a cloud user

**Comment by Pauzi2304** [comment]
The port is correct and the user is a local one!
As i have written it seems that the API directory is wrong:
In the wiki is a note that tells that a UDM Pro uses that uri: "https://XXX.XXX.XXX.XXX:8443/api/auth/login"

**Comment by platinummonkey** [comment]
That’s not our wiki so perhaps you can report to unifi directly about inconsistency in their docs to reality. 

Unpoller just polls the local api. Given its saying the combination of host, port and user details there is something wrong in the configuration settings for unpoller or something incorrect about the user account. 

usually careful review is sufficient, you can also use curl to perform the login check directly to validate your controller directly, and if that works it validates its simply the config given to unpoller
