### ISSUE TITLE
Grafana Dashboard: Change Fahrenheit to Celsius?

### ISSUE THREAD

**Issue by Callahan78** [unpoller/unpoller#676]
Is there an easy and simple way to switch from Fahrenheit to Celsius or do I have to change the items all one by one?
(By the way: there is a missing "h" in "Fahrenheit".)
![image](https://github.com/unpoller/unpoller/assets/88541621/3587404e-c2f4-45f7-b3e4-b471ae0244c6)

**Comment by platinummonkey** [comment]
This is a grafana specific question, the templates are only starters, so yes you would need to change each one

**Comment by Callahan78** [comment]
It is clear that it is Grafana. But since the users of these templates are here, there is also a high probability that someone here knows the solution.
If anyone has the same question:
I have meanwhile found out that both Fahrenheit and Celsius are included in the templates, you can show or hide them in edit mode.
Finally, thank you very much for nothing, closing my question in this arrogant way with false information.

**Comment by davidnewhall** [comment]
I'm glad you found the edit and the hide buttons in Grafana.

This isn't a community support portal and no one here owes you anything.

**Comment by Callahan78** [comment]
I fully agree with the content of the replies. But it's a question of friendly interaction. Nobody is forced to answer. You should either answer in a friendly manner or not at all.
All the best for you

**Comment by davidnewhall** [comment]
I don't think you get to decide how we handle our property. No one comes to your house and tells you how you need to treat solicitors. 

No one was rude to you. No one called you names. No one lied to you or provided you false information. If you don't like the answer you shouldn't respond.
