### ISSUE TITLE
(status: 401 Unauthorized): authentication failed

### ISSUE THREAD

**Issue by jsrichie** [unpoller/unpoller#684]
Fresh Install of unpoller

I checked it thru three times, verified passwords, and still get  the error,

Controller 1 of 1 Auth or Connection Error, retrying: unifi controller: (user: unifipoller): http://X.X.X.X/api/login (status: 401 Unauthorized): authentication failed

I verified the password several times / Copy and pasted.

Move to the old interface and do not have the full settings as before.

UniFi OS  3.2.12. 
Network  8.0.28.
 User is  View Only
OS Setting View Only 

Please help me get this back and running again.

**Comment by platinummonkey** [comment]
These should be https and verify the port is either 443 or 8443

**Comment by jsrichie** [comment]
Im running a UDM Pro it states not to use 443 or 8443. I changed to https and get
metric fetch for InfluxDB failed: re-authenticating to https://x.x.x.x443: unifi controller: (user: unifipoller): https://10.0.0.1:443/api/auth/login (status: 403 Forbidden): authentication failed: error initializing inputs

if I use 8443 I get:



[ERROR] metric fetch for InfluxDB failed: re-authenticating to https://10.0.0.1:8443: unifi controller: (user: unifipoller): https://10.0.0.1:8443/api/login (status: 404 ): authentication failed: error initializing inputs

**Comment by jsrichie** [comment]
https://10.0.0.1/proxy/networks/api/auth/login. allows me to log in with the unifipoller id and password to the web UI.

**Comment by platinummonkey** [comment]
This is a local access user correct? It appears 443 is the correct port here for you which is what I expected. 

![image](https://github.com/unpoller/unpoller/assets/310993/613a8f47-f2be-4220-9e15-547e667cff3f)

**Comment by jsrichie** [comment]
Correct local access only

**Comment by platinummonkey** [comment]
This should work, I'm running the same versions, this implies one of the follow:

1. Check the config - it's possible special characters are not being handled here correctly depending on your configuration file format choice
2. The credentials are not correct for this user

**Comment by jsrichie** [comment]
Ok so I have setup again for the fifth time I still get the same message. It will not log in

When it states auth token - this is the password for the unifipoller account on the UDM Pro correct?
| auth token for account created earlier. e.g. unifipoller

Looks like I really need help getting this going again

I did not mention I al running this on a Synology 918+

**Comment by platinummonkey** [comment]
username password combo - you should probably also specify how you are trying to configure this when asking for help

**Comment by jsrichie** [comment]
Configuring with the Synology install process.

**Comment by platinummonkey** [comment]
more to the point: share your config file (redact the passwords) share the exact commands you're using the start and the full log

**Comment by jsrichie** [comment]
I have to run a config file as well as the directions for the synology setup?

**Comment by platinummonkey** [comment]
`share your config file`

and the exact commands

**Comment by jsrichie** [comment]
I used this process https://unpoller.com/docs/install/synology/  I have No Config file with this process

**Comment by platinummonkey** [comment]
you have to have a config file to connect to the right device

**Comment by jsrichie** [comment]
Sorry for the confusion on my part, The Synology process does not mention a config file it appears to get that from the config of the container. Is the config your talking about the up config and where should I locate the file once created?

IE I should follow this first : Installation
Unpoller's Docker container can be configured in two ways:

Using environment variables.
Using a configuration file.

And then config my Synology?

**Comment by platinummonkey** [comment]
it's a container so yeah you need to supply it some config

**Comment by jsrichie** [comment]
The config is coming from the container setup from what I can tell. Under the environment settings
it asks for UP_UNIFI_DEFAULT_URL and the UP_UNIFI_DEFAULT_AUTH_TOKEN which are provided.

**Comment by platinummonkey** [comment]
Please share exactly what you’re doing - I’m afraid I’m going to need to close this otherwise

**Comment by jsrichie** [comment]
On the UDM User unpoller created password set - Limited admin
Prepared Synology & Docker
Run docker & configure network
Created new network:

Named Grafana_Net
Enable IPv4
Get network configuration automatically is selected
Click add


Prepare mapped volumes

/docker/altuha/grafana and /dockeraltuha/influxdb
Download needed images from the registry
unpoller for ghcr.io/unpoller/unpoller:latest https://github.com/unpoller/unpoller/pkgs/container/unpoller
grafana for grafana/grafana:latest https://hub.docker.com/r/grafana/grafana/
influxdb for influxdb:1.8 https://hub.docker.com/_/influxdb/

Create influxdb container
In Image, select influxdb: and click launch
container named influxdb1
Click Advanced Settings
On volume tab add the following:
The /docker/influxdb folder from above to mount path /var/lib/influxdb -  read/write
On the Network tab
Added network Grafana_Net
Removed the default bridge
Ensured that the use the same network as the docker host was unchecked
local port from Auto to 3456 - container port as 8086 and type as TCP
environment tab added the following vars
INFLUXDB_DATA_DIR | /var/lib/influxdb/data
INFLUXDB_DATA_WAL_DIR | /var/lib/influxdb/wal
INFLUXDB_DATA_META_DIR | /var/lib/influxdb/meta
Finalized container and:
Click APPLY
Click NEXT
Click APPLY
SSHed into  Synology
Ran the command sudo docker exec -it influxdb1 bash
followed InfluxDB Post Setup instructions ](https://unpoller.com/docs/dependencies/influxdb#post-setup).
Create unpoller container
In Image select ghcr.io/unpoller/unpoller:latest and click launch
 Container name unpoller1
Click Advanced Settings
On the network tab:
Add network Grafana_Net
Removed the default bridge 
Ensured that the use the same network as docker host was unchecked
On the Environment tab, add the following vars:
UP_INFLUXDB_URL | http://influxdb1:8086
UP_UNIFI_DEFAULT_URL | https://10.0.0.1
UP_UNIFI_DEFAULT_AUTH_TOKEN | unpoller UDM Password
UP_UNIFI_DEFAULT_ORG | unpoller
UP_UNIFI_DEFAULT_BUCKET | unpoller

Finalized the container by:
Click APPLY
Click NEXT
Click APPLY

checked for data and this is where I cant pull data

**Comment by davidnewhall** [comment]
lol you just copy and pasted the docs from the website.

**Comment by davidnewhall** [comment]
The error message at the top of this thread indicates the wrong auth info is provided. ie. bad username or password. Seems like you've tried lots of things related to that and I now suspect your controller is just in a bad state. Might want to consider factory resetting it and starting over.

**Comment by jsrichie** [comment]
Well, I bailed on the Synology direction, used ssh for the installation, and could configure it without issue. The config is then shown in the Synology docker. Seems the Synology direction is missing a few steps and ENV variables. In short all is good now
