### ISSUE TITLE
In Grafana/Prometheus dashboard, some charts are empty when time range is small

### ISSUE THREAD

**Issue by outofsight** [unpoller/unpoller#685]
For example USW Insights, Data Transfer chart show no data when time range is 2 days, but if I change the time range to 1 week suddenly the data appear.

It seems something related to a recent change. I run unpoller since 1y and I never noticed this behavior.

Any idea?

**Comment by platinummonkey** [comment]
hey please move this question to the `unpoller/dashboards` repo. But this is likely a problem with grafana and the data source being used.

**Comment by outofsight** [comment]
Seems related to scraping frequency and minimum interval settings.
But I don't think I changed anything, and I can confirm scraping in grafana agaet is set to 30s.
