### ISSUE TITLE
Unable to install via homebrew on MacOS

### ISSUE THREAD

**Issue by osxster** [unpoller/unpoller#692]
When trying to install via homebrew on MacOS, I am getting the following:

username@server01:~$ brew install golift/mugs/unpoller
Warning: You are using macOS 10.14.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.

==> Fetching golift/mugs/unpoller
==> Downloading https://github.com/unpoller/unpoller/releases/download/v2.10.0/unpoller_2.10.0_darwin_all.tar.gz
Already downloaded: /Users/username/Library/Caches/Homebrew/downloads/ea91216e26cf051aa50b8b9e04af877b8a2064b2dc36b6b62f7a098bf4e00380--unpoller_2.10.0_darwin_all.tar.gz
==> Installing unpoller from golift/mugs
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 11.3.1.

Warning: Formula golift/mugs/unifi-poller was renamed to golift/mugs/unpoller.
Error: An exception occurred within a child process:
  TypeError: no implicit conversion of String into Integer

---

I know I am running an older OS, but this server hardware doesn't support newer.  Any help would be great.

**Comment by platinummonkey** [comment]
I would suggest just using the binary (or build it yourself) directly from the [releases](https://github.com/unpoller/unpoller/releases)
