### ISSUE TITLE
logger.go error, influxdb is empty (not writing anything)

### ISSUE THREAD

**Issue by Devineavenger** [unpoller/unpoller#694]
logger.go:32: [ERROR] event fetch for InfluxDB failed: unifi.GetIDS(): json: cannot unmarshal array into Go struct field IDS.data.catname of type string: error initializing inputs

Please let me know what info you require.

I am trying to pull from both a udm-se and a server application

**Comment by platinummonkey** [comment]
Try v2.11.0

**Comment by Devineavenger** [comment]
I am on 2.11.0

I just deployed everything. I also deployed a influxdb 1.8 especially for this.
Don't know where to look for more details on the error... 
BTW,  Grafana reads just fine from influx.

**Comment by platinummonkey** [comment]
Can you run unpoller -j

this will dump out the json response

**Comment by davidnewhall** [comment]
I think it goes like this:
`unpoller -j "other /proxy/network/api/s/default/stat/ips/event" -c /path/to/up.conf`

**Comment by davidnewhall** [comment]
Does 2.11.1 fix this?

**Comment by Devineavenger** [comment]
Sorry for the late response.
2 things to note.

1st: 2.11.1 fixed the issue. (no ideea what the issue was)
2nd: trying to run a shell to execute that command gave me this error:
"Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "9d3c23def325f6127a768288b994dddd89e3c75365153571b560af111493f912": OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory"

I'm not familiar with go. so maybe it's meant to do that... (container is running in k3s, not docker)

But the problem for this thread is resolved.
