### ISSUE TITLE
error in unpoller

### ISSUE THREAD

**Issue by yarafie** [unpoller/unpoller#699]
Starting getting the below error not sure when but at least a 2 to 3 weeks ago I was fine and was able to view graphs in grafana for influxdb. Prometheus seems to be working fine.

2024/04/10 09:24:11 [INFO] UniFi Measurements Exported. Site: 1, Client: 57, UAP: 2, USG/UDM: 3, USW: 0, DPI Site/Client: 1/94, Desc:
198, Metric: 10555, Err: 0, 0s: 771, Req/Total: 1.0125s / 1.0337s
2024/04/10 09:24:13 [ERROR] event fetch for InfluxDB failed: unifi.GetAlarms(): json: cannot unmarshal array into Go struct field Alarm.data.catname of type string: error initializing inputs

**Comment by declan727** [comment]
I am also seeing this issue. it seems like it might have started after an update on the Unifi side.

**Comment by yarafie** [comment]
To get around this for mow I set Alarm to false in the up.conf file.

**Comment by lslamp** [comment]
I had this issue. The problem is caused by influxdb, they have changed the data type of some of the data that is added into the databases. because the data type is not correct, it does not display the data shown in the db.

My solution was to update unpoller and the grafana templates and then all data was visible again.

I have a few threads about this exact same issue.
Lawrence

**Comment by yarafie** [comment]
> I had this issue. The problem is caused by influxdb, they have changed the data type of some of the data that is added into the databases. because the data type is not correct, it does not display the data shown in the db.
> 
> My solution was to update unpoller and the grafana templates and then all data was visible again.
> 
> I have a few threads about this exact same issue. Lawrence

I updated unpoller but not the grafana templates, will try that. What version of influxdb ate you using?

**Comment by platinummonkey** [comment]
there is a fix in progress

**Comment by cknic** [comment]
I am still getting the issue for both Alarms and IDS.  It prevents unpoller from writing to Influx.  As soon as i set those to false, it works fine.  I am on Unifi 4.0.7, unpoller 2.11.2 and influx 1.8.10

**Comment by sswensen** [comment]
@cknic I am in the same boat as well. 

I did notice that when querying the controller for Alarms, all but one of the entries returned have a timestamp type as a number. One entry has a timestamp field with type String:

```
"timestamp": 1711549174,
```
```
"timestamp": "1712051846",
```

Casting the returned timestamp into a number, similar to the changes in [this commit](https://github.com/unpoller/unpoller/commit/4bd56677c9764f8d213395cacce5fb1d89ba0eff) may resolve the unmarshaling error.

**Comment by platinummonkey** [comment]
Thanks for the debug! I’ll shoot for a fix tomorrow unless you’re able to make a PR sooner
