### ISSUE TITLE
Added UXG Max Gateway, USG Dashboard shows extra Panels.

### ISSUE THREAD

**Issue by lslamp** [unpoller/unpoller#701]
I have just updated my UXG Lite to the UGX Max Gateway device.
The switch went well, only when I open the UniFi-Poller: USG Insights - InfluxDB Dashboard, I am presented with the following dashoard.
![image](https://github.com/unpoller/unpoller/assets/6013759/665f2942-7cb1-4097-a11a-07cd6c538c3d)
I think that this was caused by me renaming the gateway after the installation.
The current name is ICANGateway. No matter what I try I cannot seem to remove the other two Gateway names.
I did try to delete these but then it also ended up deleting the ICANGateway as well.
Looking at the separate dashboards, two of the 3 have no data. The ICANGateway has data as expected.
How can I delete the second two dashboards. Below are all 3 dashboards.
![image](https://github.com/unpoller/unpoller/assets/6013759/d8b4691f-bbde-48be-a1b8-7b028e833f06)

![image](https://github.com/unpoller/unpoller/assets/6013759/3f46eedc-9cbd-4a04-b790-f0cd8ee1533d)

![image](https://github.com/unpoller/unpoller/assets/6013759/ca88f62c-1424-4b16-8ef6-3c04b03f6f85)

Thanks
Lawrence

**Comment by platinummonkey** [comment]
please use https://github.com/unpoller/dashboards/issues instead

**Comment by davidnewhall** [comment]
@lslamp,

You need to remove the measurements from your database that contain this label or field. Look in the documentation for Influx or Prometheus for how to do that.

**Comment by lslamp** [comment]
@davidnewhall 
I have a load of experience with Oracle and Mysql but vey little with influx.
What I do not understand is, if I run the following query then I get the data that needs to be deleted.
SELECT last("uptime") AS "Uptime", last("ip") AS "Address", last("bytes") AS "Data" FROM "usg" WHERE $timeFilter GROUP BY "name", "model", "serial", "site_name", "mac", "version", "source", "type"

name: usg
tags: mac=xx:xx:xx:xx:xx:xx, model=UXGB, name=Gateway Max, serial=xxxxxxxxx, site_name=ICAN (default), source=https://127.0.0.1:8443, type=uxg, version=3.2.13.14740
time Uptime Address       Data
---- ------ -------       ----
0    825    xx.xx.xx.xx 91314934

name: usg
tags: mac=xx:xx:xx:xx:xx:xx, model=UXGB, name=Gateway Max, serial=xxxxxxxxx, site_name=ICAN (default), source=https://127.0.0.1:8443, type=uxg, version=3.2.15.14839
time Uptime Address       Data
---- ------ -------       ----
0    37544  xx.xx.xx.xx 15594277584

name: usg
tags: mac=xx:xx:xx:xx:xx:xx, model=UXG, name=Gateway, serial=xxxxxxxxx, site_name=ICAN (default), source=https://127.0.0.1:8443, type=uxg, version=3.1.16.12746
time Uptime  Address       Data
---- ------  -------       ----
0    1794644 xx.xx.xx.xx 1985168009910

name: usg
tags: mac=xx:xx:xx:xx:xx:xx, model=UXG, name=Gateway, serial=xxxxxxxxx, site_name=ICAN (default), source=https://127.0.0.1:8443, type=uxg, version=3.2.15.14839
time Uptime Address       Data
---- ------ -------       ----
0    79663  xx.xx.xx.xx 39404548588

but in the same if I run the command
select * from usg where name='*Gateway*'
ERR: error parsing query: found NAME, expected identifier, string, number, bool at line 1, char 25

It does not matter what variation I have in the name I cannot get it to work, with or without quotes.
I am clueless with influx. I have also googled and cannot get the correct syntax.

I would very much appreciate a pointer.
Thanks
Lawrence

**Comment by davidnewhall** [comment]
You probably want `DROP SERIES`. I'm also not an influx expert, and would have to consult documentation to solve the problem.

https://docs.influxdata.com/influxdb/v1/query_language/manage-database/#drop-series-from-the-index-with-drop-series

**Comment by lslamp** [comment]
@davidnewhall 
Thanks for your feedback. I have so many questions, not sure if you are the man to answer.
I assumed/thought that because you created the dashboards that you had a good understanding of the data model and how it all worked.
I am a little concerned with just dropping series. 
I don't know the impact, if I want to drop a series, 
how can I see what series are available to be dropped? 
if I drop the wrong series does that mean I loose historical data but more current data will keep being added?
I am used to working with relational databases where you can query what you want to delete before deletion. Is it the same with time series databases.
I will try to do some research.
Thanks
Lawrence

**Comment by lslamp** [comment]
@davidnewhall 
Your advice helped me loads. So please ignore my questions.
I did the following, this shows the list of the series used for usg.
SHOW SERIES FROM usg
I then ran the drop command. this cleared out all the series within usg
 drop series from usg

Now I look and I only have the single series for the USG dashboard.
What I have found is when I open dashboards now, there is a delay while data is being collected, which was not the case before.
it shows fetching services before presenting the dashboard and then many of the panels are not populated with data. This was not like this before. They were always instantaneous and very fast.

Lawrence
