### ISSUE TITLE
UDR Auth or Connection Error,

### ISSUE THREAD

**Issue by Geekllem** [unpoller/unpoller#707]
I have UDR and I have problems with the api:
[ERROR] Controller 1 of 1 Auth or Connection Error, retrying: unifi controller: (user: unifipoller): https://192.168.XXXX.1/api/auth/login (status: 403 Forbidden): authentication failed

Could you help me?
Thanks.

**Comment by platinummonkey** [comment]
Usually this will be an issue with the way it was configured. Make sure it’s a local account with all the read permissions. Make sure the password matches

**Comment by Geekllem** [comment]
I use a local account, with read permissions and the passwords matches.

Log Error:

[ERROR] Controller 1 of 1 Auth or Connection Error, retrying: unifi controller: (user: unifipoller): https://192.168.XXX.1:443/api/auth/login (status: 403 Forbidden): authentication failed
[DEBUG] Requested https://192.168.XXX.1:443/api/auth/login: elapsed 1.092s, returned 94 bytes  
[DEBUG] Requesting https://192.168.XXX.1:443/api/auth/login, with params: true, cookies: 0
[DEBUG] Using NEW UniFi controller API paths for https://192.168.XXX.1:443/
[DEBUG] Requesting https://192.168.XXX.1:443/ to determine API paths
[DEBUG] inititalizing input... unifi
[DEBUG] initializing 1 inputs
[INFO] UniFi Poller v2.7.13 Starting Up! PID: 1

 what can I do?

**Comment by platinummonkey** [comment]
You might exercise the curl command directly but the controller is rejecting the current combo

**Comment by platinummonkey** [comment]
Describe how you’re setting this up specifically with exact commands. The user/pass it has is saying this is incorrect. Certain config file formats you should also avoid certain special characters depending on which format you used as well

**Comment by Geekllem** [comment]
Environtmen variables:

UP_UNIFI_DEFAULT_URL = https://192.168.65.1:443/proxy/network
UP_UNIFI_DEFAULT_USER = unifipoller
UP_UNIFI_DEFAULT_PASS = Unifi20232023
