### ISSUE TITLE
Unable to Pull Image from Synology

### ISSUE THREAD

**Issue by mfranzel** [unpoller/unpoller#712]
Hello,
I am following the directions here: https://unpoller.com/docs/install/synology 

But when I try to search for the image ghcr.io/unpoller/unpoller like the walkthrough instructs, I only show these 9 images, which are all wrong:

![image](https://github.com/unpoller/unpoller/assets/66579594/45b0baac-0db1-4ba6-a680-a36e9b9bb6f3)

It looks like Synology Container Manager wants a Docker Hub image or URL, not GitHub. 

Do you know how I can proceed?

**Comment by platinummonkey** [comment]
it's also replicated to docker hub now https://hub.docker.com/r/golift/unifi-poller/tags

**Comment by mfranzel** [comment]
> it's also replicated to docker hub now https://hub.docker.com/r/golift/unifi-poller/tags

Thank you!!
