### ISSUE TITLE
Alerts - Prometheus Alert manager

### ISSUE THREAD

**Issue by jlpedrosa** [unpoller/unpoller#715]
Hi! 

I'm creatting this issue to talk about where your mind is at alarms for prometheus/alert manager. As the prom stack has alert manager, I think it would be great if we could provide some pre configured alarms and the options for users to add customs.

Top of my head, I think that having alarms for:
* High packet drops, packet errors.
* Device offline
* snmp traps? I don't know the unifi api, but not sure if it has the equivalent of the snmp traps available, so it can be sent out.

At least on the helm chart I can provide an automatic way to install those.

What do you think about the idea?

@davidnewhall @platinummonkey

**Comment by davidnewhall** [comment]
My thought is: Providing alarms means someone has to help users with alarms. I think system admins should configure their own alarms.

**Comment by jlpedrosa** [comment]
Hummm... tipically in prometheus world, the alarm comes with an explanation, optional a runbook. Something among this lines:

![image](https://github.com/unpoller/unpoller/assets/4932947/e5caafdc-8b0b-4d19-92f2-3c69c9cf8a7c)

I feeling that is better to have an alarm, even if you don't know how to act on it than silently failing? IDK, 2 cents, I will probably create them for me, so I was thinking if it was worth add them upstream (or in the chart). The advantage of the chart part is that can be disabled by default and enabled at will. 

I'm just a user of all the effort you did, and I'm trying to give back.

**Comment by davidnewhall** [comment]
I wonder why Ubiquiti doesn't provide these same alarms?  I suspect because of the support burden that comes with them.
