### ISSUE TITLE
Unifi Poller uses Angular Dashboard Templates for Grafana which is depreciated

### ISSUE THREAD

**Issue by cknic** [unpoller/unpoller#721]
I am using the InfluxDB dashboards and i'm getting an error in Grafana about Angular being depreciated and so many of the areas of the various dashboards are not working.

**Comment by geiseri** [comment]
it looks like it tries to offer a "migration" but I didn't see any difference.

**Comment by lslamp** [comment]
There is an easy fix for this. Only it is very time consuming and tedious.

You need to go to each and every dashboard panel do the following.
1. click on the 3 vertical dots on the top right hand side of the panel.
2. On the drop down menu, select edit.
3. on the top right hand side you can select the type of graphics used. You need to swap the current Graph (Angular) for Graph and do the same for Time Series.

I am very sorry but I cannot remember what the old settings were but the new setting should be Graph and Time Series.
Please let me know if you have issues or questions and I will try to recreate the issue and try to document the process for you to follow.
Lawrence 
PS: This is shown in other posts on this page.

**Comment by davidnewhall** [comment]
Y'all should be making your own dashboards anyway. Surely these dashes I made 6 years ago for my house don't fit all your needs. Good luck!
