### ISSUE TITLE
Auth fails with "429 Too Many Requests"

### ISSUE THREAD

**Issue by shaman007** [unpoller/unpoller#724]
Auth fails with "429 Too Many Requests":

```
2024/06/06 16:58:27 [ERROR] metric fetch for InfluxDB failed: re-authenticating to https://192.168.1.1:443: unifi controller: (user: shaman007): https://192.168.1.1:443/api/auth/login (status: 429 Too Many Requests): authentication failed: error initializing inputs
2024/06/06 16:58:46 [INFO] Re-authenticating to UniFi Controller: https://192.168.1.1:443
2024/06/06 16:58:46 [ERROR] metric fetch failed: re-authenticating to https://192.168.1.1:443: unifi controller: (user: shaman007): https://192.168.1.1:443/api/auth/login (status: 429 Too Many Requests): authentication failed: error initializing inputs
2024/06/06 16:58:57 [INFO] Re-authenticating to UniFi Controller: https://192.168.1.1:443
2024/06/06 16:58:57 [ERROR] metric fetch for InfluxDB failed: re-authenticating to https://192.168.1.1:443: unifi controller: (user: shaman007): https://192.168.1.1:443/api/auth/login (status: 429 Too Many Requests): authentication failed: error initializing inputs
2024/06/06 16:59:27 [INFO] Re-authenticating to UniFi Controller: https://192.168.1.1:443
```

Happened after I had 'Network' updated to version to 8.2.93. I run poller in container. Maybe some auth delay settings neede.

**Comment by platinummonkey** [comment]
This sounds like the upgrade might have changed some setting or caused and issue itself. I'm currently on that same version without issue.

**Comment by shaman007** [comment]
Maybe during the update itself it was trying to auth w/o success and become throttled.

**Comment by shaman007** [comment]
@platinummonkey, this is an API rate-limiting introduced in the Network 8.2.93. See https://community.ui.com/questions/Unifi-API-Rate-Limited/ba82a718-9418-46b0-8f2f-235bfc647f9b, my Home Assistant integration was ruined as well, but I'd overridden rate limits with ridiculous values so it's back. More errors in the other issue. I think this one could be closed, maybe some mention in the README needed.
