### ISSUE TITLE
metric fetch for InfluxDB failed: unifi.GetDevices - unifi 8.1.27 - cloudkey gen2 pro

### ISSUE THREAD

**Issue by ffichman** [unpoller/unpoller#726]
I install on cloudkey gen2 pro but i receive this error: metric fetch for InfluxDB failed: unifi.GetDevices
unifi network 8.1.27

**Comment by platinummonkey** [comment]
can you provide more details including the logs?

**Comment by ffichman** [comment]
sure.
2024/06/08 04:02:13 [INFO] Re-authenticating to UniFi Controller: https://controller.nextthouse.com.br:8443
Jun 08 04:02:14 UniFi-CloudKey-Gen2-Plus unpoller[18019]: 2024/06/08 04:02:14 [ERROR] metric fetch for InfluxDB failed: unifi.GetDevices(https://xxxxxx.xxxxxxx.com.br:8443): https://xxxxx.xxxxxxx.com.br:8443/api/s/72oc41ew/stat/device: 500 : invalid status code from server: error initializing inputs

**Comment by platinummonkey** [comment]
500 is a unifi device issue unfortunately. You may need to restart the device.

**Comment by ffichman** [comment]
> 500 is a unifi device issue unfortunately. You may need to restart the device.

what device? Controller on amazon?

**Comment by ffichman** [comment]
i restart controller and same issue

**Comment by platinummonkey** [comment]
the device being the one serving this API `https://xxxx..xxxxx.com.br:8443/`

If you're running the firmware on an EC2 this may be a unique issue and collect logs from the the controller itself on that host. Then I would take that to unifi support directly.

**Comment by ffichman** [comment]
> the device being the one serving this API `https://xxxx..xxxxx.com.br:8443/`
> 
> If you're running the firmware on an EC2 this may be a unique issue and collect logs from the the controller itself on that host. Then I would take that to unifi support directly.

Im running unifi controller on ec2 and unipoller on cloudkey locally on my office.
