### ISSUE TITLE
Data Spikes / Random reading of 0 every other poll

### ISSUE THREAD

**Issue by jhavens12** [unpoller/unpoller#747]
![image](https://github.com/user-attachments/assets/40c99e59-4721-451c-9084-d0e66e885521)

Picture describes it best - that was me moving data across the switch. The graph should be consistent but it looks like it's reporting 0 every other poll for some reason. Its worth noting this happens with all interfaces across all switches, but not values such as the temperature of the switches.

UDM-SE
UniFi Enterprise 10G switch

Thanks

**Comment by jhavens12** [comment]
`TZ=America/New_York
CURRENT_USER=0:0
#unifi-poller
POLLER_TAG=latest
POLLER_DEBUG=false
POLLER_SAVE_DPI=false
UNIFI_USER=unifipoller
UNIFI_PASS=REDACTED
UNIFI_URL=https://10.0.1.1

#influxdb
INFLUXDB_HTTP_AUTH_ENABLED=false
INFLUXDB_ADMIN_USER=unpoller
INFLUXDB_ADMIN_PASSWORD=unpollerpassword
INFLUXDB_DB=unpoller
INFLUXDB_ORG=unpoller
INFLUXDB_BUCKET=unpoller
INFLUXDB_ADMIN_TOKEN=unpollersecret

#grafana
GRAFANA_USERNAME=admin
GRAFANA_PASSWORD=grafanaadmin`

**Comment by jhavens12** [comment]
"2024/08/14 21:21:31 [INFO] Loading Configuration File: /etc/unpoller/up.conf
2024/08/14 21:21:31 [INFO] UniFi Poller v2.11.2 Starting Up! PID: 1
2024/08/14 21:21:31 [INFO] Found 1 site(s) on controller https://10.0.1.1: default (Default)
2024/08/14 21:21:31 [INFO] Configured UniFi Controller 1 of 1:
2024/08/14 21:21:31 [INFO]    => URL: https://10.0.1.1 (verify SSL: false)
2024/08/14 21:21:31 [INFO]    => Version:  (6d84f96e-d8b9-5e6e-950c-50221a39acde)
2024/08/14 21:21:31 [INFO]    => Username: unifipoller (has password: true)
2024/08/14 21:21:31 [INFO]    => Hash PII false / Drop PII false / Poll Sites: all
2024/08/14 21:21:31 [INFO]    => Save Sites true / Save DPI false (metrics)
2024/08/14 21:21:31 [INFO]    => Save Events false / Save IDS false (logs)
2024/08/14 21:21:31 [INFO]    => Save Alarms false / Anomalies false (logs)
2024/08/14 21:21:31 [INFO]    => Save Rogue APs: false
2024/08/14 21:21:31 [INFO] Prometheus is enabled
2024/08/14 21:21:31 [INFO] InfluxDB enabled
2024/08/14 21:21:31 [INFO] Poller->InfluxDB started, version: 2, interval: 30s, dp: false, db: unpoller, url: http://influxdb:8086, bucket: unpoller, org: unpoller
2024/08/14 21:21:31 [INFO] Prometheus exported at http://0.0.0.0:9130/ - namespace: unpoller
2024/08/14 21:22:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 54, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 159, Fields: 4501, Err: 0, Dur: 146ms
2024/08/14 21:22:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 54, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 159, Fields: 4501, Err: 0, Dur: 44ms
2024/08/14 21:23:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 54, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 159, Fields: 4501, Err: 0, Dur: 42ms
2024/08/14 21:23:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 54, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 159, Fields: 4501, Err: 0, Dur: 38ms
2024/08/14 21:24:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 53, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 158, Fields: 4467, Err: 0, Dur: 39ms
2024/08/14 21:24:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 53, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 158, Fields: 4467, Err: 0, Dur: 49ms
2024/08/14 21:25:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 53, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 158, Fields: 4467, Err: 0, Dur: 33ms
2024/08/14 21:25:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 55, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 160, Fields: 4535, Err: 0, Dur: 34ms
2024/08/14 21:26:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 55, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 160, Fields: 4535, Err: 0, Dur: 38ms
2024/08/14 21:26:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 55, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 160, Fields: 4535, Err: 0, Dur: 41ms
2024/08/14 21:27:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 55, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 160, Fields: 4535, Err: 0, Dur: 44ms
2024/08/14 21:27:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 55, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 160, Fields: 4535, Err: 0, Dur: 42ms
2024/08/14 21:28:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 55, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 160, Fields: 4535, Err: 0, Dur: 45ms
2024/08/14 21:28:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 55, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 160, Fields: 4535, Err: 0, Dur: 35ms
2024/08/14 21:29:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 55, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 160, Fields: 4535, Err: 0, Dur: 43ms
2024/08/14 21:29:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 55, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 160, Fields: 4535, Err: 0, Dur: 61ms
2024/08/14 21:30:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 54, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 159, Fields: 4501, Err: 0, Dur: 67ms
2024/08/14 21:30:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 54, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 159, Fields: 4501, Err: 0, Dur: 43ms
2024/08/14 21:31:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 54, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 159, Fields: 4501, Err: 0, Dur: 54ms
2024/08/14 21:31:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 54, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 159, Fields: 4501, Err: 0, Dur: 41ms
2024/08/14 21:32:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 54, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 159, Fields: 4501, Err: 0, Dur: 35ms
2024/08/14 21:32:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 54, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 159, Fields: 4501, Err: 0, Dur: 32ms
2024/08/14 21:33:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 54, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 159, Fields: 4501, Err: 0, Dur: 41ms
2024/08/14 21:33:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 54, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 159, Fields: 4501, Err: 0, Dur: 50ms
2024/08/14 21:34:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 54, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 156, Fields: 4450, Err: 0, Dur: 45ms
2024/08/14 21:34:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 55, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 157, Fields: 4484, Err: 0, Dur: 40ms
2024/08/14 21:35:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 56, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 161, Fields: 4569, Err: 0, Dur: 72ms
2024/08/14 21:35:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 56, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 161, Fields: 4569, Err: 0, Dur: 57ms
2024/08/14 21:36:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 56, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 160, Fields: 4552, Err: 0, Dur: 32ms
2024/08/14 21:36:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 56, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 159, Fields: 4535, Err: 0, Dur: 41ms
2024/08/14 21:39:11 [INFO] UniFi Metrics Recorded. Site: 1, Client: 56, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 161, Fields: 4569, Err: 0, Dur: 50ms
2024/08/14 21:39:11 [INFO] UniFi Metrics Recorded. Site: 1, Client: 56, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 161, Fields: 4569, Err: 0, Dur: 47ms
2024/08/14 21:39:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 56, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 161, Fields: 4569, Err: 0, Dur: 50ms
2024/08/14 21:40:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 56, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 161, Fields: 4569, Err: 0, Dur: 37ms
2024/08/14 21:40:32 [INFO] UniFi Metrics Recorded. Site: 1, Client: 56, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 160, Fields: 4552, Err: 0, Dur: 51ms
2024/08/14 21:41:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 56, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 161, Fields: 4569, Err: 0, Dur: 43ms
2024/08/14 21:41:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 56, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 161, Fields: 4569, Err: 0, Dur: 40ms
2024/08/14 21:42:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 57, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 162, Fields: 4603, Err: 0, Dur: 48ms
2024/08/14 21:42:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 57, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 162, Fields: 4603, Err: 0, Dur: 42ms
2024/08/14 21:43:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 57, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 162, Fields: 4603, Err: 0, Dur: 42ms
2024/08/14 21:43:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 58, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 160, Fields: 4586, Err: 0, Dur: 43ms
2024/08/14 21:44:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 59, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 163, Fields: 4654, Err: 0, Dur: 37ms
2024/08/14 21:44:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 59, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 164, Fields: 4671, Err: 0, Dur: 44ms
2024/08/14 21:45:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 58, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 162, Fields: 4620, Err: 0, Dur: 40ms
2024/08/14 21:45:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 58, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 163, Fields: 4637, Err: 0, Dur: 49ms
2024/08/14 21:46:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 58, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 163, Fields: 4637, Err: 0, Dur: 44ms
2024/08/14 21:46:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 57, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 162, Fields: 4603, Err: 0, Dur: 46ms
2024/08/14 21:47:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 58, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 163, Fields: 4637, Err: 0, Dur: 41ms
2024/08/14 21:47:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 58, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 163, Fields: 4637, Err: 0, Dur: 39ms
2024/08/14 21:48:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 58, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 163, Fields: 4637, Err: 0, Dur: 46ms
2024/08/14 21:48:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 58, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 163, Fields: 4637, Err: 0, Dur: 52ms
2024/08/14 21:49:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 58, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 163, Fields: 4637, Err: 0, Dur: 48ms
2024/08/14 21:49:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 58, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 163, Fields: 4637, Err: 0, Dur: 46ms
2024/08/14 21:50:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 59, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 164, Fields: 4671, Err: 0, Dur: 39ms
2024/08/14 21:50:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 59, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 164, Fields: 4671, Err: 0, Dur: 42ms
2024/08/14 21:51:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 59, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 164, Fields: 4671, Err: 0, Dur: 37ms
2024/08/14 21:51:31 [INFO] Re-authenticating to UniFi Controller: https://10.0.1.1
2024/08/14 21:51:32 [ERROR] metric fetch for InfluxDB failed: unifi.GetClients(https://10.0.1.1): unexpected end of JSON input: error initializing inputs
2024/08/14 21:52:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 59, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 164, Fields: 4671, Err: 0, Dur: 40ms
2024/08/14 21:52:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 59, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 164, Fields: 4671, Err: 0, Dur: 49ms
2024/08/14 21:53:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 59, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 164, Fields: 4671, Err: 0, Dur: 45ms
2024/08/14 21:53:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 59, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 164, Fields: 4671, Err: 0, Dur: 47ms
2024/08/14 21:54:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 59, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 164, Fields: 4671, Err: 0, Dur: 46ms
2024/08/14 21:54:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 59, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 164, Fields: 4671, Err: 0, Dur: 47ms
2024/08/14 21:55:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 58, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 163, Fields: 4637, Err: 0, Dur: 37ms
2024/08/14 21:55:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 58, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 163, Fields: 4637, Err: 0, Dur: 49ms
2024/08/14 21:56:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 58, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 163, Fields: 4637, Err: 0, Dur: 48ms
2024/08/14 21:56:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 58, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 163, Fields: 4637, Err: 0, Dur: 44ms
2024/08/14 21:57:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 58, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 163, Fields: 4637, Err: 0, Dur: 46ms
2024/08/14 21:57:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 58, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 163, Fields: 4637, Err: 0, Dur: 45ms
2024/08/14 21:58:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 58, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 163, Fields: 4637, Err: 0, Dur: 45ms
2024/08/14 21:58:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 58, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 163, Fields: 4637, Err: 0, Dur: 59ms
2024/08/14 21:59:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 58, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 163, Fields: 4637, Err: 0, Dur: 70ms
2024/08/14 21:59:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 58, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 163, Fields: 4637, Err: 0, Dur: 52ms
2024/08/14 22:00:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 58, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 163, Fields: 4637, Err: 0, Dur: 44ms
2024/08/14 22:00:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 58, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 163, Fields: 4637, Err: 0, Dur: 46ms
2024/08/14 22:01:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 55, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 160, Fields: 4535, Err: 0, Dur: 39ms
2024/08/14 22:01:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 55, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 160, Fields: 4535, Err: 0, Dur: 36ms
2024/08/14 22:02:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 55, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 160, Fields: 4535, Err: 0, Dur: 60ms
2024/08/14 22:02:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 55, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 160, Fields: 4535, Err: 0, Dur: 33ms
2024/08/14 22:03:01 [INFO] UniFi Metrics Recorded. Site: 1, Client: 55, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 160, Fields: 4535, Err: 0, Dur: 44ms
2024/08/14 22:03:31 [INFO] UniFi Metrics Recorded. Site: 1, Client: 55, Gateways: 1, UAP: 5, USW: 7, IDS/Event/Alarm/Anomaly: 0/0/0/0, DPI Site/Client: 0/0, Point: 160, Fields: 4535, Err: 0, Dur: 55ms"

**Comment by jhavens12** [comment]
![image](https://github.com/user-attachments/assets/e0362fb0-1ff7-48ca-bdf5-82643c2bec35)

**Comment by jhavens12** [comment]
I tried this again in a completely different VM using a different config method and the results are the same. Are the readings coming from the UDM-SE like this?

**Comment by jhavens12** [comment]
UDM-SE Firmware version: v4.0.6

**Comment by jhavens12** [comment]
I just set this up in an entirely different environment (Unifi Express instead of UDM-SE) with a different virtual machine on a different network and have the same issues.

**Comment by platinummonkey** [comment]
> I tried this again in a completely different VM using a different config method and the results are the same. Are the readings coming from the UDM-SE like this?

Yes. Unpoller is simply taking what the unifi api returns and reporting that

**Comment by jhavens12** [comment]
> > I tried this again in a completely different VM using a different config method and the results are the same. Are the readings coming from the UDM-SE like this?
> 
> Yes. Unpoller is simply taking what the unifi api returns and reporting that

Is there an issue with the current Unifi API? Or am I missing something in my setup?

**Comment by jhavens12** [comment]
I can confirm that this issue is not present when using SNMP monitoring (Using PRTG to view the SNMP data) using the same UDM-SE and switching hardware

**Comment by platinummonkey** [comment]
that leads me to believe the device is fine, but the data the apis are returning is not. Which means you'll need to contact ubiquiti support

**Comment by davidnewhall** [comment]
Set the polling interval to 1m instead of 30s. Should give you immediate relief. Some APIs just won't update that often, and some folks have had to use 90s or 2m.

**Comment by jhavens12** [comment]
Thanks - that would make sense. How do I set the polling interval? I don't see it documented in the docker-compose section.

Thanks

**Comment by platinummonkey** [comment]
https://github.com/unpoller/unpoller/blob/master/examples/up.conf.example#L47-L50

**Comment by jhavens12** [comment]
Thanks I saw that - but that is for the config file setup instead of the .env file setup like I have.
I guessed with POLLER_INTERVAL=60s, but either I guessed wrong or it didn't resolve my issue

**Comment by platinummonkey** [comment]
the environment variable naming over a config file is of the pattern `UP_{SECTION}_{KEY}={VALUE}`

so here it should be like `UP_INFLUXDB_INTERVAL=...`

**Comment by jhavens12** [comment]
Thank you - that seems to have fixed my issue. It's too bad the API is so limited

**Comment by jhavens12** [comment]
Coming back to this - why are other people not having the same issues? Currently running:

UniFi Poller v2.11.2 UniFi OS 4.0.20 Network 8.5.6

**Comment by platinummonkey** [comment]
It seems to depend on what you have all connected is how the unifi api will return and aggregate data. My personal setup the default settings work just fine, but it’s a home and homelab setup vs a business setup or larger home setup
