### ISSUE TITLE
Privacy by default

### ISSUE THREAD

**Issue by mschmitt** [unpoller/unpoller#748]
I provide a high-level quantitative view for a client's Wifi with hundreds of quickly fluctuating guest devices. While setting up _unpoller_, I noticed the following in `/etc/unpoller/up.conf`:

https://github.com/unpoller/unpoller/blob/f7b78fa0c1f45a7b19529ce27e34a2b65fedc393/examples/up.conf.example#L159-L161

It seems unlikely that _most_ Grafana instances require access to all of the "Alice's Galaxy S23" hostnames. Would it be unreasonable to suggest making `hash_pii=true` the default (not sure about the role of the undocumented `drop_pii`?) and to rephrase the comment to say "most users won't need to enable this"?

**Comment by davidnewhall** [comment]
I'm trying to understand the problem you ran into so we can make sure there's a proper correction. 

Changing default values for config options is almost never appropriate (it would completely wreck my graphs for instance). I'm not sure I understand the problem though so it's not clear how changing the default solves it. Please elaborate.

I also do not understand what this sentence means, and perhaps that's why I'm not understanding the problem description.

> It seems unlikely that most Grafana instances require access to all of the "Alice's Galaxy S23" hostnames.

**Comment by mschmitt** [comment]
Hey David, thanks for the quick response!

If you look into any client-related metric, say `unpoller_client_anomalies`, you will see the client-provided hostnames (let's ignore the MAC addresses, since I hardly see any remaining clients who don't randomize them):

```
curl -s http://localhost:9130/metrics | grep unpoller_client_anomalies | head -10
```

The client-provided _"Alice's Galaxy S23"_ will appear here as the `name` attribute.

This actually works for me and yields a number of results:

```
curl -s http://localhost:9130/metrics | grep unpoller_client_anomalies | grep Galaxy
...
...name="Galaxy-S10-von-Erik"...
```

`hash_pii=true` in `up.conf` will replace the client-provided name with an MD5 hash of itself.

`drop_pii=true` in `up.conf` will substitute the name, MAC and Vendor OUI with empty strings.

I see that `drop_pii=true` with its empty strings may bring potential breakage to consuming systems, but it may be undocumented for a reason, so let's not focus on that.

It's interesting that you fear your graphs will break from anonymization of this data, while it is hidden so well that you've apparently never seen it. And yet, it's being collected and pipelined all the way from the Unifi console via Prometheus to Grafana, maybe with a tiny bit of permanent retention in Influxdb.

My suggestion is to rephrase and pre-populate the _"pii"_ section in `up.conf` in a way that encourages privacy-aware behaviour:

```
  # Hash, with md5, client names and MAC addresses. This attempts to protect
  # personally identifiable information. Most users won't want to disable this.
  hash_pii = true
```

**Comment by davidnewhall** [comment]
> It's interesting that you fear your graphs will break from anonymization of this data, while it is hidden so well that you've apparently never seen it. And yet, it's being collected and pipelined all the way from the Unifi console via Prometheus to Grafana, maybe with a tiny bit of permanent retention in Influxdb.

No one in my house has a Galaxy. I created this because I use UniFi at home. 

I don't see any problem updating comments in the config file.
