### ISSUE TITLE
UAP-AC-Pro Showing up in usw_ports

### ISSUE THREAD

**Issue by bigjohns97** [unpoller/unpoller#752]
I am getting this weird situation where my UAP-AC-Pro is showing up on my USW Insight dashboard because for some reason it is ending up in my usw_ports table. 

I understand I can just use the variable at the top to limit to usw but would rather find out why this is ending up in the table if possible.

Any ideas?

**Comment by davidnewhall** [comment]
Your UAP has 1 or 2 switch ports, so it shows up in the switch table. Very expected.

**Comment by bigjohns97** [comment]
That does make sense, after looking through all of my AP's this is the only one that has that extra ethernet port.

I guess I will just use the top of dashboard filters, thanks @davidnewhall .
