### ISSUE TITLE
Support Cloud Gateway Ultra

### ISSUE THREAD

**Issue by mcmarko70** [unpoller/unpoller#770]
Any plans on adding support for the Cloud Gateway Ultra?

**Comment by davidnewhall** [comment]
Does it have an API you can access from where you run unpoller?

**Comment by mcmarko70** [comment]
I can access it via the web menu like "https://10.10.10.1." 
![CGU_Gatway_login_screen](https://github.com/user-attachments/assets/775db9b8-0aa7-4ec7-902c-6ea255d83068)

**Comment by davidnewhall** [comment]
You put the config file in the wrong place. This is inaccurate:
```
volumes:
- /root/docker/unifi-poller:/home/grafana/config
```

**Comment by mcmarko70** [comment]
where should I put it? Can you help me with some advice?

**Comment by davidnewhall** [comment]
At [`/config/unifi-poller.conf`](https://github.com/unpoller/unpoller/blob/master/pkg/poller/config.go#L39)

**Comment by mcmarko70** [comment]
I have fixed and reloaded docker and I still have a similar error.
![image](https://github.com/user-attachments/assets/ef64ea8e-befb-483f-8a24-5f384abec428)

**Comment by davidnewhall** [comment]
You still haven't given it a config file.

**Comment by mcmarko70** [comment]
root@grafana:~/docker# cat docker-compose.yml
services:
   infuxdb:
     container_name: up_infuxdb
     restart: unless-stopped
     image: influxdb:1.8
     ports:
      - '8086:8086'
     volumes:
       - influxdb:/var/lib/influxdb
     environment:
       - INFLUXDB_DB=unifi
       - INFLUXDB_ADMIN_USER=unifi
       - INFLUXDB_ADMIN_PASSWORD=unifi

   grafana:
     container_name: up_grafana
     image: grafana/grafana
     restart: unless-stopped
     user: 1000:1000
     ports:
        - '3000:3000'
     volumes:
       - grafana:/var/lib/grafana
     depends_on:
       - infuxdb
     environment:
       - GF_SECURITY_ADMIN_USER=admin
       - GF_INSTALL_PLUGINS=grafana-clock-panel,natel-discrete-panel,grafana-piechart-panel
   unifi-poller:
     container_name: up_poller
     restart: unless-stopped
     image: golift/unifi-poller:latest
     depends_on:
       - infuxdb
       - grafana
     volumes:
       - /root/docker/unifi-poller:/config/unifi-poller.conf

volumes:
  influxdb:
  grafana:
  unifipoller:
root@grafana:~/docker#
root@grafana:~/docker# cat unifi-poller/unifi-poller.conf
[unifi.defaults]
  url = "https://10.10.10.1"
  user = "unifipoller"
  pass = "password"
  save_dpi = true
[influxdb]
  url = "http://10.10.10.248:8086"
root@grafana:~/docker#
