### ISSUE TITLE
unpoller does not find JSON config file

### ISSUE THREAD

**Issue by SunSparc** [unpoller/unpoller#776]
When I start the app it will only look for the config at `/etc/unifi-poller/up.conf`:
```
2024/11/27 00:29:51 [ERROR] finding file: stat /etc/unifi-poller/up.conf: no such file or directory
```
I put a JSON formatted file in both of the suggested locations:
```
/etc/unifi-poller/up.json
/config/up.json
```
Is JSON no longer supported?

**Comment by SunSparc** [comment]
I am starting the application as a [Nomad job](https://www.nomadproject.io/) using the `exec` driver.

The binary that is being used is: `https://github.com/unpoller/unpoller/releases/download/v2.11.2/unpoller_2.11.2_linux_amd64.tar.gz`

In other words, it is running in a Linux environment.

After unpacking the binary, I run the binary directly as an executable: `/unpoller`

I am not passing any arguments to it as I did not see an argument that would allow me to specify a custom location for the config file.

**Comment by davidnewhall** [comment]
How about adding `-c /path/to/config.json` as an argument? You can see all the available arguments with `-h`.

**Comment by SunSparc** [comment]
@davidnewhall, thank you. Using `-c` as an argument to the command. And I feel dumb for not checking for the `-h` reference on the command line. 🤦
