### ISSUE TITLE
No Metrics available on USG Insights dashboard

### ISSUE THREAD

**Issue by bgatestmg** [unpoller/unpoller#782]
No Metrics available on USG Insights dashboard when using Unifi official hosting and UXG Max gateways

![Screenshot 2024-12-19 at 2 30 01 PM](https://github.com/user-attachments/assets/eda4b4ba-c4b5-4b91-9d8f-a82fe1c46f0d)
![Screenshot 2024-12-19 at 2 30 43 PM](https://github.com/user-attachments/assets/f2de7012-27b3-4899-aa2c-bf6343f2ac56)

**Comment by platinummonkey** [comment]
Please open this on unpoller/dashboards. But also please detail your setup, verify that data is flowing and detail what you’ve tried including changing Params etc
