### ISSUE TITLE
Mandatory 2FA and Unpoller

### ISSUE THREAD

**Issue by papylhomme** [unpoller/unpoller#784]
Hello,

my account was forcibly migrated to use 2FA, and now Unpoller can't connect to extract metrics (and massively spam my inbox with 2FA authentication code :D) .

I gather from https://github.com/unpoller/unpoller/issues/218 that disabling 2FA was a requirement for Unpoller, any hope it could work one way or another in the future ?

**Comment by PythonCoderAS** [comment]
You can create a local account without 2FA and use that.

**Comment by papylhomme** [comment]
Thanks I missed that part somehow, it's working fine with a local account.
